### ISSUE TITLE
Rendering in webinterface doesn't group fields

### ISSUE THREAD

**Issue by helmut72** [nextcloud/contacts#1327] opened 2019-11-06 07:51 UTC
**To Reproduce**

1. Open a Browser
2. Login to Nextcloud
3. Go to Contacts

**Expected behavior**
Phone number and Mail address fields should be grouped together

**Actual behavior**
One Mail address is under one Phone number, 2nd Phone number is next to the 1st, but not in the same line.

**Screenshots**

![Bildschirmfoto 2019-11-06 um 08 36 19](https://user-images.githubusercontent.com/1388751/68278670-224d8980-0072-11ea-9f9c-a238d8542979.png)

### Versions

Nextcloud 17.0.0

Safari 13 (doesn't respect standards?)

But also with:
Firefox 63
Chrome 78

Don't have tried Lynx

### Display

common 24" with 1080p resolution with maximized window

**Comment by skjnldsv** [comment] 2019-11-07 10:53
Duplicate of #654

**Closed by skjnldsv** 2019-11-07 10:53 UTC
Labels: 0. Needs triage, bug
