### ISSUE TITLE
Contacts web app: phone numbers with custom type not shown

### ISSUE THREAD

**Issue by poiNt3D** [nextcloud/contacts#1020] opened 2019-03-27 10:03 UTC
### Describe the bug
There is no feature to add custom phone type in contacts web interface.
But if you have contacts with custom-type phone numbers (added by Android), these phone numbers will not be shown. 
......
......

**To Reproduce**
1. Edit your contact on Android and set phone number to 'Custom'.
2. Sync to Nextcloud using DavX.
3. Open your Nextcloud website and open Contacts.
4. Find your contact and see no phone number.

**Expected behavior**
At least it's expected to see all phone numbers.
Ability to add custom types would be great.

**Screenshots**

### Server configuration

**Operating system**: Android, Web-client

**Web server:** Apache

**Database:** MySQL,

**PHP version:** 7.0

**Nextcloud version:**  Nextcloud 15.0.5

**Contacts version:** 3.0.5

**Updated from an older Nextcloud or fresh install:**
Updated 13 -> 14 -> 15
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.4
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

**Nextcloud configuration:**
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\***REMOVED SENSITIVE VALUE***/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }

### Client configuration
**Browser:** Mozilla Firefox 66.0.1

**Operating system:** Windows

**CardDAV-clients:** DavX

### Logs

### Nextcloud log
#### *data/nextcloud.log*

empty

#### Browser log

JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
New search handler registered search.js:67:4
Connected to dav! 
Object { rootUrl: Getter & Setter, advertisedFeatures: Getter & Setter, currentUserPrincipal: Getter & Setter, principalCollections: Getter & Setter, calendarHomes: Getter & Setter, addressBookHomes: Getter & Setter, parser: Getter & Setter, _isConnected: Getter & Setter, _request: Getter & Setter, … }
Contacts.vue:272

​
#### VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:8ca61679-f6ec-4085-a95c-9a4e0997f472
FN:Test123
N:;Test123;;;
TEL;TYPE=cell:+71111111111
DAVDROID1.TEL;TYPE=x-test:+722222222222
DAVDROID1.X-ABLABEL:Test
REV:20190327T093905Z
END:VCARD

**Comment by poiNt3D** [comment] 2019-03-27 10:04
![nextcloud-report](https://user-images.githubusercontent.com/2190153/55067471-d6c10f00-5090-11e9-9ed1-1b72e345bb3b.png)

**Comment by skjnldsv** [comment] 2019-03-27 10:07
> DAVDROID1.TEL;TYPE=x-test:+722222222222
> DAVDROID1.X-ABLABEL:Test

Okay, I get it now :)
Duplicate of #42

**Closed by skjnldsv** 2019-03-27 10:07 UTC
