### ISSUE TITLE
5.4 - Cannot save "Contact Groups" selection

### ISSUE THREAD

**Issue by bstin** [nextcloud/contacts#3623] opened 2023-09-17 14:24 UTC
### Describe the bug

Since the upgrade to 5.4, its no longer possible to save a contract to a group. You can choose the group from the list, however it never saves. 

### Steps to reproduce

1. Go to any contact
2. Click on group to assign it
3. Click 'save'
4. See that Contact has no group associated with it

### Expected behavior

Should save contact group

### Actual behavior

Doesn't save contact group selection

### Contact version

5.4

### Operating system

RHEL 8

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by tilosp** [comment] 2023-09-17 15:42
Duplicate of #3614

**Closed** 2023-09-17 15:58 UTC
Labels: bug, feature: contacts, 0. Needs triage
