### ISSUE TITLE
Export a list with contacts

### ISSUE THREAD

**Issue by radoeka** [nextcloud/contacts#764] opened 2018-12-16 13:07 UTC
**Is your feature request related to a problem? Please describe.**
Export contacts, to be able to print them as a list.

**Describe the solution you'd like**
For the holiday season I marked xcontacts that I want to contact (added them to the group xmas).

I want to print a list with these contacts based on the group.
As I only need some fields, make it also possible to select the contact fields (name, address) to be exported.
Export to csv is sufficient.

**Describe alternatives you've considered**
I now copied and pasted the contacts from the web interface, which is cumbersome but it works.

**Additional context**

**Comment by skjnldsv** [comment] 2019-01-17 14:56
Duplicate of #277 :)

**Closed by skjnldsv** 2019-01-17 14:56 UTC
Labels: enhancement
