### ISSUE TITLE
Configure Birthday Reminders

### ISSUE THREAD

**Issue by tvollscw** [nextcloud/contacts#1752] opened 2020-08-20 16:03 UTC
**Is your feature request related to a problem? Please describe.**
I would like to increase the reminder time for my contact birthdays to be a week in advance (so i can plan ahead if presents are due). Currently, I don't see this as an option.

**Describe the solution you'd like**
Add a reminder option (little bell icon) to the contact page, right beside the selected contact's birthday, so that you can easily configure your reminder settings for each contact.

**Comment by skjnldsv** [comment] 2020-08-21 06:06
Duplicate of https://github.com/nextcloud/server/issues/1505

**Closed by skjnldsv** 2020-08-21 06:06 UTC
Labels: 0. Needs triage, enhancement
