### ISSUE TITLE
Nextcloud users in the Contacts application

### ISSUE THREAD

**Issue by octopus-post** [nextcloud/contacts#1274] opened 2019-09-26 09:19 UTC
I am the Nextcloud administrator at my company. There are 30 Nextcloud users. I want to add all users to the contact list. But this can only be done manually. It would be great if in the Contacts application I could see all my users and add information for each of them.

Nextcloud 16.0.4
Contacts app 3.1.3

**Comment by skjnldsv** [comment] 2019-09-26 09:25
Duplicate of #243 and/or #1117

**Closed by skjnldsv** 2019-09-26 09:25 UTC
