### ISSUE TITLE
Suggestion : XMPP field

### ISSUE THREAD

**Issue by qwertygc** [nextcloud/contacts#109] opened 2017-01-28 10:40 UTC
Hi !
I have a little suggestion about contacts field : it's possible to add a field « xmpp address » ? Because, i have numerous of contact use XMPP and it's no pratical no write in note field.
Regards

**Comment by MariusBluem** [comment] 2017-02-05 22:30
`6.4.3.  IMPP

   Purpose:  To specify the URI for instant messaging and presence
      protocol communications with the object the vCard represents.

   Value type:  A single URI.

   Cardinality:  *

   Special notes:  The property may include the "PREF" parameter to
      indicate that this is a preferred address and has the same
      semantics as the "PREF" parameter in a TEL property.
 
      If this property's value is a URI that can be used for voice
      and/or video, the TEL property (Section 6.4.1) SHOULD be used in
      addition to this property.

      This property is adapted from [RFC4770], which is made obsolete by
      this document.

   ABNF:

     IMPP-param = "VALUE=uri" / pid-param / pref-param / type-param
                / mediatype-param / altid-param / any-param
IMPP-value = URI

   Example:

       IMPP;PREF=1:xmpp:alice@example.com`

...so it should be possible with vCard 4.0 🙈 (https://tools.ietf.org/html/rfc6350#section-5)
However: @nextcloud/contacts - do you think it would make sense? 🤔

**Comment by qwertygc** [comment] 2017-02-05 22:32
Nice !

**Comment by jancborchardt** [comment] 2017-05-23 09:57
Isn’t this part of the »Instant messaging« field?

**Comment by qwertygc** [comment] 2017-05-25 15:50
Yes, when i sync with my phone, it's put xmpp:alice@example.org

**Comment by jancborchardt** [comment] 2017-07-04 18:44
I’m closing this as a duplicate of https://github.com/nextcloud/contacts/issues/130 since it’s a more general issue about further social media / communication items. :)

**Closed by jancborchardt** 2017-07-04 18:44 UTC
Labels: enhancement
