### ISSUE TITLE
Direct link to contact

### ISSUE THREAD

**Issue by janpekar** [nextcloud/contacts#868] opened 2019-01-18 10:52 UTC
I have shared contact lists on my nextcloud with users.

I would like to create link to contact and share that link with other users.
I noticed, that contact has some UID, which is generated to URL (when I'm searching the name), but this link is not working, when I open it in new tab or I share it with another user (who is sharing the same contact list with me). The link also contains my contact list name, which can be different for another user, so it looks useless.

Is it possible to create direct link to a contact somehow?

Thank you

**Comment by skjnldsv** [comment] 2019-01-21 09:30
Hello!

I'm not sure I get your question. Are you talking about the contacts menu on the top right header?

**Comment by janpekar** [comment] 2019-01-21 09:43
I'm talking about creating link to some certain contact in my contact list so I can share that link (send by email for example) and any other user that I'm sharing contact list with, can open the link and see contact details of that person.

**Comment by skjnldsv** [comment] 2019-01-21 09:46
Ah, sorry :)
You cannot publicly share contacts on nextcloud (yet?)

Your request is a duplicate of https://github.com/nextcloud/contacts/issues/111 ;)

**Comment by janpekar** [comment] 2019-01-21 09:55
It is not duplicate of #111 - I don't want to share single contact. I have shared with my colegues whole contact list, so they all see the same contacts as I see, but when I want to point somebody to some certain contact for example Mr. John Smith and I have two John Smith contacts (different people) I just want to link to the correct one. 
I notice UUID in URL, but it is not opening any contact, when I save that link to that contact and open it in another tab (even in my browser instance).

**Comment by skjnldsv** [comment] 2019-01-21 10:35
@janpekar Sorry
Then I really don't get you issue.
So assuming:
1. you have a contact with the uuid XXXXX
2. you shared the addressbook the XXXXX contact belong to with one of your user on nextcloud

When you share the url xxxx.xxx/apps/contacts/All%20contacts/XXXXX~addressbook to your user, it does not open the contact in his/her nextcloud instance?

**Comment by janpekar** [comment] 2019-01-21 10:49
Yes, you are right -  it does not open the contact in his/her nextcloud instance
It does not even open in my instance (in another tab). 

Also - you mentioned xxxx.xxx/apps/contacts/All%20contacts
but when you map shared addressbook, you can rename it. 
Also - when you use localization, it is no All%20contacts, but it is in different language etc.

So that is my problem. Hope now it is clear.

**Comment by skjnldsv** [comment] 2019-01-21 11:51
All%20contacts is translated depending on your locale yes.
Mine was set in English.

> It does not even open in my instance (in another tab).

This is an issue. What nextcloud version are you using?

**Comment by janpekar** [comment] 2019-01-21 18:58
I noticed, that is working for some contacts, but I can find some contacts, where it is not, so some debugging is necessary.

I'm using Nextcloud 14.0.4, Contact app 2.1.8

**Comment by skjnldsv** [comment] 2019-01-21 19:49
What happens when it's not working?
Error message? Redirect to files? White page?

**Comment by janpekar** [comment] 2019-01-21 20:09
When I open problematic contact link, page is loading at contacts page and after my contacts are loaded (after few seconds page fills with contacts) it opens the first contact, that is in my list and URL (UUID in URL) changes/rewrites to that first contact.

**Comment by skjnldsv** [comment] 2019-01-22 08:55
> I'm using Nextcloud 14.0.4, Contact app 2.1.8

Okay, now I get it!
Please update to the latest. I should have asked for that first ^^
Please reopen if it still happens on nc15 and contacts 3.0.0

**Closed by skjnldsv** 2019-01-22 08:55 UTC
Labels: need info

**Comment by thomas-mc-work** [comment] 2022-09-06 07:16
I'm facing the same problem. I'm unable to send the URL of a contact to other users of the same instance. The address book is shared with the receiver. The first contact is selected when the receiver opens the link.

**Comment by janpekar** [comment] 2022-09-06 11:54
And do they have same language settings?

**Comment by thomas-mc-work** [comment] 2022-09-06 12:08
Yes. Though I'd expect this to be independent of the selected language, as it is with internal file links in the file app.
