### ISSUE TITLE
Trying to add "Nickname" brings up 2 fields

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#1485] opened 2020-02-26 08:21 UTC
When you choose to add a nickname, you get 2 fields which is quite confusing:
![Contacts nickname results in 2 fields being shown](https://user-images.githubusercontent.com/925062/75325462-742d5000-58ab-11ea-9191-82460060ec34.png)

You can separately delete them, which doesn’t clear up the confusion. :) Only one field should be shown.

@skjnldsv if you point out where in the code this has to be changed or what the reasoning is, this could be a good first issue?

**Comment by skjnldsv** [comment] 2020-02-26 10:06
duplicate of https://github.com/nextcloud/contacts/issues/1464

**Closed by skjnldsv** 2020-02-26 10:06 UTC
Labels: 1. to develop, bug, good first issue
