### ISSUE TITLE
contact display on widescreen is confusing

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1087] opened 2019-05-02 17:34 UTC
### Steps to reproduce
1. create a contact
2. add some contact details

-- precondition: big screen resolution (e.g. 1920x1200), will not be reproducible on smaller screens (like 19" monitor with 1200x800)
-- reproducible with Firefox, Vivaldi, Chrome (didn't try others)

### Expected behaviour
A) the contact details are well-grouped on all screen sizes
b) The usually bigger field ORG will take more space than the usually not that big field TITLE

### Actual behaviour
A) The arragement of the contact fields on bigger screens (e.g. 24" screen that allows three rows to be displayed) is confusing and incomprehensible.
B) The ORG field is cutted, the TITLE field has normal size, and there is a lot of unneccessary whitespace to the right

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
15.0.7

**Contacts version:** (see Nextcloud apps page)
3.1.1

![screenshot02](https://user-images.githubusercontent.com/11940089/57094491-f3e0a180-6d10-11e9-8653-01205be959a9.png)

**Comment by skjnldsv** [comment] 2019-05-02 18:00
Duplicate of #654

**Closed by skjnldsv** 2019-05-02 18:00 UTC
