### ISSUE TITLE
unable to share address book

### ISSUE THREAD

**Issue by mevolu** [nextcloud/contacts#3445] opened 2023-06-08 04:25 UTC
### Describe the bug

I want to share an address book, but in the field "share with users or groups" i get no results. It worked with the 5.2 contacts app.

### Steps to reproduce

1. Go to 'contacts'
2. Click on 'Contacts settings'
3. Click on the share symbol from an address book
4. Put in a user or group name on the server

### Expected behavior

When I put in the user or group name there should be a list shown with the user or group on the server that I can click on for sharing the address book.

### Actual behavior

"No results" shown even if the user or group exist on the server.

### Contact version

 5.3.0

### Operating system

nextcloud-aio docker

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by polendri** [comment] 2023-06-08 06:28
I'm also experiencing this; seems high-priority to me since it breaks sharing entirely. Mine is a brand-new install of Nextcloud 26.0.2 / Contacts 5.3.0.

Some additional technical details:

1. When I click the "share" icon for an address book, I see a warning in the browser console stating "You need to fill either the text or the ariaLabel props in the button component.".
2. Otherwise, nothing happens at all in the console or over the network when I type into the search box.

I would speculate that maybe the event handler for the input isn't wired up correctly.

**Comment by mevolu** [comment] 2023-06-08 11:05
@polendri Thank you!

I changed
`"search-change":e.findSharee` to `"search":e.findSharee` in the file `custom_apps/contacts/js/contacts-main.js`.
Now it's fixed for me too!

**Comment by hamza221** [comment] 2023-06-09 13:50
Duplicate of https://github.com/nextcloud/contacts/issues/3424

**Closed by hamza221** 2023-06-09 13:50 UTC
Labels: bug, feature: contacts, 0. Needs triage
