### ISSUE TITLE
Duplicate properties after adding new property

### ISSUE THREAD

**Issue by PopeRigby** [nextcloud/contacts#1475] opened 2020-02-22 00:09 UTC
### Steps to reproduce
Click "Add new property"

### Expected behaviour
Only one property is added

### Actual behaviour
Two properties are created

## Server configuration detail

**Operating system:** Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.14
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** LinuxServer Docker image

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - calendar: 2.0.1
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - cookbook: 0.5.7
 - dav: 1.14.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_antivirus: 2.2.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.5
 - metadata: 0.11.1
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocsms: 2.1.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.haddock.cc\/",
    "overwritehost": "cloud.haddock.cc",
    "overwriteprotocol": "https",
    "trusted_domains": [
        "cloud.haddock.cc"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587"
}
```
</details>

**Are you using external storage, if yes which one:** Local
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

**Operating system:** ArchLinux

**Comment by lp-unaape** [comment] 2020-02-23 06:52
We have the exact same problem since upgraded to 3.6.8

Steps to reproduce

Operating system: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64

Webserver: Apache/2.4.29 (Ubuntu) (fpm-fcgi)

Database: pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

PHP version: 7.2.24-0ubuntu0.18.04.3

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

Nextcloud version: 16.0.8 - 16.0.8.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.9.0
 - bruteforcesettings: 1.5.0
 - calendar: 1.7.2
 - circles: 0.17.10
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.8
 - dav: 1.9.2
 - deck: 0.6.6
 - external: 3.3.1
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_automatedtagging: 1.6.0
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.5
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - maps: 0.1.5
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 1.3.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - rainloop: 6.1.0
 - recommendations: 0.4.0
 - richdocuments: 3.5.2
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_diaspora: 1.0.5
 - socialsharing_email: 1.0.6
 - socialsharing_facebook: 1.0.5
 - socialsharing_twitter: 1.0.5
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - terms_of_service: 1.2.3
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - twofactor_u2f: 3.0.1
 - updatenotification: 1.6.0
 - user_external: 0.8.0
 - viewer: 1.2.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - jsloader
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "**************************"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "16.0.8.1",
    "overwrite.cli.url": "https:\/\/hermes.unaape.asso.fr\/",
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "*******",
                993,
                "ssl",
                "********r"
            ]
        }
    ],
    "default_language": "fr",
    "force_language": "fr",
    "default_locale": "fr_FR",
    "force_locale": "fr_FR",
    "defaultapp": "apporder",
    "app.mail.accounts.default": {
        "email": "***************",
        "imapHost": "************",
        "imapPort": 993,
        "imapUser": "*********************",
        "imapSslMode": "ssl",
        "smtpHost": "*******************,
        "smtpPort": 587,
        "smtpUser": "**************************************",
        "smtpSslMode": "tls"
    },
    "updater.release.channel": "production",
    "maintenance": false,
    "loglevel": 2,
    "app_install_overwrite": [
        "announcementcenter"
    ]
}


</details>

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

OC_User_IMAP

Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

The problem does not depend on the client browser (Win or Linux, Firefox or Chrome)

**Comment by fpetry** [comment] 2020-02-23 17:31
I can confirm this. Tried with "Notes" and "Anniversary".

Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
Nextcloud: 17.0.3
Contacts: 3.1.8

![Screenshot_20200223_182524](https://user-images.githubusercontent.com/4649876/75116610-82d8f480-566a-11ea-8721-fbab6a239700.png)
![Screenshot_20200223_182636](https://user-images.githubusercontent.com/4649876/75116612-83718b00-566a-11ea-9734-ab3fec421c72.png)
![Screenshot_20200223_182655](https://user-images.githubusercontent.com/4649876/75116613-840a2180-566a-11ea-87cd-4eef0e3d6ba5.png)

**Comment by skjnldsv** [comment] 2020-02-26 11:23
Duplicate of #1464, already fixed, I'll release this week. Sorry about that! :)

**Closed by skjnldsv** 2020-02-26 11:23 UTC
Labels: 0. Needs triage, bug
