### ISSUE TITLE
Searchbar Contacts result links don't work with Snap Nextcloud (there is no PrettyUrls available)

### ISSUE THREAD

**Issue by CMThF** [nextcloud/contacts#1952] opened 2020-11-27 09:22 UTC
### Describe the bug
Since the latest Snap Nextcloud update (20.0.1), the search bar for contacts returns links that require Pretty Urls to be set up, e.g.:
`https://<domain>/apps/contacts/All%20contacts/1cdab762-e882-428b-8365-b865247c0adc~contacts`

However, because Pretty Urls is not available on the snap version, these links break and return 404.
One can manually fix them by inserting `index.php`.

According to https://help.nextcloud.com/t/pretty-urls-remove-index-php-snap/32512 and https://github.com/nextcloud/nextcloud-snap/issues/412 there is still no way for PrettyUrls to work with the snap nextcloud version.

I assume this is because the search bar behavior has been changed in general. In earlier versions the search bar only searched in the current app/context, so only contacts are found when searching there. Now, everything is searched and the pop up windows shows links to the results... 

**To Reproduce**
1. Use SNAP version of nextcloud
2. Click on contacts
3. Use searchbar to look for a contact, click on the found contact in the opening window.

**Expected behavior**
Links from the searchbar work.

**Actual behavior**
Links from the searchbar return 404, because they assume that PrettyUrls are configured.

**Screenshots**
https://imgur.com/a/4ZvcxbO

### Server configuration
**Operating system**: Linux 5.4.0-52-generic 57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.7.32

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.1 - 20.0.1.1

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:** updated SNAP

**Nextcloud configuration:**
```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "log_rotate_size": 10485760
}

```
### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by skjnldsv** [comment] 2020-11-27 09:27
duplicate of https://github.com/nextcloud/contacts/issues/1852

**Closed by skjnldsv** 2020-11-27 09:27 UTC
Labels: 0. Needs triage, bug
