### ISSUE TITLE
Show system address book as ready-only address book in contacts

### ISSUE THREAD

**Issue by schiessle** [nextcloud/contacts#1474] opened 2020-02-21 10:49 UTC
In organizations it is quite common that you want to have a shared address book with the contact data of all your colleagues.

Today you can achieve this with a address book created within the contacts app and shared with all others. But this has some issues:

1. If you share it read-only someone has to be in charge to keep it up to date
2. If you share it read-write so that everyone can add their own contact data people have to maintain their information twice, once in "contacts" and once in the personal settings.
3.  If you share it read-write you risk that people delete contacts by accident, add contacts which doesn't belong to the address book, etc

All information from the personal settings are already written to a carddav system address book. So technically we already have everything we need in the back-end. The idea is to expose it to the contacts app for all users and via carddav in a read-only mode. This way:

1. Every time someone updates their personal settings or if they are updated in a central user management like LDAP the address book will be updated as well.
2. People don't have to maintain their information in multiple places
3. You don't risk that people delete contacts by accident or add personal contacts which doesn't belong to the address book.

Of course there should be a Admin switch to enable/disable this behavior. In most organizations this will be quite useful but of course a shared hoster for example doesn't want to present all users in a address book to all the other users.

**Comment by georgehrke** [comment] 2020-02-21 11:04
Duplicate of https://github.com/nextcloud/server/issues/693

**Closed** 2020-02-21 11:08 UTC
Labels: 0. Needs triage, enhancement
