### ISSUE TITLE
Birthday field asks for time of day

### ISSUE THREAD

**Issue by axelsimon** [nextcloud/contacts#884] opened 2019-01-25 16:30 UTC
### Describe the bug
When entering a birthday for a contact, Nextcloud contacts requests the time of day.

**To Reproduce**
1. Go to a contact
2. Add a birthday
3. Nextcloud contacts asks for a time of day, beyond the day + month + year.

**Expected behaviour**
The app should be happy with just day + month, year should be optional, time of day is a bit ridiculous and should not be requested or considered.

**Screenshots**
https://user-images.githubusercontent.com/5955972/50417447-44edff80-081e-11e9-8286-afda5a372cd5.png

### Server configuration
Can add if relevant, doesn't seem so right now.

**Comment by skjnldsv** [comment] 2019-01-25 16:34
Duplicate of #795 
:wink:

**Closed by skjnldsv** 2019-01-25 16:34 UTC
