### ISSUE TITLE
Adding Detailed Name: Presettings wrong filled

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/contacts#886] opened 2019-01-25 21:13 UTC
NC 15.0.2
Contacts 3.0.2

1. Two entries exist with FNs: "**FN1-1 FN1-2**" and "**FN2-1 FN2-2**"
2. Select first entry
2. Add attribute Detailed Name
3. Cut FN and paste into Detailed Name attribute fields
4. Select second entry
5. Add attribute Detailed Name
6. Values of first entry are preset in the fields

Screenshots:

![fn-1](https://user-images.githubusercontent.com/3857906/51773134-21a0c380-20ee-11e9-8411-3b75d281759a.JPG)

![fn-2](https://user-images.githubusercontent.com/3857906/51773139-26fe0e00-20ee-11e9-8631-be2c7bcf0ec1.JPG)

![fn-3](https://user-images.githubusercontent.com/3857906/51773147-2c5b5880-20ee-11e9-8c8b-5e643e9ab510.JPG)

Bug: Prefilled fields with former entry data:

![fn-4](https://user-images.githubusercontent.com/3857906/51773152-30877600-20ee-11e9-898b-4965de130b88.JPG)

**Comment by skjnldsv** [comment] 2019-01-25 22:45
Duplicate of #875

**Closed by skjnldsv** 2019-01-25 22:45 UTC
Labels: bug
