### ISSUE TITLE
Column for names too narrow 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/contacts#495] opened 2018-02-22 10:08 UTC
### Steps to reproduce
1. The display of the name column is to narrow - can only see half of the name, wheras the display of the individual is too large. 
2. This relation is independent of window size. Same in Windows Edge and Chrome. 

![image](https://user-images.githubusercontent.com/36486009/36532139-36917466-17c0-11e8-850a-353dd568fc3f.png)

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** nginx/1.13.8 (fpm-fcgi)

**Database:** mysql 10.2.13

**PHP version:** 7.1.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - audioplayer: 2.2.5
 - calendar: 1.6.0
 - caniupdate: 0.1.2
 - cms_pico: 0.9.7
 - contacts: 2.1.0
 - dav: 1.4.6
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - oauth2: 1.1.0
 - onlyoffice: 1.2.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - comments
 - encryption
 - federation
 - files_external
 - files_frommail
 - files_versions
 - files_videoplayer
 - nextcloud_announcements
 - notifications
 - ownpad
 - quota_warning
 - sharebymail
 - socialsharing_email
 - socialsharing_facebook
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "173.249.5.125",
        "nginx-server",
        "cloud.korskyrkan-intra.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/173.249.5.125",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "onlyoffice": {
        "DocumentServerUrl": "\/ds-vpath\/",
        "DocumentServerInternalUrl": "http:\/\/onlyoffice-document-server\/",
        "StorageUrl": "http:\/\/nginx-server\/"
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by skjnldsv** [comment] 2018-02-22 10:09
Duplicate of #453

**Closed by skjnldsv** 2018-02-22 10:09 UTC
Labels: duplicate

**Comment by Sr4l** [comment] 2018-02-22 17:46
Are you sure this is the same problem? I was Going to report the same issue as rollanders. I have very small  "name" column in Chrome (also Chromium, Linux and Windows) and Windows Edge. I can only read the first ~3 chars of every name. Firefox seems okay though.

![issue](https://user-images.githubusercontent.com/2060860/36554612-0fdecc0c-1800-11e8-8566-0e58e173ee83.png)

**Comment by skjnldsv** [comment] 2018-02-22 17:50
It depends on the windows width. As soon as the details get split into two columns, the list get shrunk. :)

**Comment by Sr4l** [comment] 2018-02-22 17:54
Nice one ;-). Nope. I am on fullscreen at 1920x1080 and the "contact details" consume more than 80% of the screen.

**Comment by skjnldsv** [comment] 2018-02-22 18:22
@Sr4l The new pr is supposed to fix this, But I'll provide a new grid system asap. It should be a lot better :)

**Comment by Sr4l** [comment] 2018-02-22 18:29
Good job. Sorry for stealing your time.

I applied PR #481 and its looking fine.

Thank you!

**Comment by rollanders** [comment] 2018-02-23 07:41
At window size 770-797 I see 2-3 letters in the contacts list column. At 798-840 I see no letter - just three points. The number of letters is then gradually increasing with increasing the window and I almost see them al at 1449. When increasing the window further the column shrinks again and only 2 letters and three points are visible.  This is Chrome. The same behaviour in Opera and Edge.  The Contacs app is not usable in the present form.

**Comment by Sr4l** [comment] 2018-02-23 07:59
@rollanders You are right. You could apply these changes now: https://github.com/nextcloud/contacts/pull/481/files to your nextcloud/apps/contacts files or you have to wait. skjnldsv is waiting for approval to merge the mentioned changes.

**Comment by rollanders** [comment] 2018-02-23 08:22
Confirm it works in Chrome.

**Comment by skjnldsv** [comment] 2018-02-23 08:23
> @skjnldsv Good job. Sorry for stealing your time.

Don't appologise :)
It's perfectly normal
