### ISSUE TITLE
Improve FN/Name fields display

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#307] opened 2017-08-28 00:51 UTC
**Currently**
1) When User selects 'detailed name', and perhaps also 'Nickname', name information appears in three separate areas of the screen, some of it is duplicated. Leaving the User confused as to what overrides what (does the name entered at the top override the name entered in 'detailed name'?)
2) There is no way of tailoring how a contact's display name should appear (important for both sorting, searching, and viewing/memory purposes)
3) There is no phonetic name field (important for users who have foreign contacts) (CardDAV X-PHONETIC-FIRST-NAME, X-PHONETIC-LAST-NAME)
4) There is no way of adding alias name fields (important in many countries where people have a) formal names, b) familiar names, c) maiden names, d) past names, e) alternative names written in a different script or language.
5) There is no 'Department' name (CardDAV: DEPARTMENT)

**Resolution:**
(See attachment below showing Zimbra's resolution)

1) List the basic name at the top of the screen (as at present).
2) Have a dropdown at the top of the screen for choosing which extra name elements to display (rather than cluttering the Users display with lots of unused fields, as at present).

_The basic list would be:_
Fullname, Organisation, Title
_The dropdown would offer:_
Detailed name (breaking down first/middle/last), Nickname, Prefix, Suffix, Alias, Role, Department, Display name

3) Include 'Display Name' as one of the options in the Name dropdown.
When user selects that, a new field will display, showing the current display name order for that contact. User can selection a dropdown next to it to change it from the default, options to include:
First Last; Last, First; First Middle Last; Organisation; First Last (Organisation); Last, First (Organisation); Nickname; Suffix First Last Prefix...

4 **Dealing with multiple alias and nicknames**
Alias should be stored in CardDAV with properties set as 'NAME, ALTID'
Alias and Nickname, once selected, should have an + next to them, as both can occur multiple times for the same contact, and both are permitted within vCard standards.

**Comment by olantrust** [comment] 2017-08-28 01:42
![nextcloudissue2-screenshot_20170827_235308](https://user-images.githubusercontent.com/627140/29756259-86cdf5ba-8b9a-11e7-966d-784d27ead59f.png)
![nextcloudissue-screenshot_20170827_235308](https://user-images.githubusercontent.com/627140/29756260-86d002f6-8b9a-11e7-9114-5b269263257f.png)

**Comment by skjnldsv** [comment] 2017-08-28 17:32
I don't mind the duplicate of the header since it's not exactly a duplicate. The header contains the summary of the whole FN fields. 

To be fair, I think you're right, but this is probably a pain to so few peoples that I'm not sure working on this is really such useful :)

**Comment by olantrust** [comment] 2017-08-29 10:43
Well we'll try and work on it and propose a more slimline fix.

Just to add that a lot of people could be using detailed name, and currently it takes up a lot of space and impedes smooth viewing, unnecessarily, as per images above.

**Comment by jancborchardt** [comment] 2017-08-30 12:57
While it is something to improve, let’s please not use Zimbra’s messy interface as any kind of benchmark. Google Contacts or Apple Contacts is way more widely used, and far better designed.

**Comment by skjnldsv** [comment] 2018-10-02 13:37
Closing since most of it is either a `wontfix` or have its own issue (phonetic for example)
The duplicate is not one since they're referring to FN and N fields. 

Regarding the ui we want to keep things simple. You can find software that are crazy complicated ad have every options, this won't be ours. We have to draw a line somewhere unfortunately :confused: 
Thanks a lot for your suggestions!!

**Closed by skjnldsv** 2018-10-02 13:37 UTC
Labels: design
