### ISSUE TITLE
"Custom" phone label from Android 9 not shown in NextCloud app

### ISSUE THREAD

**Issue by pss34** [nextcloud/contacts#799] opened 2018-12-28 13:16 UTC
### Steps to reproduce
1. Sync any contact w/ custom phone number label
2. Examine contact in browser app. There is no phone number for contact anymore, but it is present in backup from phone or from NC app.

### Expected behaviour
Custom label and phone number shown in browser app.

### Actual behaviour
No phone number and no custom label

### Server configuration

**Operating system**: 
sb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Web server:**
nginx 1.10.3-0ubuntu0.16.04.3

**Database:**
mariadb-server 10.0.36-0ubuntu0.16.04.1

**PHP version:**
php7.0 7.0.33-1+ubuntu16.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.0

**Contacts version:** (see Nextcloud apps page)
3.0.1

**Updated from an older Nextcloud or fresh install:**
Update

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0   
  - metadata: 0.8.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - phonetrack: 0.4.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

**Nextcloud configuration:**

{   
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.avalon.org.ua"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.avalon.org.ua",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "errorlog",
        "updater.release.channel": "stable",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
firefox 64.0+build3-0ubuntu0.18.10.1
**Operating system:**
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

**CardDAV-clients:**
DavDroid 2.0.7-gplay

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by skjnldsv** [comment] 2018-12-31 12:53
Hello @pss34 
Is this happening on every contacts? Only one? Could you share the vcard here as well please?

Also, I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by pss34** [comment] 2019-01-08 14:31
Hello!
Yes, it concerns every contact with "custom" field.

Test VCard attached.
[testvcard-from-nc.txt](https://github.com/nextcloud/contacts/files/2737062/testvcard-from-nc.txt)

Console log:


GEThttps://nc.avalon.org.ua/apps/contacts/All%20contacts/03e17167-2d20-430e-b276-52182d6d4265~contacts
[HTTP/2.0 200 OK 455ms]
GEThttps://nc.avalon.org.ua/core/vendor/select2/select2.css?v=61b92900
[HTTP/2.0 200 OK 84ms]
GEThttps://nc.avalon.org.ua/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=61b92900
[HTTP/2.0 200 OK 115ms]
GEThttps://nc.avalon.org.ua/css/core/7838-cde4-jquery-ui-fixes.css?v=d41d8cd98f00b204e9800998ecf8427e?v=61b92900
[HTTP/2.0 200 OK 167ms]
GEThttps://nc.avalon.org.ua/css/core/7838-cde4-server.css?v=d41d8cd98f00b204e9800998ecf8427e?v=61b92900
[HTTP/2.0 200 OK 371ms]
GEThttps://nc.avalon.org.ua/css/core/7838-cde4-css-variables.css?v=d41d8cd98f00b204e9800998ecf8427e?v=61b92900
[HTTP/2.0 200 OK 535ms]
GEThttps://nc.avalon.org.ua/apps/files_versions/css/versions.css?v=4fda350b
[HTTP/2.0 200 OK 109ms]
GEThttps://nc.avalon.org.ua/apps/files_pdfviewer/css/style.css?v=1bf6e69c
[HTTP/2.0 200 OK 109ms]
GEThttps://nc.avalon.org.ua/css/firstrunwizard/0d6d-cde4-firstrunwizard.css?v=d41d8cd98f00b204e9800998ecf8427e?v=0d6d4ea2
[HTTP/2.0 200 OK 536ms]
GEThttps://nc.avalon.org.ua/css/notifications/70e2-cde4-styles.css?v=d41d8cd98f00b204e9800998ecf8427e?v=70e2b24f
[HTTP/2.0 200 OK 415ms]
GEThttps://nc.avalon.org.ua/apps/sociallogin/css/style.css?v=406d3fd3
[HTTP/2.0 200 OK 94ms]
GEThttps://nc.avalon.org.ua/css/core/7838-cde4-jquery.ocdialog.css?v=d41d8cd98f00b204e9800998ecf8427e?v=61b92900
[HTTP/2.0 200 OK 518ms]
GEThttps://nc.avalon.org.ua/css/core/7838-cde4-results.css?v=d41d8cd98f00b204e9800998ecf8427e?v=61b92900
[HTTP/2.0 200 OK 518ms]
GEThttps://nc.avalon.org.ua/css/contacts/3d4b-cde4-contacts.css?v=d41d8cd98f00b204e9800998ecf8427e?v=3d4b11f6
[HTTP/2.0 200 OK 541ms]
GEThttps://nc.avalon.org.ua/css/icons/icons-vars.css?v=1546514867
[HTTP/2.0 200 OK 615ms]
GEThttps://nc.avalon.org.ua/core/vendor/core.js?v=61b92900
[HTTP/2.0 200 OK 419ms]
GEThttps://nc.avalon.org.ua/js/core/merged-template-prepend.js?v=61b92900
[HTTP/2.0 200 OK 644ms]
GEThttps://nc.avalon.org.ua/core/search/js/search.js?v=61b92900
[HTTP/2.0 200 OK 147ms]
GEThttps://nc.avalon.org.ua/core/js/backgroundjobs.js?v=61b92900
[HTTP/2.0 200 OK 147ms]
GEThttps://nc.avalon.org.ua/apps/encryption/js/encryption.js?v=61b92900
[HTTP/2.0 200 OK 132ms]
GEThttps://nc.avalon.org.ua/apps/files_pdfviewer/js/previewplugin.js?v=61b92900
[HTTP/2.0 200 OK 130ms]
GEThttps://nc.avalon.org.ua/js/core/merged-share-backend.js?v=61b92900
[HTTP/2.0 200 OK 680ms]
GEThttps://nc.avalon.org.ua/apps/firstrunwizard/js/jquery.colorbox.js?v=61b92900
[HTTP/2.0 200 OK 129ms]
GEThttps://nc.avalon.org.ua/apps/firstrunwizard/js/firstrunwizard.js?v=61b92900
[HTTP/2.0 200 OK 146ms]
GEThttps://nc.avalon.org.ua/apps/notifications/js/notifications.js?v=61b92900
[HTTP/2.0 200 OK 277ms]
GEThttps://nc.avalon.org.ua/core/search/js/searchprovider.js?v=61b92900
[HTTP/2.0 200 OK 160ms]
GEThttps://nc.avalon.org.ua/core/js/jquery-ui-fixes.js?v=61b92900
[HTTP/2.0 200 OK 160ms]
GEThttps://nc.avalon.org.ua/core/js/files/fileinfo.js?v=61b92900
[HTTP/2.0 200 OK 159ms]
GEThttps://nc.avalon.org.ua/core/js/files/client.js?v=61b92900
[HTTP/2.0 200 OK 170ms]
GEThttps://nc.avalon.org.ua/core/js/contactsmenu.js?v=61b92900
[HTTP/2.0 200 OK 166ms]
GEThttps://nc.avalon.org.ua/core/js/contactsmenu_templates.js?v=61b92900
[HTTP/2.0 200 OK 165ms]
GEThttps://nc.avalon.org.ua/apps/contacts/js/contacts.js?v=61b92900
[HTTP/2.0 200 OK 864ms]
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
GEThttps://nc.avalon.org.ua/apps/accessibility/js/accessibility?v=0
[HTTP/2.0 200 OK 100ms]
GEThttps://nc.avalon.org.ua/apps/files/img/app.svg?v=61b92900
[HTTP/2.0 200 OK 38ms]
GEThttps://nc.avalon.org.ua/apps/activity/img/activity.svg?v=61b92900
[HTTP/2.0 200 OK 37ms]
GEThttps://nc.avalon.org.ua/apps/contacts/img/app.svg?v=61b92900
[HTTP/2.0 200 OK 40ms]
GEThttps://nc.avalon.org.ua/apps/calendar/img/calendar.svg?v=61b92900
[HTTP/2.0 200 OK 41ms]
GEThttps://nc.avalon.org.ua/apps/phonetrack/img/app.svg?v=61b92900
[HTTP/2.0 200 OK 42ms]
GEThttps://nc.avalon.org.ua/apps/notes/img/notes.svg?v=61b92900
[HTTP/2.0 200 OK 41ms]
GEThttps://nc.avalon.org.ua/apps/tasks/img/tasks.svg?v=61b92900
[HTTP/2.0 200 OK 71ms]
GEThttps://nc.avalon.org.ua/settings/img/admin.svg?v=61b92900
[HTTP/2.0 200 OK 70ms]
GEThttps://nc.avalon.org.ua/settings/img/apps.svg?v=61b92900
[HTTP/2.0 200 OK 69ms]
GEThttps://nc.avalon.org.ua/settings/img/users.svg?v=61b92900
[HTTP/2.0 200 OK 67ms]
GEThttps://nc.avalon.org.ua/apps/firstrunwizard/img/info.svg?v=61b92900
[HTTP/2.0 200 OK 67ms]
GEThttps://nc.avalon.org.ua/settings/img/help.svg?v=61b92900
[HTTP/2.0 200 OK 69ms]
GEThttps://nc.avalon.org.ua/core/img/actions/logout.svg?v=61b92900
[HTTP/2.0 200 OK 71ms]
GEThttps://nc.avalon.org.ua/core/img/logo/logo.svg?v=1
[HTTP/2.0 200 OK 71ms]
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Bold.woff2
[HTTP/2.0 302 Found 138ms]
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Regular.woff2
[HTTP/2.0 302 Found 108ms]
New search handler registered search.js:67:4
GEThttps://nc.avalon.org.ua/apps/spreed/img/app.svg?v=61b92900
[HTTP/2.0 200 OK 39ms]
GEThttps://nc.avalon.org.ua/avatar/pseudo/32?v=0
[HTTP/2.0 201 Created 107ms]
GEThttps://nc.avalon.org.ua/apps/notifications/img/notifications.svg
[HTTP/2.0 200 OK 38ms]
XHRGEThttps://nc.avalon.org.ua/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/2.0 200 OK 159ms]
XHRPROPFINDhttps://nc.avalon.org.ua/remote.php/dav/
[HTTP/2.0 207 Multi-Status 91ms]
XHRGEThttps://nc.avalon.org.ua/cron.php
[HTTP/2.0 200 OK 112ms]
XHRGEThttps://nc.avalon.org.ua/apps/encryption/ajax/getStatus
[HTTP/2.0 200 OK 94ms]
GEThttps://nc.avalon.org.ua/apps/files/
[HTTP/2.0 200 OK 288ms]
GEThttps://nc.avalon.org.ua/apps/files/
[HTTP/2.0 200 OK 322ms]
GEThttps://nc.avalon.org.ua/apps/notifications/img/notifications.svg
[HTTP/2.0 200 OK 39ms]
XHRPROPFINDhttps://nc.avalon.org.ua/remote.php/dav/principals/users/pseudo/
[HTTP/2.0 207 Multi-Status 76ms]
Connected to dav! 
Object { rootUrl: "https://nc.avalon.org.ua/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
contacts.js:84:29413
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Regular.ttf
[HTTP/2.0 200 OK 171ms]
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Bold.ttf
[HTTP/2.0 200 OK 204ms]
XHRPROPFINDhttps://nc.avalon.org.ua/remote.php/dav/addressbooks/users/pseudo/
[HTTP/2.0 207 Multi-Status 96ms]
GEThttps://nc.avalon.org.ua/apps/contacts/img/favicon-touch.png
[HTTP/2.0 200 OK 49ms]
GEThttps://nc.avalon.org.ua/apps/contacts/img/favicon.ico
[HTTP/2.0 200 OK 50ms]
Помилка карти джерела: request failed with status 401
URL джерела: https://nc.avalon.org.ua/apps/contacts/js/contacts.js?v=61b92900
URL карти джерела: contacts.js.map[Докладніше]
XHRREPORThttps://nc.avalon.org.ua/remote.php/dav/addressbooks/users/pseudo/contacts/
[HTTP/2.0 207 Multi-Status 294ms]
XHRPROPFINDhttps://nc.avalon.org.ua/remote.php/dav/addressbooks/users/pseudo/contacts/03e17167-2d20-430e-b276-52182d6d4265.vcf
[HTTP/2.0 207 Multi-Status 87ms]
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Regular-latin-ext.woff2
[HTTP/2.0 302 Found 88ms]
GEThttps://nc.avalon.org.ua/apps/files/
[HTTP/2.0 200 OK 211ms]
GEThttps://nc.avalon.org.ua/core/fonts/Nunito-Regular.ttf
[HTTP/2.0 200 OK 0ms]

**Comment by skjnldsv** [comment] 2019-03-02 10:41
Looking at your contact, this is a duplicate of https://github.com/nextcloud/contacts/issues/42

**Closed by skjnldsv** 2019-03-02 10:41 UTC
Labels: bug, need info
