### ISSUE TITLE
Contact groups not recognized in macOS

### ISSUE THREAD

**Issue by digitall-it** [nextcloud/contacts#577] opened 2018-07-15 07:23 UTC
### Steps to reproduce
1. Create a contact in web interface 
2. Create a group in web interface
3. Assign group as a tag in web interface

### Expected behaviour
Contacts should appear in group in macOS Addressbook

### Actual behaviour
Groups are not recognized.

## Server configuration detail

**Operating system:** Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.5.56

**PHP version:** 7.0.30
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, lua, exif, mcrypt, memcached, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.4 - 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** official website source code archive

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - calendar: 1.6.1
 - camerarawpreviews: 0.5.3
 - checksum: 0.4.0
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - deck: 0.4.0
 - defaultlinkopen: 1.0.0
 - drawio: 0.8.9
 - external: 3.0.3
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - news: 12.0.4
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - polls: 0.8.1
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - sentry: 2.0.1
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.2.4
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_saml: 1.5.0
 - workflowengine: 1.3.0
Disabled:
 - admin_notifications
 - announcementcenter
 - audioplayer
 - bookmarks
 - bruteforcesettings
 - cms_pico
 - encryption
 - files_external
 - keeporsweep
 - mindmaps
 - ocsms
 - quota_warning
 - ransomware_protection
 - richdocuments
 - spreedme
 - unsplash
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.digitall.it"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/cloud.digitall.it",
    "dbtype": "mysql",
    "version": "13.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari v.11.1.2 (13605.3.8)

**Operating system:** macOS High Sierra v.10.13.6 (17G65)

**CardDAV-clients:** ios 11-latest, macOS

#### Web server error log
```
No error reported
```

#### Nextcloud log (data/nextcloud.log)
```
No error reported
```

#### Browser log
```
No error reported
```

**Comment by dphi** [comment] 2018-08-01 20:30
Duplicate of #213 .

**Closed** 2018-08-01 20:34 UTC
