### ISSUE TITLE
Sort order of the contact groups

### ISSUE THREAD

**Issue by rprpx** [nextcloud/contacts#1212] opened 2019-08-12 14:15 UTC
**Is your feature request related to a problem? Please describe.**
The Contact Groups appear to be sorted only by the number of people in the group. The initial commenter of #344 mentioned that he would find this type of sorting ideal, and this apparently was implemented, however I imagine it isn't ideal for everyone.  For example, I have no reason to care about the number of people in a group.  Alphabetical ordering would be much preferable to me. 

**Describe the solution you'd like**
May an option be implemented so that ordering may be based on Count OR Group Name, depending on user preference?  This could be implemented in the "Settings" section at the bottom of the left column along with the other settings there.

Thank you.

**Comment by skjnldsv** [comment] 2019-08-12 14:57
Hey :)
Duplicate of https://github.com/nextcloud/contacts/issues/522

**Closed by skjnldsv** 2019-08-12 14:57 UTC
Labels: 0. Needs triage, enhancement
