### ISSUE TITLE
Contacts list scroll broken on mobile with contacts v4

### ISSUE THREAD

**Issue by Octopus2** [nextcloud/contacts#2289] opened 2021-06-18 15:16 UTC
### Describe the bug
Contacts are not displayed in mobile view, only on Desktop
......

**To Reproduce**
I have over 700 contacts. These are displayed on the desktop without any problems with the current beta version. But no contacts are displayed on the smartphone.

This problem did not occur with version 3.x.

See screenshots....
![Screenshot_20210618-093358_Chrome](https://user-images.githubusercontent.com/4060419/122582771-d1c54d00-d058-11eb-9cb2-bf10af59f51a.jpg)
![InkedScreenshot ](https://user-images.githubusercontent.com/4060419/122582775-d25de380-d058-11eb-99ed-666e6f4ab819.jpg)

### Server configuration

**Nextcloud version:** 21.0.2

**Contacts version:** 4.0.0.-Beta 2 (Circle is NOT installed)

**Updated from an older Nextcloud or fresh install:** updated from NC 15 an so on....

### Client configuration
**Browser:**
DESKTOP: Windows 10+ Firefox 89.0.1 
MOBILE: Android+Samsung Browser (V.14.01) or Chrome (same same)

#### Browser log
No Browser-Log on my Android-Device, sorry

**Comment by skjnldsv** [comment] 2021-06-21 07:09
I guess fixed in incoming beta 3

**Comment by skjnldsv** [comment] 2021-06-21 07:37
Released, please test and try again :)

**Comment by Octopus2** [comment] 2021-06-21 10:18
@skjnldsv Thanks. Contacts are now (with beta 3) displayed on the smartphone again, but only the first 30 in both the Samsung browser and Chrome. After that, only a very long white area is displayed

**Comment by Octopus2** [comment] 2021-07-07 10:40
Still valid with the official V4 and NC 22.

**Comment by szaimen** [comment] 2021-07-08 01:15
I can reproduce that also on Desktop if you enable mobile view via the console.
It loads the first 30 contacts and stops loading when you scroll down further. So it seems like something in this logic dooesn't work. Maybe a bug with a used library?

**Comment by skjnldsv** [comment] 2021-07-08 09:41
It was supposed to be fixed with `nextcloud/vue@^4.0.3`

**Comment by skjnldsv** [comment] 2021-07-08 09:41
A css fix to properly handle the scrollable container is most likely needed

**Comment by szaimen** [comment] 2021-07-08 09:53
Maybe this came back due to the resizable columns PR?

**Comment by Octopus2** [comment] 2021-07-29 12:08
Still broken with 4.0.1 and NC 22.1.0 RC 1
Perhaps revert the resizable columns PR? Sorry, having no access to the data is in my world a release blocker...

**Closed** 2021-07-30 07:47 UTC
Labels: 1. to develop, bug, feature: contacts, high, regression
