### ISSUE TITLE
[3.0.3] A vcf-file which contains a death date ist not correctly imported

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#912] opened 2019-02-03 18:09 UTC
## Expected behavior
If you import a vcf-file which contains a death date field, it should be correctly imported and displayed in the Contacts app.

## Current behavior
If you import a vcf-file which contains a death date field, it is imported but the death date field is not displayed anymore. Additionally it is not possible to add that field because it isn't shown in the available fields list. This is how the exported contact record looks like:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:c339755f-43fe-47d6-a47c-519be4c4a716
FN:Donald Death-NC
ADR;TYPE=HOME:;;;;;;
EMAIL;TYPE=HOME:
TEL;TYPE="HOME,VOICE":
BDAY:19600101T000017
CATEGORIES:Privat
DEATHDATE:19900615T000000
END:VCARD
```

### Steps to reproduce
1. Open the Contacts app.
2. Create a new contact and add e.g. a birth and death date.
3. Export this contact to a vcf file.
4. Delete the newly created contact in the Contacts app.
5. Re-import the previously saved vcf-file.
-> Check the availability of the death date field.

#### Server Configuration
OS: Linux 3.16.60
Web server: Apache2 2.4.37
Database: MariaDB 10.2.19
PHP version: 7.2.14
Nextcloud version: 15.0.2
Contacts app version: 3.0.3

#### Client Configuration
Browser: Mozilla Firefox 65.0
Operating system: Windows 10

**Comment by skjnldsv** [comment] 2019-02-04 09:04
This is a duplicate of #813

**Closed by skjnldsv** 2019-02-04 09:04 UTC
Labels: bug
