### ISSUE TITLE
itemN.* not Imported into NC Via Web; "," Escaped in Notes; ":" in Address Throws Errors

### ISSUE THREAD

**Issue by DiagonalArg** [nextcloud/contacts#3736] opened 2023-12-10 03:09 UTC
### Describe the bug

Export a test vCard from Google Contacts (iOS format).  Import to Nextcloud Contacts via web interface.  See that none of the itemN.* attributes are imported and that some characters in Notes are escaped.

### Steps to reproduce

Import this card:

BEGIN:VCARD
VERSION:3.0
FN:J & N Test
N:Test;J & N;;;
item1.TEL:+1.555 222 4444
item1.X-ABLabel:J Cell
item2.TEL:+1.555 444 8888
item2.X-ABLabel:J Cell Pix
item3.TEL:+1.888 555 2222
item3.X-ABLabel:N Cell
item4.TEL:+1.999 555 9999
item4.X-ABLabel:Old Cell
NOTE:A\\\, b. 2023.
CATEGORIES:myContacts
END:VCARD

[J&N.Test.txt](https://github.com/nextcloud/contacts/files/13626433/J.N.Test.txt)

### Expected behavior

I should see the phone numbers with their labels.  I should also see notes without characters like "," being escaped.

### Actual behavior

Get this results:

![image](https://github.com/nextcloud/contacts/assets/5190243/25ba5056-b9da-41d9-be28-a32c2130a063)

### Contact version

5.4.2

### Operating system

CentOS 7.8.2003

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Nextcloud version 27.14

**Comment by DiagonalArg** [comment] 2023-12-10 03:38
It's also failing to import (at least some) addresses.  Another vcard, which I imported to Nextcloud.  See the result, below that.

BEGIN:VCARD
VERSION:3.0
FN:R M Dick
N:Dick;R M;;;
item1.ADR:;121 South Estes Dr.\, suite 104;Haven Medical Center;Chapel Hill
 ;;27514;US;Haven Medical Center\n121 South Estes Dr.\, suite 104\, Chapel 
 Hill\, 27514\nUS
item1.X-ABLabel:
CATEGORIES:myContacts
END:VCARD

![image](https://github.com/nextcloud/contacts/assets/5190243/c8487f75-5468-42df-902b-e61b7215ea62)

**Comment by DiagonalArg** [comment] 2023-12-10 05:27
Finally, when there is a ":" in the address, import to NC throws an error.

BEGIN:VCARD
VERSION:3.0
FN:R M D
N:D;R M;;;
item1.ADR:;;Dorchester Village\: CenterPoint;;NC;;US;Dorchester Village\: C
 enterPoint\nNC\nUS
item1.X-ABLabel:
CATEGORIES:myContacts
END:VCARD

[RMD.txt](https://github.com/nextcloud/contacts/files/13626622/RMD.txt)

**Comment by DiagonalArg** [comment] 2023-12-13 12:15
On upgrade to 5.5.0, I can now see the itemN.X-ABLabel's for phone numbers and addresses, but many addresses are showing up like this: 

";;1025 Keeler Ave;Berkeley;CA;94708-140 ..."

**Comment by hamza221** [comment] 2023-12-19 15:08
duplicate of #3721

**Closed by hamza221** 2023-12-19 15:08 UTC
Labels: bug, feature: contacts, 0. Needs triage

**Comment by hamza221** [comment] 2023-12-19 17:04
Fixes in #3644

**Comment by DiagonalArg** [comment] 2024-01-04 15:04
[Address issue](https://github.com/nextcloud/contacts/issues/3736#issuecomment-1853809369) not repaired in 5.5.1
