### ISSUE TITLE
Phone numbers are not displayed correct in iOS

### ISSUE THREAD

**Issue by Luto73** [nextcloud/contacts#1434] opened 2020-01-22 22:16 UTC
### Describe the bug
When I create a new contact via the browser and set a work phone number (German localisation "Arbeit") iOS recognizes this as ""WORK" instead of "Arbeit". The same is with numbers declared as "Fax Arbeit": they are displayd as ""WORK" in iOS. If I change it from "Fax Arbeit" to "Fax" it is correctly displayd as "Fax Arbeit".

**To Reproduce**
Create a new contact via the web interface.
Sync with iOS via WebDAV

**Expected behavior**
The numbers should be displayed with the correct denomination: "Arbeit" -> "Arbeit", "Fax Arbeit" -> "Fax Arbeit"

**Actual behavior**
The numbers are denominated in a wrong way: "Arbeit" -> ""WORK", "Fax Arbeit" -> ""WORK"

### Server configuration
**Operating system:** Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 7.2.24-0ubuntu0.18.04.2

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.7 - 16.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - bruteforcesettings: 1.5.0
 - calendar: 1.7.2
 - camerarawpreviews: 0.7.3
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.6
 - dav: 1.9.2
 - deck: 0.6.6
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_fulltextsearch: 1.3.6
 - files_fulltextsearch_tesseract: 1.3.2
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - fulltextsearch: 1.3.6
 - fulltextsearch_elasticsearch: 1.3.6
 - gallery: 18.3.0
 - groupfolders: 4.1.5
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.1.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - onlyoffice: 4.1.1
 - password_policy: 1.6.0
 - polls: 1.0.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - registration: 0.4.7
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - viewer: 1.2.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "16.0.7.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "default_language": "de",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "production"
}
```
</details>

**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by skjnldsv** [comment] 2020-02-03 06:20
Duplicate of #942 & #1107

**Closed by skjnldsv** 2020-02-03 06:20 UTC
Labels: 0. Needs triage, bug
