### ISSUE TITLE
Contact thumbnails / pictures aren't loading

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/contacts#543] opened 2018-04-12 21:02 UTC
### Steps to reproduce
Open the Contacts App

### Expected behaviour
The contacts load, including the thumbnails pictures

### Actual behaviour
The thumbnails aren't shown.
Only when I open a contact, the thumbnail is loaded.
Waiting doesn't help

## Server configuration detail

**Operating system:** Linux 3.10.0-714.10.2.lve1.4.75.el7.x86_64 #1 SMP Fri Nov 3 04:25:16 EDT 2017 x86_64

**Webserver:** Apache (litespeed)

**Database:** mysql 10.1.32

**PHP version:** 7.1.15
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, litespeed, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, redis, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.4.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - contacts: 2.1.3
 - dav: 1.4.6
 - deck: 0.3.1
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - comments
 - federation
 - files_external
 - firstrunwizard
 - mindmaps
 - systemtags
 - user_external
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "arnomuhren.hostiso.host"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/arnomuhren.hostiso.host",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "integrity.check.disabled": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using encryption:** yes
## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36

**Operating system:** 
Elementary OS 0.4.1 Loki

**Comment by skjnldsv** [comment] 2018-04-12 22:57
Duplicate of #477

**Closed** 2018-04-12 22:57 UTC
