### ISSUE TITLE
broken contacts could not be fixed in the app by clicking the above right icon...

### ISSUE THREAD

**Issue by cpu2910** [nextcloud/contacts#1313] opened 2019-10-23 19:00 UTC
### Describe the bug
On several contacts there was a hint in the above right corner:This contact was broken and received a fix. Please review the content and click here to save it.

By doing this most of the contacts are fixed.

But 5 contacts couldn't be fixed this way. After clicking the 'arrow up' a rotating circle appears and stays there didn't stop to rotate...

**To Reproduce**
1. Logon to Nextcloud
2. Click on 'Contacts'
3. Select a contact and clickt the 'arrow up'
4. rotating circle appears for ever ...

**Expected behavior**
After clicking the arrow, I see a rotating circle for a short time, then it disappears and the contact ist saved.

**Screenshots**

### Server configuration

**Operating system**: Ubuntu Server 18.04.3 LTS

**Web server:** Apache 2.4.29

**Database:** MariaDB 10.1.41

**PHP version:** 7.2.19

**Nextcloud version: 16.0.5

**Contacts version: 3.1.6

**Updated from an older Nextcloud or fresh install:Updated

**Signing status:**
Don't know what to put here...
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_trashbin
  - files_versions
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.111",
            "cpunke.de",
            "ubuntu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cpunke.de\/owncloud",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "log_rotate_size": 104857600,
        "theme": "",
        "maintenance": false,
        "filesystem_check_changes": 1,
        "trashbin_retention_obligation": "7,8",
        "versions_retention_obligation": "7,8",
        "appstore.experimental.enabled": false,
        "default_language": "de",
        "defaultapp": "",
        "updatechecker": false,
        "enable_previews": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

### Client configuration
**Browser: Firefox 69.0.3 (64-bit)**

**Operating system: Linux Mint 19.2 Tina**

**CardDAV-clients: Android DAVx5**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
nextcloud.log is empty

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.


Insert your browser log here, this could for example include:

a) Console Log:
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
New search handler registered search.js:67:12
Connected to dav! 
Object { rootUrl: "https://cpunke.de/owncloud/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], publicCalendarHome: {…}, addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
Contacts.vue:299
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 13 globals.js:30:10
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 4 globals.js:30:10
The following contact needed a correction that failed: duplicate types 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:38:14
Locale used de PropertyDateTime.vue:171
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    toICALString ical.js:3123
    fix duplicateTypes.js:47
    fix duplicateTypes.js:46
    Sn validate.js:36
    Sn validate.js:31
    updateLocalContact ContactDetails.vue:580
    e ContactDetails.vue:494
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
duplicateTypes.js:60:11
The following contact needed a correction that failed: duplicate types 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:38:14
The following contact has been repaired: invalid REV 
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false, dav: {…} }
validate.js:42:14
Locale used de PropertyDateTime.vue:171
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    toICALString ical.js:3123
    fix duplicateTypes.js:47
    fix duplicateTypes.js:46
    Sn validate.js:36
    Sn validate.js:31
    t contacts.js:326
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    ln contacts.js:1022
    a contacts.js:1022
    fn contacts.js:1022
    fn contacts.js:1022
    updateContact contacts.js:280
    h vuex.esm.js:732
    dispatch vuex.esm.js:437
    dispatch vuex.esm.js:331
    t ContactDetails.vue:433
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
    qn contacts.js:1129
    qn contacts.js:1129
    updateContact ContactDetails.vue:426
    VueJS 3
duplicateTypes.js:60:11
The following contact needed a correction that failed: duplicate types 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:38:14
TypeError: "t.replace is not a function"
    _rfc6868Unescape ical.js:1657
    property ical.js:1493
    component ical.js:1444
    r ical.js:1406
    t contacts.js:333
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    ln contacts.js:1022
    a contacts.js:1022
    fn contacts.js:1022
    fn contacts.js:1022
    updateContact contacts.js:280
    h vuex.esm.js:732
    dispatch vuex.esm.js:437
    dispatch vuex.esm.js:331
    t ContactDetails.vue:433
    u ncvuecomponents.js:298
    _invoke ncvuecomponents.js:298
    e ncvuecomponents.js:298
    Wn contacts.js:1129
    a contacts.js:1129
    qn contacts.js:1129
    qn contacts.js:1129
    updateContact ContactDetails.vue:426
    VueJS 3
b) The network log:
see screenshot1.jpg + screenshot2.jpg
![screenshot1](https://user-images.githubusercontent.com/30260653/67425376-2be9e280-f5d8-11e9-9200-bb4d9a8c1165.jpg)
![screenshot2](https://user-images.githubusercontent.com/30260653/67425393-30160000-f5d8-11e9-87b6-825a8b20c957.jpg)

**Comment by skjnldsv** [comment] 2019-10-23 20:50
DUplicate of #1306

**Comment by skjnldsv** [comment] 2019-10-23 20:52
Ah, I'm an idiot! Sorry :)
I misread and confused you with another github user I was in contact with!

**Closed** 2020-01-06 11:24 UTC
Labels: 0. Needs triage, bug

**Comment by sutidor** [comment] 2020-10-09 09:46
contacts 3.4.0 release solved this for me
