### ISSUE TITLE
JSON encoding errors of l10n/zh_CN.json

### ISSUE THREAD

**Issue by guoyunhe** [nextcloud/contacts#168] opened 2017-03-15 16:20 UTC
### Steps to reproduce
1. Install and enable latest contacts app in Nextcloud
2. Switch to Simple Chinese (zh_CN).
2. Go to admin logging.
3. Look for JSON errors.

### Expected behaviour
Here should be no error messages about JSON loading.

### Actual behaviour
Get a lot of JSON errors:

```
Failed to load /srv/www/htdocs/nextcloud/apps/contacts/l10n/zh_CN.json - json error code: 3
```

I downloaded contacts latest release from Github and tested JSON encoding with `enca` tool.

```shell
> cd contacts/l10n
> enca zh_CN.json
Universal transformation format 8 bits; UTF-8
  Surrounded by/intermixed with non-text data
> enca sk_SK.json
Universal transformation format 8 bits; UTF-8
> enca ar.json
Universal transformation format 8 bits; UTF-8
```

You can see, only `zh_CN.json` has the **Surrounded by/intermixed with non-text data** information. So here is something wrong with the zh_CN.json file encoding.

**Comment by guoyunhe** [comment] 2017-03-15 16:26
I found in git master, the `enca` test result of `zh_CN.json` file is correct. But the problem is still in 1.5.3 version.

Hope next release will solve the problem.

**Comment by skjnldsv** [comment] 2017-03-17 04:34
I think the json are generated by transifex.

**Comment by irgendwie** [comment] 2017-03-20 15:35
@guoyunhe We won't change the old release, but the next version will contain the fix for this problem.
I would suggest for the time being you replace the file manually with the one from the master branch.

**Closed by irgendwie** 2017-03-20 15:35 UTC
Labels: invalid

**Comment by maddie** [comment] 2017-06-09 02:27
The snap package with version number 11.0.3snap4 also have this problem, and it's impossible to manually change the file since files within snap is immutable..

What should I do?

**Comment by guoyunhe** [comment] 2017-07-13 22:13
I have this problem again on Nextcloud version 12.0, the error message is the same:

Failed to load /srv/www/htdocs/nextcloud/apps/contacts/l10n/zh_CN.json - json error code: 3

If Transifex keep exporting JSON with errors, it would be better to add some automatic tests before each release. Otherwise this kind of problem will never disappear.

**Comment by kdaye** [comment] 2017-08-13 12:02
same error , Nextcloud version 12.0 Docker officeal image
```
l10n | Failed to load /var/www/html/custom_apps/contacts/l10n/zh_CN.json - json error code: 3
-- | --
```
so how to fix it ? replace the file manually with the one from the master branch will be fix it?

**Comment by catscarlet** [comment] 2017-11-06 06:02
I'm still using 1.5.3 because 2.0+ is too broken.

The problem is in the zh_CN.json, about line 39.

```
"Only VCard version 4.0 (RFC6350) or version 3.0 (RFC2426) are supported." : "仅支持 VCard 4.0 版 (RFC6350) 或者 3.0 版 (RFC2426) 。",
```

You can see there is a unknown char. Just delete that char and everything will be fine.

**Comment by catscarlet** [comment] 2017-11-06 06:02
I'm still using 1.5.3 because 2.0+ is too broken.

The problem is in the zh_CN.json, about line 39.

```
"Only VCard version 4.0 (RFC6350) or version 3.0 (RFC2426) are supported." : "仅支持 VCard 4.0 版 (RFC6350) 或者 3.0 版 (RFC2426) 。",
```

You can see there is a unknown char. Just delete that char and everything will be fine.

**Comment by irgendwie** [comment] 2017-11-06 08:13
@MorrisJobke Can we do something, to make sure that translations at least don't contain broken character?

**Comment by MorrisJobke** [comment] 2017-11-06 08:23
@nickvergessen Had something in place AFK. Any idea?

**Comment by nickvergessen** [comment] 2017-11-10 14:59
For the empty box character? Not really. I manually removed it in transifex last time.

**Comment by nickvergessen** [comment] 2017-11-15 10:25
Ah yeah I just remembered, we have a script to detect this:
https://github.com/nextcloud/server/blob/master/build/translation-checker.php

But we can't automatically fix it.
But when you find the error, you can simply fix it on transifex
