### ISSUE TITLE
Add the possibility to delete duplicated contacts

### ISSUE THREAD

**Issue by pipolakus38** [nextcloud/contacts#2757] opened 2022-05-24 11:44 UTC
### Is your feature request related to a problem? Please describe.

I imported my contacts twice.
Each contact is duplicated.
I'm not able to delete the duplicated ones.

### Describe the solution you'd like

One option or button to show the duplicated contacts and the possibility to delete each one by one or to select all duplicated, then being able to delete them. 

### Additional context

Thanks a lot and good luck  :smile

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-06-02 01:32
How do you expect that something would be considered to be duplicate? Merely one field that is identical? That would cause families that share addresses to be duplicate, so that is not useful. Specifically identical names? I know of many people whose names are identical, even their middle-names.

Literally the sole decent solution that I am able to conceive is that each contact possesses a unique identifier field, that contains something like a UNIX Epoch timestamp, but this would potentially be slightly confusant for some users, and would certainly be useless for the use-case that is specified: duplicate imports. Perhaps for this problem specifically, the ability to revert modification would be useful, if currently unavailable.

**Comment by pipolakus38** [comment] 2022-06-02 07:10
As I wrote :"I imported my contacts twice" from a .VCF file, by exemple. So i see everybody twice, in my contact list. And I don't have the possibility to delete the duplicated contacts, in a simple way. I don't want to go manually in the database to remove them.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-06-02 22:05
Is your previous comment response to mine? I did not mention any such thing. My comment was description of one potential programmatic method of remediation of your problem, that would not entail what http://github.com/nextcloud/contacts/issues/2757#issuecomment-1144522120 describes.

**Comment by pipolakus38** [comment] 2022-06-03 07:47
My bad @BEEDELLROKEJULIANLOCKHART   😄

**Comment by joshtrichards** [comment] 2024-01-14 23:38
Duplicate of #70

**Closed by joshtrichards** 2024-01-14 23:38 UTC
Labels: enhancement, 0. Needs triage
