### ISSUE TITLE
ITEMX.ADR (address data) entered on iOS devices not shown in contacts web app at all

### ISSUE THREAD

**Issue by bcutter** [nextcloud/contacts#3729] opened 2023-12-05 21:55 UTC
### Describe the bug

Address data created by iOS devices not shown at all in contacts app. Available on iOS and server (synced), but not shown.

### Steps to reproduce

1. Create contact on iOS (see two examples in "Additional information" below)
2. Sync with NC server
3. Open contact on contacts web app
4. See there's no address visible at all
5. Download VCF and confirm the data is actually/still there (visibility issue)

### Expected behavior

Address data is shown in web app

### Actual behavior

Address data is not shown in web ap

### Contact version

5.4.2

### Operating system

Raspberry Pi OS

### PHP engine version

Other

### Web server

Nginx

### Database

MariaDB

### Additional info

Two vcard examples:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 16.6//EN
...
...
ITEM1.ADR;TYPE=HOME,pref:;;Street 1;City;;PLZ;Deutschland
ITEM1.X-ABADR:de
...
...
END:VCARD
```

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 16.5.1//EN
...
...
ITEM1.ADR;TYPE=HOME,pref:;;Street 1;City;;PLZ;Deutschland
ITEM2.ADR;TYPE=WORK:;;Street 2;City;;PLZ;Deutschland
ITEM1.X-ABADR:de
ITEM2.X-ABADR:de
...
...
END:VCARD
```

Unfortunately I can't name when this issue was introduced. I am very sure it wasn't always present. I just discovered it now by accident. Not very helpful I know, but what I'm saying: this used to work back at some point in time.

**Comment by DiagonalArg** [comment] 2023-12-10 03:22
It's not just itemN.ADR.  It seems to be *all* of them.  See: https://github.com/nextcloud/contacts/issues/3736

**Comment by DiagonalArg** [comment] 2023-12-10 03:52
No dev posts for 3 weeks, and the list of bugs is breathtakingly long.  All recent ones show no comments.  Is this project alive?

Do we have any alternatives?

**Comment by bcutter** [comment] 2023-12-10 10:56
> No dev posts for 3 weeks, and the list of bugs is breathtakingly long.  All recent ones show no comments.  Is this project alive?
> 
> 
> 
> Do we have any alternatives?

Indeed, many issues - but also many PRs, the oldest ones 2 years old. There are for sure reasons for this as it is FOSS.

![image](https://github.com/nextcloud/contacts/assets/13799156/36304899-3654-4f9f-8b67-497599c0f6a5)

Personal result: I just don't use the web interface (instead CalDAV clients on certain endpoints). If I **can't trust** the data shown there and to **avoid further visual or actual inconsistencies and redundancies**, I need to avoid a piece of basically great software.

Now back to the issue itself. Hopefully a dev can have a look at it.

**Comment by DiagonalArg** [comment] 2023-12-10 11:16
If it's not working in the web interface, I'm not sure I trust it on my device; and I've got too many contacts to check.

I hate to have to look for alternatives, as I run my own NC server, but I looks like the options are either DecSync with Syncthing, or EteSync (all findable on f-droid).

**Comment by DiagonalArg** [comment] 2023-12-13 12:17
Check if it's working for you with the upgrade to 5.5.0.  I'm seeing addresses with labels, but not all of them.  Also, addresses, though not all, are showing up like this:

";;1025 Keeler Ave;Berkeley;CA;94708-140 ..."

**Comment by bcutter** [comment] 2023-12-13 21:36
Indeed. 5.5.0 made the address to show up at all. But it's not readable as not presented atomic, "just" the line/Tag is shown as in the VCF file itself.

And other data shows up very strangely too like

![image](https://github.com/nextcloud/contacts/assets/13799156/485574f2-e0fe-4904-afa4-68d8aca60ae9)

I think there is a bit (lot?) of translation/compatibility work to be done here.

**Comment by DiagonalArg** [comment] 2023-12-13 22:40
Besides EteSync and DecSync/Syncthing, it looks like SOGo might be an alternative.  The difficulty is, I can't identity what the back-end stores are for any of these.  So it's not clear to me 1) what might eat my data through translation error and 2) what might both have sufficient editing and presentation facilities, and might not eat my data through poor implementation.  I need to be able to look at things on both linux and android, and at least edit things on the linux side (though preferably both).  This is appearing to be a daunting task.  

So, for example, the Android contacts app imports v3.0 and represents the data well, but exports as v2.1.  Simple-Contacts (it's been forked now and is in the process of discussing the new name) also represent it well, and exports as v4.0, but removes all CATEGORY labels (which are optional in the spec).  On the linux side, neither gnome-contacts, evolution, nor thunderbird/lightning show nor allow the ability to edit any of the labels (I haven't looked at thunderbird/Cardbook yet).  The only one that appears to do so is vcard-studio, but to sync in vcard format appears to need DecSync/Syncthing + decsync-vdir.  Too many hands in the pot, and I' having trouble deciphering it all.

**Comment by bcutter** [comment] 2023-12-13 23:21
You are getting off-topic imo. Don't hijack issues here for product information. None of that is helpful for the devs to fix this issue. Thanks.

**Comment by DiagonalArg** [comment] 2023-12-14 02:26
Ya, sorry.  I guess I'm kind of throwing up my hands in despair.

**Comment by bcutter** [comment] 2023-12-17 18:01
Interestingly: on one endpoint running Firefox, accessing contacts web app for the first time, initially address data was shown in the "data style" like `";;1025 Keeler Ave;Berkeley;CA;94708-140 ..."`. After selecting another contact and switching back, it seems to have fixed itself - at least for that browser on that endpoint for that moment.

Will need to monitor this for a while, specially on other endpoints/browsers.

Curious nobody picks up this issue. Didn't see anything relevant in the 5.5.0 release notes regarding this issue, wondering why it works now for some cases.

What remained also in that positive single discovery is...
![grafik](https://github.com/nextcloud/contacts/assets/13799156/926d3323-41f9-43be-9c0e-55014c303a16)

**Comment by hamza221** [comment] 2023-12-19 15:07
duplicate of #3721

**Closed by hamza221** 2023-12-19 15:07 UTC
Labels: bug, feature: contacts, 0. Needs triage
