### ISSUE TITLE
merging contact entries

### ISSUE THREAD

**Issue by pafcioooo** [nextcloud/contacts#136] opened 2017-02-17 06:18 UTC
### Steps to reproduce
1. I have two contact entries in addressbook for the same person
2. I want to have one contact entry for that person

### Expected behaviour
I should have possibility to mark both entries and select merge.
Entries are merged

- If one of the entries is empty then they are simply copied over 
- If they are both full then additional entries are created (example:. as additional email address)

### Actual behavior
No such function

**Comment by skjnldsv** [comment] 2017-02-17 11:43
Duplicate of #80

**Closed by skjnldsv** 2017-02-17 11:43 UTC
