### ISSUE TITLE
Cannot change photo of contact

### ISSUE THREAD

**Issue by despens** [nextcloud/contacts#1106] opened 2019-05-22 10:18 UTC
### Describe the bug

When a contact already has a photo assigned, clicking on the photo just enlarges it, but doesn't show the menu for uploading or picking another one.

**To Reproduce**
1. Create new contact
2. Click on empty circle
3. Upload a photo
4. Click on the circle again

**Expected behavior**

Clicking on the photo should allow to change it.

**Actual behavior**

The photo is displayed in a lightbox.

### Server configuration

**Nextcloud version:** 15.0.7

**Contacts version:** 3.1.1

**Comment by skjnldsv** [comment] 2019-05-22 10:28
Duplicate of #1086

**Closed by skjnldsv** 2019-05-22 10:28 UTC
