### ISSUE TITLE
Birthday, Date of Death, Anniversary fields are date-time fields, but should only be date fields

### ISSUE THREAD

**Issue by thrawn-sh** [nextcloud/contacts#795] opened 2018-12-25 08:29 UTC
### Describe the bug
When entering / modifying a date in a Birthday, Date of Death, Anniversary the resulting date is displayed/saved as date-time instead of only date. IMHO the time component is irrelevant and makes it harder to read.

**To Reproduce**
1. Go to a contact
2. Click on "Choose property type" of "Add new property"
3. Select Birthday, Date of Death or Anniversary
4. Pre-filled value is the current date-time

**Expected behavior**
The value should only be date.

**Actual behavior**
The value is date-time

**Screenshots**
![initial](https://user-images.githubusercontent.com/5955972/50417447-44edff80-081e-11e9-8286-afda5a372cd5.png)

### Server configuration

**Operating system**: Linux

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:**  7.0.33-0+deb9u1

**Nextcloud version:**  15.0.0

**Contacts version:** 3.0.1

**Updated from an older Nextcloud or fresh install:** Update

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - gpxedit: 0.0.10
  - gpxpod: 3.0.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_versions
  - firstrunwizard
  - password_policy
  - support
  - survey_client
  - systemtags
  - theming
  - user_external
```

```
{
    "system": {
        "appstore.experimental.enabled": false,
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 4,
        "logtimezone": "UTC",
        "maintenance": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "7, 14",
        "trusted_domains": [
             "***REMOVED SENSITIVE VALUE***",
             "***REMOVED SENSITIVE VALUE***"
        ],
        "version": "15.0.0.10",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "pgsql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 587,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG"
        ],
        "overwrite.cli.url":  "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:**
Friefox 64
Chromium 71.0.3578.80

**Operating system:**
Linux

**CardDAV-clients:**

#### *Web server error log*
```
No error in the log
```

#### *data/nextcloud.log*
```
No entry for Debug/Info/Warning/Error/Fatal
```

#### Browser log
```
Browser Log/Console is empty
```

**Comment by skjnldsv** [comment] 2018-12-31 13:06
Duplicate of #796

**Comment by skjnldsv** [comment] 2019-01-24 10:31
@devlux actually BDAY can be date and/or time
https://tools.ietf.org/html/rfc6350#section-6.2.5

6.2.5.  BDAY

   Purpose:  To specify the birth date of the object the vCard
      represents.




Perreault                    Standards Track                   [Page 30]
 
```
RFC 6350                          vCard                      August 2011


   Value type:  The default is a single date-and-or-time value.  It can
      also be reset to a single text value.

   Cardinality:  *1

   ABNF:

     BDAY-param = BDAY-param-date / BDAY-param-text
     BDAY-value = date-and-or-time / text
       ; Value and parameter MUST match.

     BDAY-param-date = "VALUE=date-and-or-time"
     BDAY-param-text = "VALUE=text" / language-param

     BDAY-param =/ altid-param / calscale-param / any-param
       ; calscale-param can only be present when BDAY-value is
       ; date-and-or-time and actually contains a date or date-time.

   Examples:

             BDAY:19960415
             BDAY:--0415
             BDAY;19531015T231000Z
             BDAY;VALUE=text:circa 1800
```

**Comment by devlux** [comment] 2019-01-24 10:49
@skjnldsv thank you for the explanation, which of course makes sense :-) is it possible to tell the datetime picker to only store date when editing? I've tried to remove the time but was not successfull...

**Comment by skjnldsv** [comment] 2019-01-24 10:56
That's actually why I reopened the issue :)
I have no idea how we could do that properly. Do you have a suggestion? 
The issue also happens with the *ommit year* option (#625). How should we add that in the UI without looking terrible? @jancborchardt any idea?

**Comment by jancborchardt** [comment] 2019-01-24 13:39
To be honest: The time this is part of the spec, but no contacts app provides input options for the time. We shouldn’t either, and just show the date, not the time.

And yes, in the year picker there could simply be a "No year" option in the list of years, maybe always after the current year. ("Omit year" (1 m only) could be a bit long for translations.)

## Examples (swiped from image search)
iOS contacts
![](https://media.idownloadblog.com/wp-content/uploads/2018/05/iOS-11-Contacts-add-birthday.png)

Google Contacts
![](https://i.stack.imgur.com/uyKiP.png)

Facebook
![](https://www.wikihow.com/images/thumb/5/58/Change-Your-Birthday-on-Facebook-Step-6-Version-4.jpg/aid881460-v4-728px-Change-Your-Birthday-on-Facebook-Step-6-Version-4.jpg)

**Comment by raoulbhatia** [comment] 2019-02-22 09:38
I am also interested in this feature.

**Comment by skjnldsv** [comment] 2019-03-05 10:52
Fixed for the incoming version

**Closed by skjnldsv** 2019-03-05 10:52 UTC
Labels: 1. to develop, enhancement
