### ISSUE TITLE
Not possible to share contacts or contact groups with other users

### ISSUE THREAD

**Issue by krafel** [nextcloud/contacts#3703] opened 2023-11-16 08:59 UTC
### Describe the bug

It is not possible to share a specific contact or contact groups with other users of the nextcloud instance. The only way is
- to share a address book
- to export a contact and import it as the other user as vcf

Background: 
Sharing contacts by address books is not enough. If I don't want to share a whole address book with other members of my nextcloud instance (e.g. business partners) I have to either clone the entry into another adress book and share that (but then I have two entries of the same contact. Difficult to maintain, when the contact's details change!).

The basic problem is that one single contact can be member of many groups, but of only one adress book. And contacts from different address books can be in one group.  This would be very helpful to create a set of contacts from various address books that you'd like to share.

### Steps to reproduce

1. Go to a contact
3. There is no option to share the contact

### Expected behavior

Implemented functionality to share single contacts or contact groups

### Actual behavior

Sharing not possible but via address books.

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment] 2023-11-16 09:02
nextcloud/contacts version please

**Comment by joshtrichards** [comment] 2024-01-15 13:26
Duplicate of #111

**Closed by joshtrichards** 2024-01-15 13:26 UTC
Labels: bug, needs info, regression, feature: contacts, 0. Needs triage
