### ISSUE TITLE
Button to Merge recently contacted with existing contact (and thus removing them from recently contacted)

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/contacts#2818] opened 2022-07-06 16:07 UTC
### Is your feature request related to a problem? Please describe.

I am frustrated that you cannot delete recently contacted cards,
you should be able to remove persons from this contactlist.

### Describe the solution you'd like

If you can have a button underneath the 3 dots where you can merge the contact info to another contact that already exists,
and removes the person from the list that would be great. 
![image](https://user-images.githubusercontent.com/64335794/177594851-279a0a02-5dae-47f6-b2f7-ce8624b80999.png)

### Describe alternatives you've considered

Just be able to remove the person is also a solution, but less useful

**Comment by jancborchardt** [comment] 2023-12-21 13:13
This is a duplicate of https://github.com/nextcloud/contacts/issues/2679, let’s continue tracking it there. :)

**Closed by jancborchardt** 2023-12-21 13:13 UTC
Labels: enhancement, 0. Needs triage
