### ISSUE TITLE
Save icon turns cycling and cycling and cycling ...

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/contacts#1289] opened 2019-10-02 07:19 UTC
Dear Team,

my actual config:

NC 16.0.5 / Contacts 3.1.4 / NGINX (ReverseProxy) 1.17.3 / PHP 7.3.8

I have 245 contacts. When one will be saved, the circle appears and never ends ... see picture.

![02-10-_2019_09-16-53](https://user-images.githubusercontent.com/6906390/66024978-a5207900-e4f5-11e9-8266-c716494921b9.jpg)

Any Idea?? Thank you, Tom

**Comment by skjnldsv** [comment] 2019-10-02 08:18
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by kangaroo72** [comment] 2019-10-02 10:50
@skjnldsv  see the attached log. Thank you, Tom
[cloud.escher.cc-1570013296114.log](https://github.com/nextcloud/contacts/files/3680730/cloud.escher.cc-1570013296114.log)

**Comment by skjnldsv** [comment] 2019-10-02 10:54
Thanks!
Does it do that on every contact?

**Comment by skjnldsv** [comment] 2019-10-02 10:55
Highly possible duplicate of https://github.com/nextcloud/contacts/issues/1009

**Comment by kangaroo72** [comment] 2019-10-02 11:06
Not with every contact.
Some contacts appear with "This contact was broken and received a fix. Please review the content and click here to save it." and then there's the issue ...

**Comment by skjnldsv** [comment] 2019-10-02 11:11
Okay, can you download the contact and paste it here maybe? (you can obfuscate some sensitive data, but don't edit the data like ,;:\... etc) :)

**Comment by kangaroo72** [comment] 2019-10-02 11:28
Does that help?

https://paste.escher.cc/view/6c44ad41

**Comment by skjnldsv** [comment] 2019-10-02 11:30
Yep! 
```
ADR;TYPE=home;LABEL="xxxxxxxxrstr. 56, 60000 Thecity":;;xxxxxxxxrst
 r. 36\, 60000 Thecity;;;;
```

Duplicate of https://github.com/nextcloud/contacts/issues/1009
Basically we're waiting for a fix on an external library :(

**Closed by skjnldsv** 2019-10-02 11:30 UTC
Labels: 0. Needs triage, bug, needs info
