### ISSUE TITLE
Nextcloud contacts eats characters during entry

### ISSUE THREAD

**Issue by Debianer** [nextcloud/contacts#966] opened 2019-03-02 23:01 UTC
I migrated from a PHP Nextcloud package that I used on a shared web host to a docker install. I use the official apache docker image and then I use haproxy as a transparent proxy for letsencrypt. I imported about 400 contacts by exporting to CardDAV from the old Nextcloud and then importing into the new one. 

When I change contacts now or when I add new contacts, characters disappear. It may happen when I type fast. It doesn't seem to happen when I type very slow. But at normal speed about one third of characters I enter will disappear seemingly at random. 

The client is Firefox running on Linux.

**Comment by Huster-at-github** [comment] 2019-03-03 02:07
Yes, nearly unpossilble to edit contacts. I have 3 address books with together 1.300 entries.

**Comment by skjnldsv** [comment] 2019-03-03 08:46
Duplicate of #923

**Closed by skjnldsv** 2019-03-03 08:46 UTC
Labels: bug
