### ISSUE TITLE
Autosave updating fields after DB submit

### ISSUE THREAD

**Issue by JaredNJames** [nextcloud/contacts#978] opened 2019-03-07 07:58 UTC
### Describe the bug
When creating a new contact in the app on Nextcloud, it autosaves very frequently as you type.  As I start typing a name, say "Alice Appleby", it autosaves part way through and loses the last few characters.  

What this looks like is I type "Alice Appleby", but it will autosave halfway at "Alice App" and then reset the field to "Alice App", losing everything I typed after that point.

It's worse if there's more text, e.g. "Alice Appleby Smith", because the moment it autosaves and resets it goes back to "Alice App" and then continues typing, so you end up with "Alice Appmith".

I can cope with it on the occasional new contact, but to try and add several it is really frustrating.  I've lost several phone numbers because I didn't see this and now I have the start and end only.

**To Reproduce**
As above.  Try to create a new contact and as you type monitor for autosave jumping around the text fields.

**Expected behavior**
Contact should be created, with autosave being a passive event - it should autosave whatever the contents are at the time of actioning, but not feedback to the fields.

**Actual behavior**
Autosave is submitting to the database and then updating the fields on the page with whatever was just submitted.  Wiping out anything not submitted but accepted into the fields, post-save event.

### Server configuration
issuetemplate not available for 15...

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 15.0.4

**Contacts version:** 3.0.3

**Updated from an older Nextcloud or fresh install:** Clean install on a clean install of Debian.

**Signing status:** /index.php/settings/integrity/failed doesn't exist

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - apporder: 0.6.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - passwords: 2019.3.0
  - previewgenerator: 2.1.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - workflowengine: 1.5.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}

### Client configuration
**Browser:** Chrome / Firefox / Edge

**Operating system:** Windows 7 / 10

**CardDAV-clients:** None at present.

#### *Web server error log*
The only error in the log that isn't someone calling for a non-existent page is:

[Thu Mar 07 07:34:20.271141 2019] [php7:warn] [pid 16331] [client 199.253.103.242:12512] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /../../../cloud/3rdparty/sabre/vobject/lib/Component/VCard.php on line 514

#### *data/nextcloud.log*
No nextcloud errors.

#### Browser log
No browser console errors.

**Comment by JaredNJames** [comment] 2019-03-07 08:07
Checked app latest version based on above bot response.  I have Nextcloud 15.0.4 but below that under "Basic Settings" is blank.  It doesn't give any option to update to 15.0.5, nor does it say it's the latest version.

**Comment by JaredNJames** [comment] 2019-03-07 08:24
Updated manually to 15.0.5.  No change to the issue.

**Comment by skjnldsv** [comment] 2019-03-07 08:31
Duplicate of the fixed issue #923

**Closed by skjnldsv** 2019-03-07 08:31 UTC
Labels: bug

**Comment by JaredNJames** [comment] 2019-03-07 08:32
@skjnldsv do you have an ETA?  It's crippled one of my main functions as it stands.

**Comment by skjnldsv** [comment] 2019-03-07 08:38
@a1pilot sure, I'm waiting to see if the translators on transifex finished translating the new string I added this week into the most used languages :)
So It should be tomorrow I hope ;)

**Comment by a1pilot** [comment] 2019-03-07 08:53
@skjnldsv great stuff, thanks.

**Comment by a1pilot** [comment] 2019-07-23 08:10
@skjnldsv This is back in 3.1.3.
