### ISSUE TITLE
End-To-End Encryption

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/contacts#1489] opened 2020-02-29 02:23 UTC
Please add the ability to have client side encryption with Nextcloud contacts. This will require Nextcloud making a Nextcloud contacts app for Android, iOS, Windows, Mac and Linux or having the Nextcloud clients add a contacts syncing integration into the app.

EteSync is the king of privacy and security for contacts since they have E2EE. I would like to see Nextcloud add this security and even allow the ability to edit the contacts in the browser using JavaScript to encrypt/decrypt the client side encryption.

**Comment by skjnldsv** [comment] 2020-02-29 08:01
Hey :)
Duplicate of #274 

This is a backend feature (the contacts storage) so it is for the https://github.com/nextcloud/server repository ;)

There is already an opened issue about this

**Closed by skjnldsv** 2020-02-29 08:01 UTC
Labels: 0. Needs triage, enhancement
