### ISSUE TITLE
Additional phone number field not found

### ISSUE THREAD

**Issue by djelouze** [nextcloud/contacts#779] opened 2018-12-19 08:46 UTC
⚠ Please report only issues corresponding to the contacts app for Nextcloud ⚠

Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues

If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts
__________________________________________________________________

### Describe the bug
Contacts 3.0.0 does not show Phone number or e-mail in "Add new property" menu

**To Reproduce**
1. Click on "New contact"
2. Click on "Choose new property type" in "+ Add new property"
3. Scroll and look for Phone number or E-mail
4. Error : not found!

**Expected behavior**
I would like to set several number and e-mail for contacts

**Actual behavior**
This is not possible anymore

**Screenshots**

![capture d ecran de 2018-12-18 14-13-59](https://user-images.githubusercontent.com/149713/50208743-504eb000-0372-11e9-8978-0561d7c90a89.png)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** 15

**Contacts version:** 3.0.0

**Updated from an older Nextcloud or fresh install:** Fresh install

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

**CardDAV-clients:** 

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment] 2018-12-19 08:49
Duplicate of #771

**Closed by skjnldsv** 2018-12-19 08:49 UTC
Labels: need info
