### ISSUE TITLE
Birthday, Date of Death, Anniversary save wrong date

### ISSUE THREAD

**Issue by thrawn-sh** [nextcloud/contacts#794] opened 2018-12-25 08:24 UTC
### Describe the bug
When entering / modifying a date in a Birthday, Date of Death, Anniversary the resulting date is off-by-one for the month

**To Reproduce**
1. Go to a contact
2. Click on "Choose property type" of "Add new property"
3. Select Birthday, Date of Death or Anniversary
4. Pre-filled value is the current date (correct)
5. Select an other date

**Expected behavior**
The property displays the selected date.

**Actual behavior**
The property displays a date, that is of-by-one for the month

**Screenshots**
![initial](https://user-images.githubusercontent.com/5955972/50417447-44edff80-081e-11e9-8286-afda5a372cd5.png)
![selected](https://user-images.githubusercontent.com/5955972/50417450-4a4b4a00-081e-11e9-911e-955b103c91f8.png)
![displayed](https://user-images.githubusercontent.com/5955972/50417454-4fa89480-081e-11e9-8dd6-ec31fa8de586.png)

### Server configuration

**Operating system**: Linux

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:**  7.0.33-0+deb9u1

**Nextcloud version:**  15.0.0

**Contacts version:** 3.0.1

**Updated from an older Nextcloud or fresh install:** Update

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - gpxedit: 0.0.10
  - gpxpod: 3.0.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_versions
  - firstrunwizard
  - password_policy
  - support
  - survey_client
  - systemtags
  - theming
  - user_external
```

```
{
    "system": {
        "appstore.experimental.enabled": false,
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 4,
        "logtimezone": "UTC",
        "maintenance": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "7, 14",
        "trusted_domains": [
             "***REMOVED SENSITIVE VALUE***",
             "***REMOVED SENSITIVE VALUE***"
        ],
        "version": "15.0.0.10",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "pgsql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 587,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG"
        ],
        "overwrite.cli.url":  "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:**
Friefox 64
Chromium 71.0.3578.80

**Operating system:**
Linux

**CardDAV-clients:**

#### *Web server error log*
```
No error in the log
```

#### *data/nextcloud.log*
```
No entry for Debug/Info/Warning/Error/Fatal
```

#### Browser log
```
Browser Log/Console is empty
```

**Comment by R0maNNN** [comment] 2018-12-26 10:58
+

**Comment by skjnldsv** [comment] 2018-12-31 13:04
Duplicate of #795

**Closed by skjnldsv** 2018-12-31 13:04 UTC
Labels: bug, need info
