### ISSUE TITLE
Changing email type doesn't update X-ABLABEL

### ISSUE THREAD

**Issue by raoulbhatia** [nextcloud/contacts#560] opened 2018-05-29 07:50 UTC
### Steps to reproduce
1. Upload a contact with X-ABLABEL set for the email, i.e.
```
ITEM1.EMAIL;TYPE=OTHER;TYPE=pref:email@domain.tld
ITEM1.X-ABLABEL:_$!<Other>!$_
```
2. The email address will be shown as type `_$!<OTHER>!$_`.
3. Change the type to `Work`.
4. Switch contacts from one to another contact and back.
5. The email address still shows as type `_$!<OTHER>!$_`.

### Expected behaviour
The vcard should be sanitized and simplified to contain something like:
```
EMAIL;TYPE=WORK:email@domain.tld
```

### Actual behaviour
The updated vcard is PUT to the server.  The request parameter shows:
```
ITEM1.EMAIL;TYPE=WORK;TYPE=pref:email@domain.tld
ITEM1.X-ABLABEL:_$!<Other>!$_
```

### Server configuration
**Operating system**: Ubuntu 17.10

**Web server:** nginx from Ubuntu package nginx-extras version 1.12.1-0ubuntu2

**Database:** MySQL from Ubuntu version 5.7.22-0ubuntu0.17.10.1

**PHP version:** PHP7.1 from Ubuntu version 7.1.17-0ubuntu0.17.10.1

**Nextcloud version:** 13.0.2

**Contacts version:** 2.1.3

**Updated from an older Nextcloud or fresh install:** Update through various releases.  Last update from 13.0.1.

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Let me know if relevant to share.
```

**Nextcloud configuration:**

```
Let me know if relevant to share.
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 60.0.1

**Operating system:** MacOS

**CardDAV-clients:** N/A

#### Web server error log
```
N/A
```

#### Nextcloud log (data/nextcloud.log)
```
N/A
```

#### Browser log
```
Let me know if relevant to share.
```

**Comment by skjnldsv** [comment] 2018-05-29 07:52
Hello! :)
Yes, we do no supports X-properties yet.

**Comment by raoulbhatia** [comment] 2018-05-29 12:07
Thanks for the update.  Let me know if there is anything I can help with – besides writing a patch ;-)

**Comment by skjnldsv** [comment] 2018-10-01 16:48
Let's put his into another issue
Duplicate of #27

**Closed by skjnldsv** 2018-10-01 16:48 UTC
Labels: 1. to develop, compatibility
