### ISSUE TITLE
Show error when trying to import LDIF address book

### ISSUE THREAD

**Issue by ahstro** [nextcloud/contacts#1387] opened 2019-12-24 03:44 UTC
### Describe the bug
When trying to import an address book in the LDIF format (as exported from SOGo, for example), the app stops at the modal saying it's importing contacts, not reporting any errors even though the console shows an error.

**To Reproduce**
1. Try to import an LDIF formatted address book
2. See error
3. Look in the console
4. See more error
5. Be sad 😥

**Expected behavior**
Ideally, the app should support LDIF, but since that isn't near on the roadmap (#1134), it should display the error(s) that have happened.

**Actual behavior**
It pretends to be importing contacts, while nothing - in fact - happens.

**Screenshots**
![done-importing](https://user-images.githubusercontent.com/3090888/71392207-997db380-2607-11ea-9160-eb60bd7b3587.png)

**Comment by haukegithub** [comment] 2020-03-16 18:58
Nextcloud can't import ldif, but you can convert to vcf and then import to Nextcloud.
To convert ldif to vcf you can user Thunderbird.

Problem: 
Thunderbird converts to vcf-version 2.1 and Nextcloud can only handle 4.x.
So you have to convert.
For that I used this Python script:

`f = open("output.vcf", "a")
idCountBase = "0xfb44caa1468f"
idAsInt = int(idCountBase, 16)
idAsInt += 1
theName = ""
telNr = ""

def writeit():
    f.write("BEGIN:VCARD\n")
    f.write("VERSION:4.0\n")
    f.write("PRODID:-//Nextcloud Contacts v3.2.0\n")
    f.write("UID:b0d19993-a542-47e3-b69c-" + idAsHex + "\n")
    f.write("REV;VALUE=DATE-AND-OR-TIME:20200312T085943Z\n")
    f.write("FN:" + theName + "\n")
    f.write("ADR;TYPE=HOME:;;;;;;\n")
    f.write("EMAIL;TYPE=HOME:\n")
    f.write('TEL;TYPE="HOME,VOICE":' + telNr + "\n")
    f.write("END:VCARD\n\n")

filepath = "vcf-file-from-thunderbird-conversion.vcf"
with open(filepath) as fp:
    line = fp.readline()
    cnt = 1
    while line:
        idAsInt = int(idCountBase, 16)
        idAsInt += 1
        idAsHex = hex(idAsInt)
        idCountBase = idAsHex
        
        if(line.strip().startswith("fn:")):
            theName = line.strip().split(":")[1]
            
        if(line.strip().startswith("tel;cell:")):
            telNr = line.strip().split(":")[1]
        if(line.strip().startswith("end:vcard")):
            writeit()
        
        line = fp.readline()
        cnt += 1

f.close()`

You need to have both vcf files mentioned in script in same directory.

After that you finally can import "output.vcf" to Nextcloud!

**Comment by skjnldsv** [comment] 2020-03-17 13:26
> Ideally, the app should support LDIF, but since that isn't near on the roadmap (#1134), it should display the error(s) that have happened.

Leaving opened for proper error handling

Can one of you two provide a ldif example file just so I can at least see what we can do?

**Comment by haukegithub** [comment] 2020-03-17 16:47
This is the ldif formatted entry of one person:
```
dn: cn=NAME
objectClass: top
objectClass: inetOrgPerson
objectClass: mozillaAbPersonAlpha
displayname: NAME
sn: SURNAME
mobile: NUMBER
givenname: NAME
```
The next entry will just follow after a blank line.

**Comment by haukegithub** [comment] 2020-03-17 17:16
The above example wasn't complete, here's one when filling every field in SOGo v4.3.0:
```
dn: cn=Display name,mail=email-duty@mail.com
objectClass: top
objectClass: inetOrgPerson
objectClass: mozillaAbPersonAlpha
description: Notes
title: Title
mozillaworkurl: https://www.example-duty.org/
st: Region (Duty)
displayname: Display name
mozillahomepostalcode: ZIP (Private)
pager: 1234567890
mail: email-duty@mail.com
birthmonth: 03
mozillaworkstreet2: Street (continuation) (Duty)
c: Country (Duty)
mozillasecondemail: email-private@mail.com
mozillanickname: Nickname
sn: Surname
mozillahomestreet2: Street (continuation) (Private)
facsimiletelephonenumber: 1234567890
homephone: 1234567890
mozillahomestate: Region (Private)
telephonenumber: 1234567890
postalcode: ZIP (Duty)
nsaimid: Messenger-Name
mobile: 0123456789
o: Organisation
birthyear: 2020
givenname: Forename
l: City (Duty)
mozillahomecountryname: Country (Private)
birthday: 17
mozillahomelocalityname: City (Private)
mozillahomestreet: Street (Private)
mozillahomeurl: https://www.example-private.org/
ou: Organisational unit 1, Organisational unit 2
street: Street (Duty)
```

**Comment by skjnldsv** [comment] 2020-09-07 11:02
Duplicate of #1653

**Closed by skjnldsv** 2020-09-07 11:02 UTC
Labels: 1. to develop, bug
