### ISSUE TITLE
Unable to save new contact groups

### ISSUE THREAD

**Issue by GVodyanov** [nextcloud/contacts#3880] opened 2024-04-11 16:29 UTC
### Describe the bug

When creating a contact group it shows in the UI, but after reloading the page you get an error saying that the group created wasn't found and it doesn't appear in the UI any more.

### Steps to reproduce

1. Go to 'Contact groups'
2. Create a new contact group
3. Reload page

### Expected behavior

The contact group should appear in the sidebar and there is no error

### Actual behavior

There is no contact group and an error

### Contact version

Main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment] 2024-04-11 17:25
Duplicate of https://github.com/nextcloud/contacts/issues/2511.

vcard groups are not real entities. they only exists if there is at least one contact pointing to them. so technically, the app works as expected.

**Closed** 2024-04-11 18:03 UTC
Labels: bug, feature: contacts, 0. Needs triage
