### ISSUE TITLE
Similar contact entries regarded as duplicates, and not displayed?

### ISSUE THREAD

**Issue by mburnicki** [nextcloud/contacts#286] opened 2017-08-14 08:59 UTC
I've recently upgraded from owncloud 8.2.x to nextcloud 12.0.1, with contacts 1.5.3.

I'm maintaining quite a number of address books for folks who are not familiar with this kind of stuff, and sometimes there are similar contacts in different address books, or even similar entries in the same address book, e.g. 2 personal entries with individual mobile numbers for wife and husband, and a combined entry for both, with the shared landline phone number.

So if you receive a call you know exactly if the individual calls you, or someone is using their landline phone. 

Since the upgrade to nextcloud some of these similar "contacts" are not displayed by the contacts app. They are still displayed in the contacts list of my Android phone, and by the KDE PIM suite, so the entries are still in the database.

Is there a specific "feature" in contact 1.5.3, where the app tries to merge similar contacts (like Android might do if contacts have the same phone number or email address), or may the app be unable to handle some database entries correctly?

**Comment by Henni** [comment] 2017-10-25 21:25
This shouldn't happen. Resolving duplicates isn't implemented in this app and should especially not occur like you described it.

Is it possible that you give us access to a pair of these contacts in the form of vcards?

**Comment by skjnldsv** [comment] 2018-03-07 08:58
Does this still occurs?

**Comment by mburnicki** [comment] 2018-03-07 09:21
I'm going to check it, but won't have time to do so before the weekend.

@Henni Sorry, I somehow missed your comment. Saw it just now. I'll come back to this soon.

**Comment by skjnldsv** [comment] 2018-03-07 09:23
@mburnicki don't apologise, we're all late to the party it seems ;)

**Comment by skjnldsv** [comment] 2018-10-01 15:47
Closing as this should not happen anymore except if the contact if failing, which is not related to this issue and not a bug

**Closed by skjnldsv** 2018-10-01 15:47 UTC
Labels: bug, needs info
