### ISSUE TITLE
iOS corrupts vcards (e.g. address disappears)

### ISSUE THREAD

**Issue by JAKuhr** [nextcloud/contacts#901] opened 2019-01-31 22:33 UTC
I just noted that existing contact data gets corrupted if I edited an already existing contact on my iphone. For example if the contact had a address before, this is not shown anymore in nextcloud's web interface. I think this happens because iOS changes the VCARD attributes.

Original VCARD created with nextcloud's web interface (address visible):
> BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:71c59898-1e31-4e1a-8be8-9a7968f5aa4f
FN:Hans Testmann
ADR;TYPE=HOME:;;Bahnhofstraße 11;Hamburg;;21102;Deutschland
EMAIL;TYPE=HOME:hans.testmann@gmail.com
TEL;TYPE="HOME,VOICE":+49 (40) 77733300
N:Testmann;Hans;;Dr.;
END:VCARD

Same VCARD after editing a detail on my iphone (address dissapeared):
> BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 12.1.3//EN
N:Testmann;Hans;;Dr.;
FN:Dr. Hans Testmann
EMAIL;type=INTERNET;type=HOME;type=pref:hans.testmann@gmail.com
TEL;type=HOME;type=VOICE;type=pref:+49 40 77733300
item1.ADR;type=HOME;type=pref:;;Bahnhofstraße 11;Hamburg;;21102;Deutschland
REV:2019-01-31T22:26:29Z
UID:71c59898-1e31-4e1a-8be8-9a7968f5aa4f
END:VCARD

The issue seems to be that iOS adds "item1." to the ADR field. Perhaps this is not standard conform but it should be handled somehow.

**Comment by skjnldsv** [comment] 2019-02-01 10:34
Hey, this is a duplicate of #793

**Closed by skjnldsv** 2019-02-01 10:34 UTC
Labels: bug
