### ISSUE TITLE
Contacts from MacOS show only the last Addressbook from Nextcloud.

### ISSUE THREAD

**Issue by SvenKo** [nextcloud/contacts#597] opened 2018-08-17 09:52 UTC
Hi all,

i have two Logins in my Nextcloud: My own ("alpha" - the connection for my MAC) and a dummy ("bubu").  My Contacts from "alpha" works with my MAC perfect, but: if i filled the addressbook in "bubu" and shared it read only with "alpha" my MAC shows only the addressbook from "bubu" and the contacts from "alpha" are missing. I changed the Adressbook Name to "alpha" and "bubu". The Logfiles are empty.

What can i do? With iOS everything works perfect...

Thanks, Sven

Nextcloud 13.0.5.2 / CentOS 7.5 / nginx 1.14.0 / php 7.2.8
macOS High Sierra 10.13.6 / Contacts 11.0 (1808.8)

**Comment by skjnldsv** [comment] 2018-10-01 16:57
Duplicate of #399

**Closed by skjnldsv** 2018-10-01 16:57 UTC
