### ISSUE TITLE
Feature request: Sort groups alphabetically

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1215] opened 2019-08-15 10:44 UTC
**Is your feature request related to a problem? Please describe.**
Scenario: I added several groups to my contacts from time to time. 

If I add a new contact and want to assign a group to the contact, the list of groups is not lexicographically sorted, but keeps somehow the order when the group has been created (e.g. "Theater, abc, zzz Other, Colleagues, ..."). This order is useless and not intuitive.

**Describe the solution you'd like**
The list is sorted lexicographically and case-insensitively (aAbBcCdD...), in my example: "abc, Colleagues, Theater, zzz Other").

**Comment by skjnldsv** [comment] 2019-08-15 15:26
Duplicate of #522 and #1212

**Closed by skjnldsv** 2019-08-15 15:26 UTC
Labels: 0. Needs triage, enhancement
