### ISSUE TITLE
Contacts app only listing All contacts

### ISSUE THREAD

**Issue by cdmlb** [nextcloud/contacts#782] opened 2018-12-22 22:52 UTC
Contacts app only listing All contacts but not the extra address books in the listing.

I can create address books, create contacts, pick an address book from the list to add the contact to. I can share the address books. View the address book in the settings section.

But on the contacts page all you have on the left side for an address book is All contacts.

I even tested this on the https://demo.nextcloud.com/ and installed the contacts app and the same issue exist there.

**Comment by skjnldsv** [comment] 2018-12-23 10:00
Hello, I'm not sure I properly get what you mean.
Are you talking about groups? Addressbooks are in the settings section on the bottom left.
Can you share a screenshot of what is it you're missing?

Thanks a lot :smiley:

**Comment by cdmlb** [comment] 2018-12-23 17:34
@skjnldsv I'm talking about if I have multiple address books in the contacts app why is there only listed All contacts and not all the actual other address books.

The only place you see the other address books are in the contacts apps settings on the contact apps page or in the list of adding a contact to an address book.

What's the point of having multiple address books if I can't select that address book to view it and that I can only use All contacts to view all the contacts from all the address books.

Speaking of groups, I have 3 groups, but the groups drown down says empty list.

Screen shot can be found here.
[https://i.postimg.cc/q7BchZFJ/Contacts-App.png](https://i.postimg.cc/q7BchZFJ/Contacts-App.png)

**Comment by skjnldsv** [comment] 2018-12-24 06:18
@cdmlb Okay, this is a feature request then, not a bug!
You can disable addressbooks in the settings if you want to only display one specifically. This is why we added this.

I'll then close this as it have already been discussed and we want to work that way and not add one more setting to show only one addressbook, which will be confusing. :)

Thanks a lot for your issue anyway!
Enjoy the vacations/Christmas!

**Closed by skjnldsv** 2018-12-24 06:18 UTC
Labels: bug, need info
