### ISSUE TITLE
Clicking a .vcf file just automatically imports entire file without warning

### ISSUE THREAD

**Issue by Terrox** [nextcloud/contacts#1880] opened 2020-10-24 04:11 UTC
### Describe the bug
......
Clicking a .vcf file just automatically imports entire file without warning, maybe you don't know what a .vcf file is and you click it to find out what is in it.
......

**To Reproduce**
1. Click on a .vcf file stored in your Nextcloud storage in web UI.
2. view switches to Contact App and starts importing into the FIRST enabled Addressbook you have.
- if you do this twice you get duplicates. (using Cardbook addon to sync contacts in Thunderbird helps fix dupes)

**Expected behavior**
Warning before import explaining which address book will be used, how many contacts to import and option to cancel.
Choice of Address book to import into (because it isn't obvious that you need to disable specific ones to get the right one), or Group to add during Import would also help.
Checkbox choice of contacts to import would also help.
List of contacts which failed would also help.

**Actual behavior**
Everything is imported from .vcf file
Errors are not showing which address fails to import. (not related to this bug exactly though)

### Server configuration

**Operating system**: Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP x86_64

**Web server:** Apache/2.4.6 (fpm-fcgi)

**Database:** mysql 10.2.34

**PHP version:** 7.4

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Contacts version:** 3.4.1

**Updated from an older Nextcloud or fresh install:**

**Signing status:**
```
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 248b1c46827f16075a92457d368b5f8c1c6d39c8dc8569e248b35443ac035501b86b8f46785cc6fb3f12fc8445284829c1e27aa82097a53d2688040b1de7da26
                        )

                )

        )

)

```

**List of activated apps:**
```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.1
 - admin_audit: 1.9.0
 - audioplayer: 2.12.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.4.1
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.1.2
 - drawio: 0.9.7
 - event_update_notification: 1.0.2
 - external: 3.6.0
 - federatedfilesharing: 1.9.0
 - files: 1.14.0
 - files_downloadactivity: 1.8.0
 - files_external: 1.10.0
 - files_external_gdrive: 0.4.0
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.23
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - groupfolders: 7.1.0
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - metadata: 0.12.0
 - news: 14.2.2
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - passwords: 2020.10.0
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quota_warning: 1.8.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.5
 - support: 1.2.1
 - suspicious_login: 3.2.1
 - systemtags: 1.9.0
 - tasks: 0.13.5
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - weather: 1.7.3
 - workflowengine: 2.1.0
Disabled:
 - encryption
 - federation
 - mail
 - rainloop
 - richdocuments
 - richdocumentscode
 - socialsharing_email
 - survey_client
 - user_ldap

```

**Comment by skjnldsv** [comment] 2020-10-25 14:17
We could add a confirm dialog, yes.
cc @jancborchardt ?

**Comment by ChristophWurst** [comment] 2023-05-22 07:55
@jancborchardt shall we add a confirmation dialogue?

**Comment by leegarrett** [comment] 2023-08-30 10:31
Any update on this? I find this bug quite big as the only sensible fix is to restore from backups.

**Comment by joshtrichards** [comment] 2024-01-14 22:53
Duplicate of #2788 
This is the original, but #2788 is where most of the votes are so let's consolidate there.

**Closed by joshtrichards** 2024-01-14 22:53 UTC
Labels: enhancement, 1. to develop
