### ISSUE TITLE
New phone entry key is in caps and has a quote left over

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/contacts#1454] opened 2020-02-01 17:50 UTC
Add a phone number to a contact in contacts app:

![Screenshot from 2020-02-01 18-36-36](https://user-images.githubusercontent.com/476060/73596452-7e656400-4522-11ea-918a-282f8b171e71.png)

Check the entry on another device (here iOS 9 Contacts):

![image (2)](https://user-images.githubusercontent.com/476060/73596504-cbe1d100-4522-11ea-83fb-317238be765e.png)

**Comment by skjnldsv** [comment] 2020-02-03 10:50
Duplicate of https://github.com/nextcloud/contacts/issues/1107#issuecomment-495111182

**Closed by skjnldsv** 2020-02-03 10:50 UTC
Labels: 0. Needs triage, bug
