### ISSUE TITLE
Inconsistent import/export of VCF files with mutlilines starting with double spaces

### ISSUE THREAD

**Issue by foliz** [nextcloud/contacts#184] opened 2017-04-05 11:57 UTC
### Steps to reproduce
1. Create  a contact entry in the nextcloud contact app with the following data:
- Name: anything, I used John Doe
- Groups: "Bernard Oliver Photographie", "Collaboration: MUA" and "Lead: Prospection réseaux sociaux"
- Notes: "Elle peut faire un essai gratuitement mais je pense qu'il faudra payer les produits.
Elle fait des notes d'honoraires car elle n'a pas d'entreprise"
2. Export this contact as a vcf file.
3. Import the exported file.

### Expected behaviour
The groups and notes should be the same.

### Actual behaviour
Some spaces were deleted during import. Group "Lead: Prospection réseaux sociaux" become "Lead: **Prospectionréseaux** sociaux". Notes "… payer les produits …" becomes "… **payerles** produits …"

Here is my exported vcf file:
```
BEGIN:VCARD
VERSION:3.0
UID:e7c3a550-19c4-4dd1-9efb-e78d4ec8a13c
N:Doe;John;;;
FN:John Doe
CATEGORIES:Bernard Oliver Photographie,Collaboration: MUA,Lead: Prospection
  réseaux sociaux
X-MOZILLA-HTML:FALSE
NOTE:Elle peut faire un essai gratuitement mais je pense qu'il faudra payer
  les produits.\nElle fait des notes d'honoraires car elle n'a pas d'entrep
 rise
REV:20170405T113322Z
END:VCARD
```
Notice the lines starting with double spaces. This were spaces get deleted on import.

### Server configuration
**Operating system:** Linux

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.1.0

**Nextcloud version:** 11.0.2

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** Updated from fresh install 11.0.0

**Signing status:**
```
No errors have been found.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by skjnldsv** [comment] 2018-10-02 10:00
Duplicate of #393

**Closed by skjnldsv** 2018-10-02 10:00 UTC
