### ISSUE TITLE
More Intuitive Property Management

### ISSUE THREAD

**Issue by tvollscw** [nextcloud/contacts#1751] opened 2020-08-20 15:46 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to add multiple phone numbers to a contact, but did not see a plus icon near the phone section.

**Describe alternatives you've considered**
I know that there is a 'Add new property' option that allows you to do this, but it doesn't seem intuitive for the end user who naturally looks within existing sections to add to said properties.

**Describe the solution you'd like**
Add a plus icon to existing properties/sections that are present within a given contact so that a end user can easily add to a section while managing a specific property/section.

**Comment by skjnldsv** [comment] 2020-08-21 06:23
Hey! Thanks for your interest :)
Duplicate of https://github.com/nextcloud/contacts/issues/655

**Closed by skjnldsv** 2020-08-21 06:23 UTC
Labels: 0. Needs triage, enhancement
