### ISSUE TITLE
Following a /f/ link to a vcard file directly imports it?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/contacts#2505] opened 2021-11-10 16:04 UTC
### Describe the bug
Just happened to @szaimen  and me

Contacts are automatically imported (or attempted to be imported)

**To Reproduce**
1. Share a vcard/vcf in talk, it shows like this:
![Bildschirmfoto von 2021-11-10 16-58-05](https://user-images.githubusercontent.com/213943/141147686-2a06fa34-067a-42b7-9421-2a9660ae7bd1.png)
2. When you click on the entry, Talk redirects the user to the files app:
`https://…/f/4528…`

**Expected behavior**
You see the file in the files app or something like that

**Actual behavior**
You see a "import finished" dialog:
![Bildschirmfoto von 2021-11-10 17-01-56](https://user-images.githubusercontent.com/213943/141148484-bb2dfad0-5630-46d6-a51b-bcb7610e0e9c.png)
Luckily it errored, but it is totally not intended to me that a f/ link to a vcf would directly import a contact to a "random" addressbook.

### Server configuration
c.nc.

**Comment by szaimen** [comment] 2021-11-10 16:06
I think this was a feature but maybe instead of directly importing it, it would be great if you would have the possibility to first select the contact book and then click on a button to start the import...

**Comment by miaulalala** [comment] 2021-11-11 08:04
@szaimen do you have a link to the PR that you suspect introduced this behaviour?

**Comment by szaimen** [comment] 2021-11-11 08:08
I think it was probably this one: https://github.com/nextcloud/contacts/pull/1688

**Comment by skjnldsv** [comment] 2021-11-11 08:11
And have a confirmation: "This will import XXX contacts into the XX addressbook, proceed ?"

**Comment by joshtrichards** [comment] 2024-01-15 00:25
Duplicate of #2788

**Closed by joshtrichards** 2024-01-15 00:25 UTC
Labels: enhancement, 1. to develop, feature: contacts
