### ISSUE TITLE
Fields in "Detailed name" are not cleared while changing to another contact

### ISSUE THREAD

**Issue by schoenbeck** [nextcloud/contacts#1811] opened 2020-09-26 21:32 UTC
### Steps to reproduce
1. Create new contact, add Field "Detailed name" 
2. Enter Firstname "Foo" and Surname "Bar"
3. Add another contact and add Field "Detailed Name" again

### Expected behaviour
Fields "Firstname and Surname should be empty

### Actual behaviour
Fields are filled with the data entered before ("Foo" "Bar")

### Server configuration
Operating system: Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64

Webserver: Apache/2.4.18 (Ubuntu) (apache2handler)

Database: mysql 10.0.38

PHP version:

7.4.9 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 19.0.3 - 19.0.3.1

Updated from an older Nextcloud/ownCloud or fresh install: Updated

Where did you install Nextcloud from: nexcloud.com
Signing status
Array ( )
List of activated apps
``` Enabled: - accessibility: 1.5.0 - activity: 2.12.0 - admin_audit: 1.9.0 - announcementcenter: 3.8.1 - audioplayer: 2.11.2 - bruteforcesettings: 2.0.1 - calendar: 2.0.4 - cloud_federation_api: 1.2.0 - comments: 1.9.0 - contacts: 3.3.0 - contactsinteraction: 1.0.0 - dav: 1.15.0 - federatedfilesharing: 1.9.0 - federation: 1.9.0 - files: 1.14.0 - files_accesscontrol: 1.9.1 - files_external: 1.10.0 - files_pdfviewer: 1.8.0 - files_rightclick: 0.16.0 - files_sharing: 1.11.0 - files_trashbin: 1.9.0 - files_versions: 1.12.0 - files_videoplayer: 1.8.0 - firstrunwizard: 2.8.0 - groupfolders: 7.0.0 - impersonate: 1.6.1 - issuetemplate: 0.7.0 - logreader: 2.4.0 - lookup_server_connector: 1.7.0 - mail: 1.4.1 - nextcloud_announcements: 1.8.0 - notes: 3.6.4 - notifications: 2.7.0 - oauth2: 1.7.0 - ocsms: 2.1.8 - password_policy: 1.9.1 - passwords: 2020.9.0 - photos: 1.1.0 - polls: 1.4.3 - privacy: 1.3.0 - provisioning_api: 1.9.0 - recommendations: 0.7.0 - richdocuments: 3.7.4 - serverinfo: 1.9.0 - settings: 1.1.0 - sharebymail: 1.9.0 - sharelisting: 0.3.0 - sharingpath: 0.2.5 - spreed: 9.0.4 - support: 1.2.1 - survey_client: 1.7.0 - systemtags: 1.9.0 - tasks: 0.13.3 - text: 3.0.1 - theming: 1.10.0 - twofactor_backupcodes: 1.8.0 - updatenotification: 1.9.0 - user_ldap: 1.9.0 - viewer: 1.3.0 - workflowengine: 2.1.0 Disabled: - bookmarks - circles - cms_pico - deck - documentserver_community - encryption - external - keeweb - onlyoffice - richdocumentscode ```
Configuration (config/config.php)
``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "cloud.wecode.de", "cloud.schoenbeck.org", "cloud.adtainment.de", "eb.grundschule-gaertnerplatz.de", "eb.kiga-baumstrasse.de", "10.10.50.44" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "overwrite.cli.url": "https:\/\/cloud.wecode.de", "dbtype": "mysql", "version": "19.0.3.1", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "logtimezone": "UTC", "installed": true, "maintenance": false, "loglevel": 2, "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory", "memcache.local": "\\OC\\Memcache\\APCu", "memcache.locking": "\\OC\\Memcache\\Redis", "redis": { "host": "***REMOVED SENSITIVE VALUE***", "port": 6379 }, "mail_smtpmode": "smtp", "mail_smtpauthtype": "LOGIN", "mail_smtpsecure": "tls", "mail_from_address": "***REMOVED SENSITIVE VALUE***", "mail_domain": "***REMOVED SENSITIVE VALUE***", "mail_smtpauth": 1, "mail_smtphost": "***REMOVED SENSITIVE VALUE***", "mail_smtpport": "25", "mail_smtpname": "***REMOVED SENSITIVE VALUE***", "mail_smtppassword": "***REMOVED SENSITIVE VALUE***", "updater.release.channel": "stable", "default_language": "de", "default_locale": "de_DE", "force_language": "de", "force_locale": "de_DE", "mysql.utf8mb4": true, "app_install_overwrite": [ "files_external_dropbox", "files_reader" ], "theme": "", "onlyoffice": { "verify_peer_off": true, "jwt_header": "AuthorizationJwt" } } ```

### Client configuration
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0

Operating system: Archlinux

**Comment by skjnldsv** [comment] 2020-09-30 12:29
Please try latest release 3.4.0 and try again.
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by schoenbeck** [comment] 2020-09-30 14:17
After upgrade it's still the same, I tried it in latest versions of Firefox (linux), Chrome (Linux) and Safari (MacOs).

**Comment by skjnldsv** [comment] 2020-09-30 17:33
Thanks for testing!

I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by joshtrichards** [comment] 2024-01-15 13:38
As it's been 4 years without receiving the necessary follow-up information to reproduce I'm closing this out.

I also cannot replicate this bug on either NC27 or NC28 today with Contacts v5.5.1.

**Closed by joshtrichards** 2024-01-15 13:38 UTC
Labels: bug, 0. to triage
