### ISSUE TITLE
Option to upgrade vcard versions on import or manually

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/contacts#273] opened 2017-07-28 04:18 UTC
Hi,
i exported my contacts (appr. 770) from my mobile (SAMSUNG GALAXY, Running ANDROID 6.01)
and tried to upload it into NC 12.0, with contacts app 1.5.3. However, I received the error message, that only vcard version 3 and 4 are supported. I am very much sure, that I am **not the only one**, who sufferers from this behavior. It would be very much advisable to incorporate an - automatic / selectable -  conversion option of the importing procedure form vcard versions lower then 3.0!

regards, hitam4450

**Comment by exploide** [comment] 2017-08-06 15:46
Got the same problem and just wished it could convert it automatically.

But, when investigating the error down in the vcf file, I noticed that the error happened due to lines like this:
```
BEGIN:VCARD
VERSION:4.0
 1
# valid properties continue here ...
```
I have no idea why the ` 1` lines are there, if this has semantic or if it is an failure made during export from owncloud. But removing these lines in the vcf file solved the issue and I was able to import it.

If this is really just garbage, converting it to a new version is probably not the solution. I would rather blame the export (in this case owncloud) but I don't know exactly what caused this.

**Comment by hitam4450** [comment] 2018-04-26 17:03
Any news - resp. progress to be reported on how to resolve this issue ??

**Comment by hitam4450** [comment] 2018-07-09 06:42
any progress of resolving this issue and implementing the result into the current version of contacts ??

**Comment by hitam4450** [comment] 2019-05-13 08:25
Any Schedule for implementation / release of this feature ???

**Comment by skjnldsv** [comment] 2019-05-13 08:40
Not really. Upgrading is not an easy task and can lead to data lost when not done properly.

**Comment by skjnldsv** [comment] 2020-09-06 14:52
Duplicate of https://github.com/nextcloud/contacts/issues/492

**Closed by skjnldsv** 2020-09-06 14:52 UTC
Labels: 1. to develop, enhancement
