### ISSUE TITLE
Import file selector not shown in Firefox

### ISSUE THREAD

**Issue by call-me-matt** [nextcloud/contacts#3503] opened 2023-07-06 20:40 UTC
### Describe the bug

When importing a contact, the file selection window is in the background of the settings window.

### Steps to reproduce

Open contacts app in firefox 114.0.1 (in chromium everything is fine), 
open the settings and import,
the file selection window is shown in the background.
[Screencast from 06.07.2023 22:27:21.webm](https://github.com/nextcloud/contacts/assets/34400929/03797bc1-d6c5-4d82-9a25-a976f4a27e11)

### Expected behavior

file selector is shown and not in the background of the settings modal

### Actual behavior

file selector is in the background of the settings modal and cannot be used

### Contact version

5.3.2

### Operating system

Podman (Docker)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by rahilarious** [comment] 2023-11-20 10:02
Just to add more info to this. 

This got solved after I created new addressbook (named temp) and then deleting it.

**Comment by joshtrichards** [comment] 2024-01-14 23:34
Unable to reproduce in Firefox 115.6.0 (ESR) with Contacts v5.5.0 so appears fixed. Closing, but feel free to follow-up if you're still seeing this.

**Closed by joshtrichards** 2024-01-14 23:34 UTC
Labels: bug, regression, feature: contacts, 0. Needs triage
