### ISSUE TITLE
Phonetic name support

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/contacts#251] opened 2017-06-30 12:23 UTC
~~Should we downstream https://github.com/owncloud/contacts/pull/595/files ?~~

Add new props (see https://github.com/nextcloud/contacts/issues/251#issuecomment-412543730) into the rfcProps model!

**Comment by MariusBluem** [comment] 2017-07-02 10:41
I see no reason why not 😅

**Comment by jancborchardt** [comment] 2017-07-04 15:32
Yes, everything should be downstreamed. Also cc @nextcloud/contacts and the original patch submitter @t-bucchi :)

**Comment by norbusan** [comment] 2017-07-27 15:38
Yes yes yes!!! Please. Living in Japan I am in dire need of phonetic name support. Thanks!

**Comment by t-bucchi** [comment] 2018-08-10 10:39
Hi, I'm a original patch submitter.
I want to merge this patch to nextcloud also.
Is there anything I can do for you?
Thanks.

**Comment by jancborchardt** [comment] 2018-08-13 14:40
@t-bucchi cool, welcome! :) You could either cherry-pick the commits with gits functionality, or manually apply the changes since maybe the code underneath changed meanwhile.

If you have any questions, @nextcloud/contacts can help you. :) You are also welcome in our chat channel at [#nextcloud-contacts](https://riot.im/app/#/room/#freenode_#nextcloud-contacts:matrix.org)! :tada:

**Comment by skjnldsv** [comment] 2018-08-13 14:45
@jancborchardt it could be great to add it into the 3.0 update, but the code is completely different.

I'd like to know a few informations @t-bucchi 
X-PHONETIC-FIRST-NAME is not an official prop, so before we go for it, I'd like to ve sure this is supported on other systems. Google is ok with this? What does it do on Android? iOS?

**Comment by t-bucchi** [comment] 2018-08-21 11:52
@jancborchardt Thanks for your reply. I will merge my patch to current master.

@skjnldsv Google Contacts on web, Android and iOS support X-PHONEIC-FIRST-NAME. I attached vCards are exported from iOS and Google Contacts. Could you confirm its?
[google.vcf.txt](https://github.com/nextcloud/contacts/files/2306097/google.vcf.txt)
[ios.vcf.txt](https://github.com/nextcloud/contacts/files/2306098/ios.vcf.txt)

And, my patch doesn't extend N field. It changes name order when generates full name from N field to display. Because, in Japan, we use "LAST-NAME FIRST-NAME" order generally.

**Comment by skjnldsv** [comment] 2018-08-21 11:55
@t-bucchi thanks for the feedback!
Android extend the n property, that's why I mentioned it :)

I'm ok with using the X-PHONETIC props. It looks like the proper way to do since the rfc allow us to do so. Let's try to add this in 3.0.0

**Comment by skjnldsv** [comment] 2018-08-22 06:26
@t-bucchi to merge?

**Comment by t-bucchi** [comment] 2018-08-22 10:58
@skjnldsv Ah, I mean rebase or adjust my patch to head of master branch. I don't need to do it?
I'm creating the environment to develop. Current nextcloud/contacts looks working on Nextcloud 14 beta only.
What the revision of nextcloud/server should I use? Is head OK?

**Comment by skjnldsv** [comment] 2018-08-22 11:37
We'll implement it in the 3.0 update. Your patch is not compatible. Don't worry we'll take care of it! 🤗

**Comment by t-bucchi** [comment] 2018-08-22 11:45
@skjnldsv Oh! Thanks! I'm looking forward to 3.0 update!

**Comment by norbusan** [comment] 2019-06-13 11:26
Is there any progress wrt to phonetic name support? There has been a patch, lots of updates, and at the end we are at NC16 and still without phonetic name support.

Could one of the devs please explain what the problem is? Thanks

**Comment by skjnldsv** [comment] 2019-06-13 11:30
@norbusan time is the problem.
Maybe you can do it? We'd be really happy to receive some help from motivated contributors like you! :)

**Comment by norbusan** [comment] 2019-06-13 12:22
@skjnldsv thanks, that is not very helpful. I am contributing to lots of projects (see my github), but these kind of remarks don't really invite contributors.

I checked the source now, it all seems to rely on ical.js, if I am not wrong. But some pointers could help people instead of pissing them off with these kind of remarks.

Thanks

**Comment by skjnldsv** [comment] 2019-06-13 12:35
> @skjnldsv thanks, that is not very helpful. I am contributing to lots of projects (see my github), but these kind of remarks don't really invite contributors.

How so? You seemed motivated on your message and willing to have this feature, so I assumed you could have helped us here?

Though now I'm really not fan of the tone of your last message.
You do realise we're all contributors and this is an open source project, right?
Anyone can work on an issue. And suddenly stating without a greeting "Hey lots of release later, you still did not do this, how so? Please explain the problem" will aaaabsolutely not motivate me to work on this.

I would have preferred something like
"Hello! Thanks for the latest releases. I see that this is still not part of the project. Could I do anything to help ? Thanks!"

There I would have even give you pointers! :wink: 
https://nextcloud.com/code-of-conduct/

**Comment by skjnldsv** [comment] 2019-06-13 13:04
I may be overreacting.
Sorry, I think I was hoping for a more encouraging message and yours depressed me a bit seeing that there was indeed a lot of time passed and still some nice pending features. :)

So please accept my apologies. Let's be productive here!

This requires a bit of work as you could simply add two independent input in the rfcprops.js file, but this is quite not the best ux/ui. Ideally we should add two more inputs into the N field, but the way our data structure is designed does not really allow a split between a single property (vue) and multiple properties (vcard).

**Comment by norbusan** [comment] 2019-06-14 04:08
Hi @skjnldsv 
thanks for your remarks about how to tackle the problem. I will take a look. I know my way around in angular, but you have switched to vue, which I don't know at all. 

Is there at least a general agreement on the vcard field naming? Reading the thread here I don't get the impression that going with `X-PHONETIC-FIRST-NAME` etc is accepted.

Thanks

Norbert

PS: nothing to worry about your comment, and I agree I could have been less pushy, sorry for that.

**Comment by skjnldsv** [comment] 2019-06-14 04:16
> Is there at least a general agreement on the vcard field naming? Reading the thread here I don't get the impression that going with `X-PHONETIC-FIRST-NAME` etc is accepted.

Any X- property is valid according to the rfc :)
It is not officially supported, but other systems like to create vcards standards (a bit like css webkit/moz prefixes before the official css releases)
So Google is usinga a dedicated property, but Davdroid created a consensus and matches the two automatically   https://www.davx5.com/manual/technical_information.html#name

Thanks!! :hugs:

**Comment by t-bucchi** [comment] 2020-08-09 00:34
Hi. I wrote [the new patch](https://github.com/t-bucchi/nextcloud-contacts/tree/feature/phonetic-3.3.0) for this issue based on v3.3.0 .
I want to send pull request.
But, the master looks changing rapidly (many marge).
So, it's difficult to test my patch based on master.
Should I wait until the merge is complete?

**Comment by skjnldsv** [comment] 2020-08-09 10:32
@t-bucchi open a pr, I'll help you get it merged even with master changes, don't worry :)
The two other big prs are #1687 and #1688, and it's still in need for some work, so we can try to merge yours before the two others ;)

**Comment by t-bucchi** [comment] 2020-08-09 11:00
@skjnldsv Thank you for your help!
I'll send pull request soon.
Thanks!!

**Closed** 2020-08-13 19:19 UTC
Labels: 1. to develop, enhancement, good first issue
