### ISSUE TITLE
Adresses do not show

### ISSUE THREAD

**Issue by sciurius** [nextcloud/contacts#1864] opened 2020-10-19 07:34 UTC
### Describe the bug
On the contacts page, addresses for entries are not shown.
......
......

**To Reproduce**
1. Select any contact
2. No address is shown

**Expected behavior**
The address should be shown

**Actual behavior**
See screenshot.

**Screenshots**
![scrot20201019083837](https://user-images.githubusercontent.com/1118804/96410009-86675000-11e6-11eb-9cab-f7e111ba7b23.png)

**Attachments**
Attached is the ics as downloaded from the contacts app. As you can see, the ADR information is there.
[889a7409-18fd-4737-bbb9-fe6e38ffd8d6.txt](https://github.com/nextcloud/contacts/files/5399569/889a7409-18fd-4737-bbb9-fe6e38ffd8d6.txt)

### Server configuration

**Operating system**: Linux (Raspbian 10)

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.3.14

**Nextcloud version:** 20.0.0

**Contacts version:** 3.4.0

**Updated from an older Nextcloud or fresh install:** Updated

**Browser:** Firefox 81.0.1

**Comment by skjnldsv** [comment] 2020-10-19 08:54
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by sciurius** [comment] 2020-10-19 09:04
Something like this?

````
GEThttps://cloud.squirrel.nl/apps/contacts/Not%20grouped/el2todnx-8bjs-d2xx-sltk-j81r60yumccu~addresses
[HTTP/2 200 OK 2174ms]

GEThttps://cloud.squirrel.nl/apps/user_status/img/app.svg?v=fa956741
[HTTP/2 304 Not Modified 1ms]

GEThttps://cloud.squirrel.nl/core/js/dist/main.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/core/js/dist/files_fileinfo.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/core/js/dist/files_client.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/js/core/merged-template-prepend.js?v=fa956741-0
[HTTP/2 200 OK 0ms]

GEThttps://cloud.squirrel.nl/core/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/accessibility/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/accessibility/js/accessibilityoca.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_pdfviewer/js/files_pdfviewer-public.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_sharing/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_sharing/js/dist/main.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_videoplayer/js/main.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/notifications/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/notifications/js/notifications-main.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/contacts/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/contacts/js/contacts-main.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_rightclick/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_rightclick/js/script.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files_rightclick/js/files.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/firstrunwizard/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/firstrunwizard/js/about.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/theming/l10n/en_GB.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/theming/js/theming.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/user_status/js/user-status-menu.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/core/js/dist/unified-search.js?v=fa956741-0
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/files/img/app.svg?v=fa956741
[HTTP/2 304 Not Modified 1ms]

GEThttps://cloud.squirrel.nl/apps/photos/img/app.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/activity/img/activity.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/contacts/img/app.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/calendar/img/calendar.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/tasks/img/tasks.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/notes/img/notes.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/settings/img/admin.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/settings/img/apps.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/firstrunwizard/img/info.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/settings/img/users.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/apps/settings/img/help.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/core/img/actions/logout.svg?v=fa956741
[HTTP/2 304 Not Modified 0ms]

GEThttps://cloud.squirrel.nl/avatar/jv/32?v=2
[HTTP/2 304 Not Modified 1910ms]

No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Notifications permissions granted App.vue:296
GEThttps://cloud.squirrel.nl/apps/notifications/img/notifications-new.svg

GEThttps://cloud.squirrel.nl/apps/notifications/img/notifications.svg
[HTTP/2 304 Not Modified 1ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
Initial state loaded defaultProfileState HOME rfcProps.js:39:8
Initial state loaded localesState 
Array(750) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
rfcProps.js:40:8
OCA.Search is deprecated. Please use the unified search API instead search.js:31:10
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 145 globals.js:60:15
GEThttps://cloud.squirrel.nl/core/img/favicon-touch.png
[HTTP/2 200 OK 0ms]

GEThttps://cloud.squirrel.nl/core/img/favicon.ico
[HTTP/2 200 OK 0ms]

[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, app: "unified-search", uid: "jv" }
ConsoleLogger.js:42:18
Connected to dav! 
Object { rootUrl: "https://cloud.squirrel.nl/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], publicCalendarHome: {…}, addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
Contacts.vue:472
String.prototype.toRgb is deprecated! It will be removed in Nextcloud 22. 8 placeholder.js:140:9
GEThttps://cloud.squirrel.nl/remote.php/dav/addressbooks/users/jv/addresses/dee32c9a-b7c1-4ef0-b30d-5653b0dbd95a.vcf?photo
[HTTP/2 304 Not Modified 238ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
String.prototype.toRgb is deprecated! It will be removed in Nextcloud 22. 2 placeholder.js:140:9
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:130:10
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 204 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
OC.requestToken changed lmGTqFFZSvy4uvgxotCtTp19OcVNszyNayumWvhL0Bk=:/yX9kBwXHtPx7ZJQm5jJIM0RVbMI6wnjElnDYsF5sUk= index.js:311:9
OC.requestToken changed oh8kzCTen/iFuglATdiFx3IYvBONbdtlpbZQyYn9QHo=:y1tK9GmQy9fM7WMhdJDhqSJ00GXINe4L3MQ18bDPISo= index.js:311:9
OC.requestToken changed HUEAO+2kcYuwwpfTYsjt9kYn49xh6+9QW3ioenMLkwU=:dAVuA6DqJaT5lf2yW4CJmBZLj6oks9o+IgrNQko58lU= index.js:311:9
OC.requestToken changed gJ/TP5h0J4+yXWawUAlRg6zBpLdkZxVX4Yc3WxCa/go=:6du9B9U6c6D7CgzRaUE17fytyMEhPyA5mPVSYymon1o= index.js:311:9
OC.requestToken changed qG0n0dQdpE/TaoKd9h/gSdSwajrrHso22d/Nxi+qlMo=:wSlJ6ZlT8GCaPej8z1eEJ4TcBkyuRv9YoK2o/haY9Zo= index.js:311:9
OC.requestToken changed nzdrZ1c8kHKZAaX7vO+nkNOXhaC/HjdGhuH9UvOOg1M=:9nMFXxpyxF3QVs+ahafD/oP76db6RgIo/5OYasq84gM= index.js:311:9
OC.requestToken changed LEm5gFbsF1kMmmiNSrjonNCt95xuSbFVRwIR4qI+MA4=:RQ3XuBuiQ3ZFzQLsc/CM8oDBm+orEYQ7PnB02psMUV4= index.js:311:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 24 globals.js:60:15
````

**Comment by skjnldsv** [comment] 2020-10-19 09:05
Yes :)
You opened the contact right?

**Comment by sciurius** [comment] 2020-10-19 09:09
I Control-R-ed the page.
Is there anything else I can do?

**Comment by sciurius** [comment] 2020-10-19 09:10
Did I mention that the problem is with *all* address entries?

**Comment by skjnldsv** [comment] 2020-10-19 09:58
I'll release a new version today that had some fixes, i'll let you try it and see if that solves it :)

**Comment by sciurius** [comment] 2020-10-19 11:00
Great, thank you!

**Comment by skjnldsv** [comment] 2020-10-20 19:37
Released! Please test 3.4.1 :)

**Comment by sciurius** [comment] 2020-10-20 19:56
Sorry, no change. Still no addresses :( .

**Comment by skjnldsv** [comment] 2020-10-20 20:09
> Sorry, no change. Still no addresses :( .

Thanks for the checks :)
Il investigate!

**Comment by call-me-matt** [comment] 2020-10-20 21:05
I have the same error. Fields where I can set the `type` vanish as soon as its not a value from the drop-down menu. Maybe that's the case here, too?
To reproduce, insert any text into a type field of address, telephone, social profile or likewise.
@sciurius do you see the address fields when you add a new one from the front-end?

**Comment by sciurius** [comment] 2020-10-21 06:13
If I use the contacts app to add a new contact I do get the address shown.

Looking at the VCF (Jane Doe shows an address, while Joe Doe doesn't) is it appears to me that the main difference is the use of attribute grouping (ITEM0.ADR versus ADR).

[jane.vcf.txt](https://github.com/nextcloud/contacts/files/5413623/jane.vcf.txt)
[joe.vcf.txt](https://github.com/nextcloud/contacts/files/5413624/joe.vcf.txt)

**Comment by sciurius** [comment] 2020-10-25 18:49
A contacts app that doesn't show addresses is **severly** crippled (a.k.a. useless).
Please raise the priority on this issue.

**Comment by skjnldsv** [comment] 2020-10-25 19:12
Ah no, duplicate of https://github.com/nextcloud/contacts/issues/1842

**Closed by skjnldsv** 2020-10-25 19:12 UTC
Labels: 1. to develop, bug, high, regression

**Comment by MiFiWe** [comment] 2021-02-05 19:32
I’m a newbie on Nextcloud but experienced the same problem. iPhone, iPad and Mac (all latest software 2021) showing same data, which can be successfully changed, but any Browser (Safari, Chrome, Internet Explorer) does not show addresses. If the address fields are added manually, it’ll be shown on a iOS device as additional address fields. Once the additional addresses are changed or altered, the address are not shown at all on a internet browser.
Would be great if someone can fix that.

**Comment by Sailing74** [comment] 2021-03-11 11:40
I have the same error since updating from Nextcloud 19 to Nextcloud 20.0.8. Anything I can do to help find the problem and fix it?

**Comment by sciurius** [comment] 2021-03-11 12:29
See issue #1842.
