### ISSUE TITLE
Search only finds first group of a contact

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#1145] opened 2019-06-17 11:59 UTC
### Describe the bug
When a contact is assigned to several groups, the search for groups only finds the contact when searching for the first group selected in this contact.
When searching for the other group names, the contact does not show up in the search results.

**To Reproduce**
1. assign a contact to group "Group-A"
2. assign the same contact to group "Group-B"
3. search for "Group-A" -> the contact is in the results
4. search for "Group-B" -> The contact is not in the results.

**Expected behavior**
When searching for a group name, all contacts of the group should show up. Not only contacts where this group was first selected.

**Web server:** Apache

**Database:**  MySQL and PostgreSQL

**PHP version:** 7.2.2 and 7.1.30

**Nextcloud version:** 16.0.1.1

**Contacts version:** 3.1.3

**Updated from an older Nextcloud or fresh install:** updated

### Client configuration
**Browser:**
Firefox and Chrome

**Operating system:**
Windows 10 64bit

**Comment by tdoerschel** [comment] 2020-05-07 12:55
Just saying that bug is still present in latest server 18.0.4 and contacts app 3.3.0

**Comment by tdoerschel** [comment] 2020-10-20 09:37
Just updating: Bug still present in
contacts 3.4.0 with NC server 20.0.1

**Comment by skjnldsv** [comment] 2020-10-20 09:44
@tdoerschel the issue is still opened, so yep, not fixed :(

**Comment by tdoerschel** [comment] 2020-11-11 15:01
Hi,
bug still exists in contacts 3.4.1 on server 19.0.4

However, the unified search in NC 20 does not search contact groups at all (also app v. 3.4.1)

**Comment by alexanderdd** [comment] 2020-11-18 17:57
duplicate of https://github.com/nextcloud/contacts/issues/534 ?

**Closed** 2020-11-18 20:23 UTC
Labels: 1. to develop, bug
