### ISSUE TITLE
REQUEST: Option to select what Address Books to View/Hide

### ISSUE THREAD

**Issue by serbik** [nextcloud/contacts#401] opened 2017-10-19 18:33 UTC
I think it would be a nice feature to be able to choose which address books to show and hide.

1. A system similar to the Calendar app, where you can toggle the calendar's colour on and off to show/hide that particular calendar.
2. Add a Address Book section to the sidebar under the groups section (or inside the Settings pullup menu)

**Comment by Henni** [comment] 2017-10-25 21:29
duplicate of https://github.com/nextcloud/contacts/issues/36
such a address book section already exists in the settings, but it doesn't support hiding addressbooks yet.

**Closed by Henni** 2017-10-25 21:29 UTC
