### ISSUE TITLE
Sharing all contacts from a contact groups

### ISSUE THREAD

**Issue by mysap01** [nextcloud/contacts#967] opened 2019-03-03 13:32 UTC
Hi contributers
We often need nexcloud for colabration. Just only one is a gap:
We have nearly 1000 contacts in different groups, built in ms-outlook and imported once in nextcloud. Then, we create a couple of collective-users in the nextcloud. Now, we will share contacts with the nextcloud-users, so that the user get all contacts from each existing contacts-group.
For example: 12 of the 1000 contacts are "publisher", grouped togehter as contact-group "Publisher". All of this 12 fellows should have the contact-informations from the other ones, safed in a single place. 
At the moment, sharing of contacts are only possible with adressbooks, and addional contacts is only possible assign to one adressbook. And but not least, do assign 1000 contacts to adressbooks.
Would be possible contacts-groups to share or could contact-groups assign to multiple adressbook's, it would be fantastic and simple.
Thanks a lot....

**Comment by skjnldsv** [comment] 2019-03-03 18:09
Duplicate of #213 and partly #111

**Closed by skjnldsv** 2019-03-03 18:09 UTC
Labels: enhancement

**Comment by mysap01** [comment] 2019-03-04 19:31
Dear skjnldsv
I don't think, your assign to other issues are not the same, how i meen:
#213 is for sync with Mac or MS-Outlook --> We will not sync, we will share in nextcloud with different nextcloud-users
#111 is different --> How can i share a single contacts with different nextcloud-user-groups? At the moment, contact-groups would be the simplest way, or we could assign the contact to multiple addressbook's, how it's possible like contact-groups.
Best regards......

**Comment by skjnldsv** [comment] 2019-03-04 21:22
Hello, Let me explain a bit further.
For nextcloud t be able to share a group, the group must exists as an entity.  Currently the group is just a value inside a contact. It needs to be outsourced and have its own entity, the same thing that macOS vcard group does. Once we moved to that, it will be possible to share this *special* vcard.

But to be able to share a single vcard (aka our group), we need #111 :)
