### ISSUE TITLE
In contactlist contact icons are not shown

### ISSUE THREAD

**Issue by leinec** [nextcloud/contacts#715] opened 2018-11-12 21:18 UTC
When browsing the contact list in the web interface then no contact icons/avatars are shown by default.

When I click on a contact, then the contact is loaded in the "main" window at the right including contact icon. After that the icon for this single contact will also be shown in the contact list on the left side.
If I select another contact lateron the icon remains in the list.

**To Reproduce**
1. Open the contacts app. No contact icon will be displayed.
2. Click on various contacts to show their details. After that all contact icons of these contacts will be displayed in the list
3. Reload the page by pressing F5. All the contacts icons disappear again.

**Expected behavior**
The expected behaviour would be, that by loading the contact app, all contact icons for the list will beloaded and displayed.

**Actual behavior**
Contact icons are only shown, if the contact has been opened before

**Screenshots**

### Server configuration
**Operating system**: Linux

**Web server:** Nginx...

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 14.0.3

**Contacts version:** 2.1.6

**Updated from an older Nextcloud or fresh install:** fresh

**List of activated apps:**
various

### Client configuration
**Browser:** Vivaldi & Firefox (same behaviour in both)

**Operating system:** Windows 10

**Comment by skjnldsv** [comment] 2018-11-12 21:30
Duplicate of #215

**Comment by leinec** [comment] 2018-11-12 21:31
Quickly stepping over the issues GitMate.io has found I think none is related to my issue reported :-(

**Closed by skjnldsv** 2018-11-12 21:30 UTC

**Comment by skjnldsv** [comment] 2018-11-12 21:34
https://github.com/nextcloud/contacts/issues/581 should be :)
This is a feature/bug, planned to be better handled later, but not yet
