### ISSUE TITLE
After editing a contact file: ALL selected groups are deleted from the assignment

### ISSUE THREAD

**Issue by Der-K-2000** [nextcloud/contacts#3563] opened 2023-08-14 10:35 UTC
### Steps to reproduce

1. Open a person's contact
2. Choose group(s)
3. Selection of new groups is shown
4. Save contact item

### Expected behavior

New Groups will be saved.

### Actual behaviour

Every (!) selected group is deleted from the assignment.

### Calendar app version

5.4.0-beta.1

### Browser

Firefox 116.0.2

### Client operating system

Windows

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.0 beta 1

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by alphasixtyfive** [comment] 2023-09-15 08:42
Confirm observing same behavior after today's update to version 5.4.0

**Comment by pkampkam** [comment] 2023-09-15 09:16
Confirm the bug. Clarification: editing a contact removes it from all groups. You do not need to alter selection of groups. Even editing the phone number makes the contact disappear (unassigned) from all the groups. This is serious issue.

**Comment by ChristophWurst** [comment] 2023-09-15 09:26
Is this the same problem as https://github.com/nextcloud/contacts/issues/3516? Then there is a pending PR: https://github.com/nextcloud/contacts/pull/3605

**Comment by ChristophWurst** [comment] 2023-09-16 12:17
@alphasixtyfive @Der-K-2000 might want to check out #3605 nevertheless because it fixes the bug for me. I'm not able to create contacts with groups on `main` but it works on the PR's branch.

**Comment by alphasixtyfive** [comment] 2023-09-18 07:56
I can't really make a patch out of it I presume. I hope PR will be merged soon and an update released as a few people are desperate to get groups working again.

**Comment by alphasixtyfive** [comment] 2023-09-20 15:45
After today's update 5.4.1 I'm now able to select the group while creating or editing the contact however if I edit anything other than groups, all groups of that contact get deleted.

**Comment by alphasixtyfive** [comment] 2023-09-22 08:03
@ChristophWurst May we please have this looked at?

**Comment by ChristophWurst** [comment] 2023-09-22 15:11
This bug needs a page reload to be reproducible. The bug has just been fixed by https://github.com/nextcloud/contacts/pull/3628.

**Closed by ChristophWurst** 2023-09-22 15:11 UTC
Labels: bug

**Comment by alphasixtyfive** [comment] 2023-09-23 07:20
Thank you guys! 5.4.2 fixed it!
