### ISSUE TITLE
possibility to add custom instant messaging types

### ISSUE THREAD

**Issue by kromuchi** [nextcloud/contacts#672] opened 2018-10-21 20:00 UTC
Currently, I see the following dropdown values for the instant messaging type:
- IRC
- KiK
- Skype
- Telegram
- XMPP

There are quite a few more messengers that are maybe not that popular - or have only a geographically limited popularity. These messengers (like Threema) could be somehow added to that list, but eventually they loose relevance again (I saw an older discussion here about removing ICQ from that list...).

**Would it be possible to add user-specific instant messaging types?** Maybe in the configuration settings of the contact apps (or - not preferred but also acceptable - as free-text input on the editing contacts page). Then the user does not need to ask about adding his special/unpopular messenger to the global textlist of the app (and wait for the next release) or has to hope that his messenger won't be removed in the future.

**Comment by kromuchi** [comment] 2018-10-21 20:01
(the same could be implemented for social networks, too)

**Comment by skjnldsv** [comment] 2018-10-22 07:14
@kromuchi Hello! :)
yes, we could add a custom entry. BUT that won't mean it's fully compatible with other vcards reader.
Basically it's a duplicate of #27 ;)

**Comment by skjnldsv** [comment] 2018-10-22 07:14
@kromuchi Hello! :)
yes, we could add a custom entry. BUT that won't mean it's fully compatible with other vcards reader.
Basically it's a duplicate of #27 ;)

**Closed by skjnldsv** 2018-10-22 07:14 UTC
Labels: duplicate

**Comment by skjnldsv** [comment] 2018-10-22 08:00
@kromuchi Hello! :)
yes, we could add a custom entry. BUT that won't mean it's fully compatible with other vcards reader.
Basically it's a duplicate of #27 ;)

**Comment by mojoaxel** [comment] 2019-02-03 09:56
This needs to be extendable!
https://github.com/nextcloud/contacts/blob/91c02d87556b8cfc40431688384fabee33308dc2/src/models/rfcProps.js#L155-L160

**Comment by Tux12Fun** [comment] 2019-06-17 22:37
I would also like to see this Feature and it would be nice if there wouldn't be forced to enter a Web URL

My Favourite would be Threema
