### ISSUE TITLE
It's not possible to delete a field 'nickname'

### ISSUE THREAD

**Issue by BFallert** [nextcloud/contacts#858] opened 2019-01-14 13:39 UTC
### It's not possible to delete a field 'nickname'

Some of my contacts have a nickname. Some of them are imports from an e-mail account, so in this field they have nonsense (such as repeating the name).
Yesterday I wanted to clean up my contacts and removed all nicknames without meaningful content.
Then I realized that the nickname field was not deleted at all. So I check it several times, but always the same result.

A workaround for me was to empty the field. A delete was not possible then.

A second workaround is when i delete the nickname at my smartphone in the contacts app.

**To Reproduce**
1. Start browser
2. open local nextcloud (https://XXXX/nextcloud/apps/contacts/
3. Add 'nickname' to a test contact
4. Click on 'delete-icon' behind the 'nickname' field
5. 'nickname' is deleted
6. Select a other contact
7. Back to your test contact
8. 'nickname' is there again

**Expected behavior**
'nickname" should be deleted from the database. 

**Actual behavior**
'nickname' is not deleted in the database, but only from the current mask, after a renewed call the contact with the 'nickname' is the field again.

### Server configuration
**Operating system**:  Linux, Raspberry Pi

**Web server:** Apache

**Database:** 
Art: mysql
Version: 10.1.37
Größe: 12,8 MB

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.2

**Contacts version:** 3.0.1

**Updated from an older Nextcloud or fresh install:** Updated from older Version 13 then 14 then 15.0.1RC, now 15.0.2 
Problem is in 15.0.1RC and 15.0.2

**Signing status:**
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.1
  - dropit: 0.1.3
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_mindmap: 0.0.11
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - external
  - ocsms
  - quota_warning
  - user_external
  - user_ldap

**Nextcloud configuration:**
root@raspberrypi:/var/www/html/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.40",
            "berndsandhausen.feste-ip.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/berndsandhausen.feste-ip.net\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** Windows10, Linux, Windows7

**CardDAV-clients:** 
Error is only in Web-Version

**Comment by skjnldsv** [comment] 2019-01-15 14:42
Duplicate of #857

**Closed by skjnldsv** 2019-01-15 14:42 UTC
Labels: bug
