### ISSUE TITLE
Narrow Width of the Contacts List

### ISSUE THREAD

**Issue by drfho** [nextcloud/contacts#483] opened 2018-02-14 15:10 UTC
Hello,
after updating the contacts list from 2.0.1 to 2.1.0 a CSS problem with the contacts list occured; it is relevant in latest Chrome/Edge, but not this severe in Firefox:

**Problem**
![list1](https://user-images.githubusercontent.com/29705216/36210996-388bb61c-11a0-11e8-8e78-0b25e8f5527e.gif)

**Solution**
The problem can be corrected by removing the overflow-styling for _.app-content-detail_
[_contactlist.scss#L83](https://github.com/nextcloud/contacts/blob/master/css/_contactlist.scss#L83)

![list2](https://user-images.githubusercontent.com/29705216/36211065-7264f51a-11a0-11e8-9afb-1f102e3c8a9d.gif)

### Steps to reproduce
Call contact entry GUI

### Expected behaviour
List of contacts should be readable ...

### Actual behaviour
... but it is shrinked to a very narrow width

### Server configuration
Nextcloud 12, Contacts-App 2.1

_Many thanks for a great plugin_
drfho

**Comment by skjnldsv** [comment] 2018-02-14 15:12
Duplicate of #453

**Closed by skjnldsv** 2018-02-14 15:12 UTC
