### ISSUE TITLE
Broken image display for address book contacts in drop down menu

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/contacts#3078] opened 2022-10-23 12:47 UTC
### Describe the bug

I notized this issue after upgrading from Nextcloud 24 to Nextcloud 25, but maybe this also happens with Nextcloud 24:

When opening the contact menu, images for contacts who don't have an image show as "broken image" and not using the initials as placolder. In the following screenshot the "C" and "D" are users in Nextcloud. All other entries are just address book contacts without image

![image](https://user-images.githubusercontent.com/6613614/197392620-3ebc2f19-8bc3-4ce2-90af-e5d77b537873.png)

The reason for this is, that the respective image URLs (e.g. https://myserver.example/avatar/a5db8598-935c-4935-8ac7-02d89f1226e6/64&size=64) result in 404 errors.

### Steps to reproduce

1. Make sure that the Contacts app is installed and active
2. Create some address book entries without image
3. Click on the "contacts" icon on the top right corner to display the contact drop down menu

### Expected behavior

Address book contacts without image show a placholder similar to user entries based on the first and last name.

### Actual behavior

A "broken image" is displayed since the image URL responds with a 404 error.

### Contact version

5.0.1

### Operating system

Ubuntu Linux 20.04.5 LTS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by plutocrat** [comment] 2022-10-25 04:58
Can confirm. No contact images displaying anywhere in Nextcloud web app. Not in dropdown, not in contacts app. 
Identical synced contacts display fine in Thunderbird / Cardbook. 
PHP 8.0, Nextcloud versions 24 and also 25. Ubuntu 20.04. Was previously working but I don't use the web interface much, so couldn't say exactly when it broke.

**Comment by nicokaiser** [comment] 2022-11-03 20:03
In the contact app, the 404 errors are also present (seems like the app makes HTTP request for each and every contact to check if there is an image), but a placeholder image is displayed correctly. 
This is broken in the dropdown menu.

**Comment by arnowelzel** [comment] 2022-11-05 11:25
Well - generating dozens or hundreds of requests which end in 404 errors is not a good design. If the contact app wants to load an image for a contact, then this should either be the stored image or a generated placeholder similar to how it is done for users. But the way how this seems to be implemented at the moment is really not very good.

Having many 404 errors also triggers alerts in the server monitoring and it is hard to see if there is a real problem with the server or just the odd behaviour of the contacts app.

**Comment by SKB-CGN** [comment] 2022-11-15 09:35
Same problem here. Even `https://server.com/apps/contacts/css/icons.css?v=19bbdecf-15](https://cloud.kreyenborg.koeln/apps/contacts/css/icons.css?v=19bbdecf-15)" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).`

**Comment by dneuhaeuser** [comment] 2022-11-21 17:25
I also have this problem with contacts of federated servers.

![image](https://user-images.githubusercontent.com/11788579/203120188-016a4bba-57af-410b-9d8d-1d0ba5fca15e.png)

The avatar is trying to load from my local nextcloud installation instead of the federated installation:
`https://cloud.myserver.de/index.php/avatar/christian......./64&size=32`

should be:
`https://cloud.myfederation.de/index.php/avatar/christian......./64&size=32`

**Comment by plutocrat** [comment] 2022-11-25 04:14
Just tried something new: Found a contact without an image in the NC web interface. Added Image, which didn't display anywhere in contacts app or dropdown. Synched contact to phone and email client, where the image displays correctly.  

Lots of errors in this format as previously stated. 
https://myserver.example/avatar/a5db8598-935c-4935-8ac7-02d89f1226e6/64&size=64

**Comment by summersab** [comment] 2022-12-04 02:02
I can confirm that this is a bug. I just spun up a fresh instance of NC with a SQLite DB, and any new contact has a broken image while users have the default avatars with their initials. While tracing the code, I actually think that this issue has to do with the core user libraries. The failure occurs here:
https://github.com/nextcloud/server/blob/ec5cbdeb7ffb87c0169c39e6f44846e819b41f14/lib/private/Avatar/AvatarManager.php#L114

I'm going to open an issue in the server repo referencing this.

**Comment by arnowelzel** [comment] 2022-12-04 02:04
> I can confirm that this is a bug. I just spun up a fresh instance of NC with a SQLite DB, and any new contact has a broken image while users have the default avatars with their initials. While tracing the code, I actually think that this issue has to do with the core user libraries. The failure occurs here: https://github.com/nextcloud/server/blob/ec5cbdeb7ffb87c0169c39e6f44846e819b41f14/lib/private/Avatar/AvatarManager.php#L114
> 
> I'm going to open an issue in the server repo referencing this.

Thanks for that finding! With this information it should not be too hard to fix this.

**Comment by summersab** [comment] 2022-12-04 22:41
I submitted a PR to hopefully fix the issue. Until then, here is a very simple app that solves the problem temporarily:
https://github.com/nunimbus/contacts_avatar_patch

**Comment by arnowelzel** [comment] 2022-12-04 22:48
> I submitted a PR to hopefully fix the issue. Until then, here is a very simple app that solves the problem temporarily: https://github.com/nunimbus/contacts_avatar_patch

Thanks a lot! The patch app works fine here to mitigate the problem until the PR is merged and and update is published.

**Comment by summersab** [comment] 2022-12-04 22:57
Glad I could help! I thought the issue had to do with my highly-customized setup, and I spent hours digging into my personal code. It really didn't occur to me that it could be an issue with the core NC libraries. At least there was a simple workaround.

**Comment by summersab** [comment] 2022-12-05 19:59
@arnowelzel I pushed an update to my app. It was throwing errors on a foreach loop because I didn't think I needed to validate that an element is an array. It works without the update, but this will keep your logs quiet.

**Comment by arnowelzel** [comment] 2022-12-05 20:42
> @arnowelzel I pushed an update to my app. It was throwing errors on a foreach loop because I didn't think I needed to validate that an element is an array. It works without the update, but this will keep your logs quiet.

Thanks for the update, works fine :-)

**Comment by plutocrat** [comment] 2022-12-09 09:16
Broken image problem now fixed with the patch, but contacts which have images in the vcard are still not displaying it. So in both contact app and the quick contact find box, top right, all you can see are the contact initials.

**Comment by SKB-CGN** [comment] 2022-12-09 21:13
Problem still persistent with new NC 23.0.2

**Comment by arnowelzel** [comment] 2022-12-10 10:36
> Broken image problem now fixed with the patch, but contacts which have images in the vcard are still not displaying it. So in both contact app and the quick contact find box, top right, all you can see are the contact initials. If you export a contact with an image, the base64 encoded image is correctly displayed in the vcf file. VCF version is 3.0 though, whereas original was 4.0. Don't know if that has any effect.

The problem is, that the contact drop down menu does not load any avatar images from contacts at all. The patch app only make sure, that this will not result in 404 errors but instead at least placeholders will be used. For me this is ok, since the regular contact list itself works fine though.

Drop down list with a search - the "AA" entry is a contact which has an image but it is not used in the drop down:

![image](https://user-images.githubusercontent.com/6613614/206850784-701cfc27-de31-4668-8573-c2cc39e550a4.png)

Contacts app with the same contact - here the image is used:

![image](https://user-images.githubusercontent.com/6613614/206850856-3addb8eb-142a-425b-a862-1e7252925de0.png)

**Comment by summersab** [comment] 2022-12-12 05:10
Hmm... I didn't realize that the app was supposed to grab custom avatars for those contacts who are stored in the address book (vCard/DAV contacts). That makes sense, though. I'll give that a look this week to hopefully update my patch and find the root cause in the NC code.

**Comment by arnowelzel** [comment] 2022-12-31 17:50
Unfortunately the patch app breaks the user profile page in the latest NC version. Also see https://github.com/nunimbus/contacts_avatar_patch/issues/1

Hopefully the original issue gets fixed so the "patch" is not needed any longer.

**Comment by plutocrat** [comment] 2023-02-04 06:54
Issue still present after update to Contacts 5.1 today.

**Comment by SKB-CGN** [comment] 2023-02-04 08:57
Correct and confirmed after update today.

Inside the app, the pictures are shown - only the quicksearch does not display the pictures.

**Comment by flurmind** [comment] 2023-02-04 09:58
Confirmed!

**Comment by user592965** [comment] 2023-02-08 18:49
Same problem here with Contacts 5.1 and NC 25.0.3

**Comment by SKB-CGN** [comment] 2023-02-17 11:56
I just installed the new 26.0.0 beta 4 and enabled the contacts app, which is now marked as "untested app".

What shall i say?

Contacts are working as you can see in the image:

![2023-02-17 12_55_16-Window](https://user-images.githubusercontent.com/58603329/219647657-05b5e177-40a1-4420-b070-054c58895e76.png)

**Comment by Ravinou** [comment] 2023-02-25 18:08
![image](https://user-images.githubusercontent.com/39600829/221372781-0b492f06-eaeb-42a8-8241-f300dbd5df49.png)

Same with Nextcloud 25.0.4 + contacts 5.1.0

**Comment by summersab** [comment] 2023-02-26 03:53
I haven't kept up - been busy with other stuff. Has anyone tried with NC 26 beta? I might try to look at it soon, but no promises.

**Comment by ChristophWurst** [comment] 2023-05-22 08:12
I don't know the issue/PR but I think this has been addressed recently. Could someone check?

**Comment by dhelonious** [comment] 2023-05-22 15:46
@ChristophWurst You're correct, this was fixed in nextcloud/server#36735.

**Closed** 2023-05-22 16:00 UTC
Labels: bug, feature: contacts, 0. Needs triage
