### ISSUE TITLE
Does not work in Edge or IE

### ISSUE THREAD

**Issue by rollanders** [nextcloud/contacts#1141] opened 2019-06-15 09:56 UTC
Please see nextcloud/server#15957
In Edge and IE I can only use Files. No other app is working. Have tried it on the demo-site to0. Same result.

**Comment by skjnldsv** [comment] 2019-06-16 12:18
Hello! :)
As stated in the readme: 

> This app is compatible with the same browsers as server except IE!

Sorry!:(

**Comment by rollanders** [comment] 2019-06-16 15:21
Sorry John
Open Edge browser. Go to https://demo.nextcloud.com/ Log in as admin admin.  Downolad and activate the Contacts app.  Try to open it - you will get spinning wheel. 

The same apply to other apps as well. Beside the Contacts app I have tried E-mail and Calendar with same result. 

Do this before you close the report. Report back if you get another result. I have tried on 2 computers with same result. And I get the same result on other installations as well.

**Comment by skjnldsv** [comment] 2019-06-16 15:30
Ah sorry, you also specified edge. What version of edge? :)

**Comment by skjnldsv** [comment] 2019-06-16 15:32
Ok, app is working fine. But opening is only working on the text and not the app icon on the top app menu.
This is a duplicate of https://github.com/nextcloud/server/issues/15887

**Closed by skjnldsv** 2019-06-16 15:32 UTC
Labels: 0. Needs triage, bug

**Comment by rollanders** [comment] 2019-06-16 18:29
OK - You are right. It works If i click on the text
