### ISSUE TITLE
Feature request: "add one more" property

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1213] opened 2019-08-15 09:53 UTC
**Is your feature request related to a problem? Please describe.**
I want to add e.g. five email addresses to a contact. Now, I have to scroll down every time, click on "add property" and select the email property in menu. That is not very intuitive.

**Describe the solution you'd like**
A "plus" button to each caption of properties (e.g. "email", "addresses", etc.) whould be great that simply does: "add one more" (of this type of property).

**Describe alternatives you've considered**
This isn't a defect but a usability improvement.

**Additional context**
![kontakte](https://user-images.githubusercontent.com/11940089/63087772-43ab4780-bf53-11e9-8653-37d4d505cc94.png)

**Comment by skjnldsv** [comment] 2019-08-15 14:38
Duplicate of https://github.com/nextcloud/contacts/issues/655

**Closed by skjnldsv** 2019-08-15 14:38 UTC
Labels: 0. Needs triage, enhancement
