### ISSUE TITLE
Dynamic positioning of fields makes you search for them

### ISSUE THREAD

**Issue by unix0r** [nextcloud/contacts#1273] opened 2019-09-25 12:34 UTC
**Is your feature request related to a problem? Please describe.**
I edit my contacts through the web app of nextcloud contacts, but editing the contacts is really annoying.
That's because of the dynamic positions of the information fields. For example the birthday field is for one
contact on the right side, but for another contacts it's on the left side.
Try to fill a couple information to your contacts and you're spending more time to find those fields than to insert new information.

**Describe the solution you'd like**
I would like to have a specified order of the fields so i always know the exact position of a field to put information in.

**Describe alternatives you've considered**
As an alternative i just edit my contacts through other apps and the carddav interface.

**Additional context**
See the screenshots:
![Bildschirmfoto von 2019-09-25 14-27-26](https://user-images.githubusercontent.com/4679329/65600829-31d0b180-dfa1-11e9-88ce-75daf74bbf8b.png)
![Bildschirmfoto von 2019-09-25 14-27-43](https://user-images.githubusercontent.com/4679329/65600835-34330b80-dfa1-11e9-9e9e-06e171147099.png)

**Comment by skjnldsv** [comment] 2019-09-25 12:36
Duplicate of #654

**Closed by skjnldsv** 2019-09-25 12:36 UTC
Labels: 0. Needs triage, enhancement
