### ISSUE TITLE
No "remove double", "remove all" or "Select contacts" option

### ISSUE THREAD

**Issue by pinq-** [nextcloud/contacts#456] opened 2018-01-09 15:05 UTC
### Steps to reproduce
1. Have many double contacts 
2. Have to remove them one by one
3. Can't remove all and import then again

### Expected behaviour
Have future called "remove doubles", "Remove all" or select certain contacts and remove them. 

### Actual behaviour
have to remove contacts one by one. 

### Server configuration

**Operating system**:Debian GNU/Linux 8 

**Web server:**dunno

**Database:** MySQL 

**PHP version:** PHP Version 5.6

**Nextcloud version:** 12.0.4

**Contacts version:** 2.0.1

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:**
No errors have been found.

List of activated apps:

no access( no sudo access)

Nextcloud configuration:
recular or no access( no sudo access)

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** Webdav

**Comment by skjnldsv** [comment] 2018-01-09 16:20
This is a duplicate of multiple issues: 
Select multiple contacts: #277 
And merge duplicates: #70

**Closed** 2018-01-09 16:20 UTC
Labels: duplicate
