### ISSUE TITLE
Removing fields (e.g. phone number or e-mail address) does not work

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/contacts#865] opened 2019-01-16 10:57 UTC
### Describe the bug
  Removing of fields (e.g. a phone number) seems to work in the first place, but when changing the contact and coming back, the fields are there again.

**To Reproduce**
Edit a contact which has two phone numbers and remove one of them by clicking on the trash can at the right of the field.

**Expected behavior**
The field gets removed not only from the mask, but also the data of the property gets deleted from the vcard.

**Actual behavior**
The field gets removed - but only in the mask.
After switching to another contact and coming back to that, the field and its content is there again.

**Operating system**:
  Server: Linux (Debian, Shared Hoster)
  Client: Windows 10

**Web server:** Apache

**Database:** MariaDB 5.7

**PHP version:** 7.2

**Nextcloud version:** 15.0.2

**Contacts version:** 3.0.1

**Updated from an older Nextcloud or fresh install:** Update from latest V14

**List of activated apps:**
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.0
  - apporder: 0.6.0
  - audioplayer: 2.5.1
  - bookmarks: 0.15.1
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - flowupload: 0.0.9
  - gallery: 18.2.0
  - gpxpod: 3.0.1
  - groupfolders: 2.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - polls: 0.9.5
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_usage_report: 1.1.1
  - workflowengine: 1.5.0

**Nextcloud configuration:**
`{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
       "activity_expire_days": "60",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "filelocking.debug": false,
        "filelocking.enabled": true,
        "filelocking.ttl": 1800,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "version": "15.0.2.0",
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "integrity.check.disabled": true,
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 20971520,
        "skeletondirectory": "\/home\/www\/nextcloud_data\/skeleton",
        "updatechecker": true,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "disabled",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "singleuser": false,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "updater.release.channel": "stable",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}`

### Client configuration
**Browser:** Firefox 64.0, 64-Bit

**Operating system:**

Windows 10 - Pro

### Logs

I don't see any log when I click at the trash bin symbol - neither in console log nor in network traffic nor in nextcloud.log!

**Comment by skjnldsv** [comment] 2019-01-16 11:18
Duplicate of #857

**Closed by skjnldsv** 2019-01-16 11:18 UTC
Labels: bug

**Comment by Bodenseematze** [comment] 2019-01-16 11:20
Sorry for the duplicate.
I searched before adding the new issue  - but it seems I did not search good enough :-(

**Comment by skjnldsv** [comment] 2019-01-16 11:51
@Bodenseematze no worries! :)
Search can be tricky on github!
