### ISSUE TITLE
Better grouping for property fields

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/contacts#904] opened 2019-02-01 13:11 UTC
Property fields have a kind of strange floating behavior. When adding e.g. another email field, it does not sit below the first one but next to it, which makes it really hard to find it, after selecting it in "add new property":

![screenshot from 2019-02-01 14-04-49](https://user-images.githubusercontent.com/476060/52124706-649cf280-262a-11e9-9bf1-583fd4ed03b2.png)

Same view with red borders added around each property:

![screenshot from 2019-02-01 13-59-45](https://user-images.githubusercontent.com/476060/52124628-2f90a000-262a-11e9-8b34-d4c07434ee4c.png)

It's easier to make up what goes where, when narrowing down the width of the view:

![screenshot from 2019-02-01 13-58-22](https://user-images.githubusercontent.com/476060/52124667-47682400-262a-11e9-9119-57648cf7f5d9.png)

I guess solving this would mean to put some effort into the fine-tuning of the grid layout. Or simply surround groups of fields with another `<div/>` maybe :man_shrugging:

**Comment by skjnldsv** [comment] 2019-02-03 15:45
Duplicate of #654

**Closed by skjnldsv** 2019-02-03 15:45 UTC
Labels: bug, enhancement
