### ISSUE TITLE
iOS Address book hides data!

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/contacts#1973] opened 2020-12-11 23:55 UTC
### Describe the bug

iOS address book mungs vcard entries so that Contacts does not display some fields.

For more information, see Nextcloud help issue "iOS Address book eats data!", https://help.nextcloud.com/t/ios-address-book-eats-data/97058.

**To Reproduce**

1. Enter a new entry on Nextcloud or on the iPhone.

1. Edit the entry on the iPhone: add a new phone number, or look up the address using the iPhone maps app.

1. Compare what the iPhone shows vs. what Contacts shows. Fields the iPhone changes tend to disappear in Contacts.

1. Export the entry from Nextcloud, and examine the vcard

**Expected behavior**
Tell us what you expected to happen.

I expect standard vcard fields to show up on Contacts.

It would be nice if Apple extensions also showed up.

**Actual behavior**

Fields the iPhone changes tend to disappear in Contacts. Apple custom fields don't show at all.

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64

**Web server:** Apache, Nginx...

Apache/2.4.38 (Debian) (apache2handler)

**Database:** MariaDB, MySQL, PostgreSQL... 

sqlite3 3.27.2

**PHP version:** 7.0, 7.1, 7.2...

7.3.19-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)

19.0.5 - 19.0.5.2

**Contacts version:** (see Nextcloud apps page)

3.4.2

**Updated from an older Nextcloud or fresh install:**

upgraded.

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
root@hawk:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.2
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - issuetemplate: 0.7.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.7
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - contactsinteraction
  - encryption
  - files_external
  - user_ldap
root@hawk:/var/www/nextcloud# 
```

**Nextcloud configuration:**
```

root@hawk:/var/www/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "nextcloud.localdomain",
            "localhost",
            "localhost.localdomain",
            ""***REMOVED SENSITIVE VALUE***"",
            ""***REMOVED SENSITIVE VALUE***"",
            "hawk",
            "hawk.localdomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/hawk.localdomain\/nextcloud",
        "dbtype": "sqlite3",
        "version": "19.0.5.2",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "calendar"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
root@hawk:/var/www/nextcloud#


### Client configuration
**Browser:**

**Operating system:**

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64

**CardDAV-clients:**

iPhone iOS 14.0.1 to 14.2

### Logs
#### *Web server error log*
```
Insert your webserver log here
```

### Nextcloud log
#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment] 2020-12-14 15:13
Please provide a vcf example here

**Comment by skjnldsv** [comment] 2020-12-14 15:15
Ah, saw your forum post 
Duplicate of https://github.com/nextcloud/contacts/issues/1842

**Closed by skjnldsv** 2020-12-14 15:15 UTC
Labels: 0. Needs triage, bug, needs info
