### ISSUE TITLE
Rework behavior of "Gender" field

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/contacts#797] opened 2018-12-26 10:57 UTC
NC 15.0.0
Contacts 3.0.1
Firefox 64.0

The field "Gender" is broken fully.

1. When add "Gender" field it creats without title, just "Select type" 
![image](https://user-images.githubusercontent.com/9205230/50443121-ece4f500-0912-11e9-8d81-1205229b2801.png)

Better to indicate what the field is it in any states of field, i.e. "Phone"
![image](https://user-images.githubusercontent.com/9205230/50443596-20c11a00-0915-11e9-8787-f7aae86cc1a7.png)

2. There is no needs in text field if it's not "Other". So editing of the text area should be disabled when set predefined gender. And in this case (with predefined gender) the text in text area should be adaptive, "Male" instead of "M", "Female" instead of "F", and this word should be translated in any language.

![gender](https://user-images.githubusercontent.com/9205230/50443807-00458f80-0916-11e9-81db-60d7a3130b75.gif)

**Comment by donvipre** [comment] 2018-12-26 22:18
see also: #780 
most likely related

**Comment by skjnldsv** [comment] 2018-12-31 12:47
Yes!
Duplicate of #780

**Closed by skjnldsv** 2018-12-31 12:47 UTC
Labels: 1. to develop, design
