### ISSUE TITLE
ios12 contacts not show phones in web interface.

### ISSUE THREAD

**Issue by askovpen** [nextcloud/contacts#932] opened 2019-02-15 13:16 UTC
in IOS 12.1.4 saved vcard have this strings:
```
...
item1.TEL;type=pref:+1111111
item2.TEL:+111111
...
```
web-interface not show this phone numbers.

**Comment by skjnldsv** [comment] 2019-02-16 08:05
Duplicate of #42

**Closed by skjnldsv** 2019-02-16 08:05 UTC
Labels: bug, enhancement

**Comment by askovpen** [comment] 2019-02-16 10:10
#793 dup
