### ISSUE TITLE
Show me what contacts cannot be imported

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1090] opened 2019-05-02 18:33 UTC
**Is your feature request related to a problem? Please describe.**
I made an import and got a message like "15 of your 260 contacts cannot be imported. more infos, see your browser console."

**Describe the solution you'd like**
Well, contacts should tell me what contacts _exactly_ cannot be imported. You surely agree that this is not a good user experience to manually have to figure out what went wrong.

**Comment by skjnldsv** [comment] 2019-05-02 20:42
Duplicate of #990

**Closed by skjnldsv** 2019-05-02 20:42 UTC
