### ISSUE TITLE
Wrong label on phone fields 

### ISSUE THREAD

**Issue by SamR2D2** [nextcloud/contacts#1540] opened 2020-03-27 17:41 UTC
### Describe the bug
In Contact View the two phone fields labeled with "work" (DE = Arbeit).
The downloaded vcard from nextcloud for this contact show's

TEL;TYPE=WORK:+49 (123) 123
TEL;TYPE=FAX;TYPE=WORK:+49 (123) 789

So one is business number and one is business fax number.

**To Reproduce**
1. Add contact in outlook (2013)
2. Sync with CalDav Synchro
3. Open contact in nextcloud contacts.

**Expected behavior**
Label (DE) "FAX Arbeit" should use for the fax number

### Server configuration

**Operating system**: Linux/Raspberry 

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.3

**Contacts version:** 3.2.0

**Updated from an older Nextcloud or fresh install:** Update

**Comment by skjnldsv** [comment] 2020-03-27 17:46
Duplicate of #942

**Closed by skjnldsv** 2020-03-27 17:46 UTC
Labels: 0. Needs triage, bug
