### ISSUE TITLE
do not import vcard contacts by clicking on the file, ask before!

### ISSUE THREAD

**Issue by usernamehyphen** [nextcloud/contacts#3756] opened 2023-12-24 21:27 UTC
### Is your feature request related to a problem? Please describe.

when accidentally clicking on some vcf file with not a very descriptive name (turns out it was a backup), Contacts opened and duplicated most of my _contacts_

### Describe the solution you'd like

maybe ask next time? 

### Additional context

its not that complicated, so there is not much text, thanks

**Comment by joshtrichards** [comment] 2024-01-14 22:53
Duplicate of #2788

**Closed by joshtrichards** 2024-01-14 22:53 UTC
Labels: enhancement, 0. Needs triage
