### ISSUE TITLE
Feature Request: Select several Phone numbers - add/edit country codes

### ISSUE THREAD

**Issue by ghost** [nextcloud/contacts#464] opened 2018-02-01 12:45 UTC
### Steps to reproduce
1. Go to contacts
2. Search for any number starting with an area code (e.g. 030)

### Expected behaviour
select all results that came up in the search and mass-edit them to have a leading country code (e.g. +49)

e.g. 
030 1234567 and
030 2345678 would be turned into 
+49 30 1234567 and
+49 30 2345678

a bonus feature would be to convert the lengthy country codes (e.g. 0049) all to shorthand (e.g. +49)

### Actual behaviour
feature non-existent

### Server configuration

**Operating system:** CentOS (shared system, uberspace)
**Web server:** Apache 2.2
**Database:** sqlite3 Version: 3.14.2
**PHP version:** 7.0.26
**Nextcloud version:** 12.0.5 (stable)
**Contacts version:**  just updated from 12.0.4 (stable)
**Signing status:** No errors have been found.
**List of activated apps:**
 · activity: 2.5.2
 · admin_audit: 1.2.0
 · bruteforcesettings: 1.0.3
 · calendar: 1.5.7
 · comments: 1.2.0
 · contacts: 2.0.1
 · dav: 1.3.1
 · federatedfilesharing: 1.2.0
 · federation: 1.2.0
 · files: 1.7.2
 · files_external: 1.3.0
 · files_pdfviewer: 1.1.1
 · files_sharing: 1.4.0
 · files_texteditor: 2.4.1
 · files_trashbin: 1.2.0
 · files_versions: 1.5.0
 · files_videoplayer: 1.1.0
 · firstrunwizard: 2.1
 · gallery: 17.0.0
 · logreader: 2.0.0
 · lookup_server_connector: 1.0.0
 · nextcloud_announcements: 1.1
 · notifications: 2.0.0
 · oauth2: 1.0.5
 · passman: 2.1.4
 · password_policy: 1.2.2
 · provisioning_api: 1.2.0
 · serverinfo: 1.2.0
 · sharebymail: 1.2.0
 · survey_client: 1.0.0
 · systemtags: 1.2.0
 · theming: 1.3.0
 · twofactor_backupcodes: 1.1.1
 · updatenotification: 1.2.0
 · workflowengine: 1.2.0
Disabled:
 · encryption
 · files_reader
 · keeweb
 · user_external
 · user_ldap
**Nextcloud configuration:**
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
{
    "system": {
        "instanceid": "ocy912vk3zmk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.martin-riesner.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "12.0.5.3",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "mail_from_address": "nextcloud-noreply",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "session_lifetime": 604800,
        "redis": {
            "host": "\/home\/amon\/.redis\/sock",
            "port": 0,
            "timeout": 0
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 58.0.1
**Operating system:** Ubuntu 16.04 LTS
**CardDAV-clients:** Android DAVDroid

**Comment by skjnldsv** [comment] 2018-10-02 13:07
Duplicate of #128

**Closed by skjnldsv** 2018-10-02 13:07 UTC
Labels: 1. to develop, enhancement, low
