### ISSUE TITLE
In dark mode the related field name is not readable

### ISSUE THREAD

**Issue by radoeka** [nextcloud/contacts#761] opened 2018-12-16 10:34 UTC
### Describe the bug
In Dark mode the related field name is in not readable, as the characters are in black instead of white.

**To Reproduce**
1. Set nextcloud on the web in dark mode
2. Goto a contact, add the field related field

**Expected behavior**
The related field name is readable

**Actual behavior**
The related field name is not readable (it hardly is, as it is black on dark background)

This is the case for probably other, similar fields.

**Screenshots**

![image](https://user-images.githubusercontent.com/2937666/50052545-12f5e280-0126-11e9-82dc-fd90f96315fb.png)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** sqlite
**PHP version:** 7.0.1

**Nextcloud version:** 14.0.3

**Contacts version:** 2.1.8

**Comment by radoeka** [comment] 2018-12-16 10:36
When solved in 3.0; I'll try when it is general available (or when I've NC-15.0 installed).

**Comment by skjnldsv** [comment] 2018-12-16 10:38
Duplicate of #760

**Closed by skjnldsv** 2018-12-16 10:38 UTC
Labels: design, enhancement, need info
