### ISSUE TITLE
Typing in notes field causes cursor to move around and delete characters as I type

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/contacts#943] opened 2019-02-21 06:19 UTC
Sorry I don't have time to add all the info you request, but I believe I can quickly describe the bug. I am running latest version of nextcloud 15 and latest version of contacts.

Issue: I add notes field to a contact. When I type in the notes, the cursor keeps jumping around and even deleting letters as I type. Very bizarre. I can't add notes. I believe you will be able to duplicate this pretty easily. 

Thank you.

**Comment by skjnldsv** [comment] 2019-02-21 11:32
Hey! No worries! :)
This is a duplicate of #923

**Closed by skjnldsv** 2019-02-21 11:32 UTC
Labels: bug
