### ISSUE TITLE
Contact list very small when a contact with "Phone" and "Detailed name" area is open

### ISSUE THREAD

**Issue by LordSimal** [nextcloud/contacts#486] opened 2018-02-16 19:30 UTC
### Steps to reproduce
1. Add a few new contacts with a "Phone" area and a "Detailed name" area
2. Look at the list of available contacts while one of the added contacts is open

### Expected behaviour
The 300px width of the contacts list, that is present in the ".app-content-list" class.

### Actual behaviour
Just 150px width, cause the content of the open contact is pushing the list to its size
Due to that pretty much every name in the list will be cut off.

<img src="https://i.pfiff.me/chrome_2018-02-16_20-22-45.png" />

### Server configuration

**Operating system**:
Ubuntu 16.04.3 LTS (4.4.0-112-generic)

**Web server:**
Apache (cant tell more due to AllInkl not showing it to me)

**Database:**
MySQL 5.6.38

**PHP version:**
7.1.11

**Nextcloud version:** 
13.0.0

**Contacts version:** 
2.1.0

**Updated from an older Nextcloud or fresh install:**
Fresh Install (updated Contacts App due to current Nextcloud Installer has version 2.0.1)

**Signing status:**
No errors have been found.

**List of activated apps:**
Default from fresh install

**Nextcloud configuration:**
`$CONFIG = array (
  'instanceid' => 'oclqkyff5fhb',
  'passwordsalt' => '<salt>',
  'secret' => '<secret>',
  'trusted_domains' => 
  array (
    0 => 'test-nextcloud.my.tld',
  ),
  'datadirectory' => '<my_dir_to_nextcloud>/test-nextcloud/data',
  'overwrite.cli.url' => 'http://test-nextcloudmy.tld',
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => '<db_name>',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'GR2rY_',
  'mysql.utf8mb4' => false,
  'dbuser' => '<db_user>',
  'dbpassword' => '<db_pw>',
  'installed' => true,
  'tempdirectory' => '<my_dir_to_nextcloud>/test-nextcloud/tmp/',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'my.tld',
  'maintenance' => false,
);`

**Are you using external storage, if yes which one:**
No

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:**
Chrome 64.0.3282.167

**Operating system:**
Windows 10

**CardDAV-clients:**
none

#### Web server error log
empty

#### Nextcloud log (data/nextcloud.log)
empty

#### Browser log
`JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://test-nextcloud.pfiff.me/apps/contacts/css/vendor/ui-select/select.min.css.map`

### Solution

Add to the ".app-content-list" class the following CSS code:

`flex: 1 0 300px;`

**Comment by skjnldsv** [comment] 2018-02-16 19:46
Duplicate of #453

**Closed** 2018-02-16 19:46 UTC
