### ISSUE TITLE
Allow custom date types

### ISSUE THREAD

**Issue by S74HK9hV** [nextcloud/contacts#866] opened 2019-01-16 16:25 UTC
**Is your feature request related to a problem? Please describe.**
Contacts app only allows BIRTHDAY, ANNIVERSARY, DATE OF DEATH as milestone dates for a contact. But there are potentially other milestones that users may want to track. For example, graduation date, or date of becoming a citizen, etc.

**Describe the solution you'd like**
Allow user to add a event date with a custom label. In the drop down menu select CUSTOM DATE and then allow user to change the label and select the date. Google contacts has this feature already. Implementation details are below

For example, in the screenshot below, user should be able to add a custom event. The field would show "Custom Event" (instead of Date of death). User clicks on field name, and can change to any other event name
![image](https://user-images.githubusercontent.com/32150864/51262818-209ac400-1981-11e9-9272-b328ce511ebe.png)

**Describe alternatives you've considered**
none

**Additional context**

Nextcloud 15 - only 3 date types available, birthday, anniversary, death
![image](https://user-images.githubusercontent.com/32150864/51262583-a5d1a900-1980-11e9-9ffe-62d95da46bc3.png)

Google Contacts - user can add a date, then make a custom label for that date
![image](https://user-images.githubusercontent.com/32150864/51262531-8d618e80-1980-11e9-9e22-d68050f8a483.png)

**Comment by skjnldsv** [comment] 2019-01-16 17:25
duplicate of #223

**Closed** 2019-01-16 17:26 UTC
Labels: duplicate
