### ISSUE TITLE
Cannot add Birthday correctly

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#862] opened 2019-01-15 08:35 UTC
Hi,

when I add a Birthday to a Contact, the field saves the date always -1 month. E.g. 5th May 2000 -> 5th April 2000.

**To Reproduce**
1. Create new contact or select existing
2. Add new Property "Birthday"
3. select any date.

**Expected behavior**
Selected date saved

**Actual behavior**
date minus 1 month is saved.

**Screenshots**

### Server configuration
Tested on 2 systems:

**Operating system**: Ubuntu 18.04 and Webhoster

**Web server:** Apache

**Database:** PostgreSQL 11.1 and MySQL 5.7.24

**PHP version:**  7.2.14 and 7.1.26

**Nextcloud version:** both 15.0.2

**Contacts version:** both 3.0.2

**Updated from an older Nextcloud or fresh install:**
Updated and fresh

**Signing status:**
ok

**List of activated apps:**
```
Enabled:
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.1
  - deck: 0.5.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - ransomware_detection: 0.4.2
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

```

### Client configuration
**Browser:**
Firefox and Chrome
**Operating system:**
Windows 10 and Ubuntu 18.10

**Comment by skjnldsv** [comment] 2019-01-15 08:57
Duplicate of #794

**Closed by skjnldsv** 2019-01-15 08:57 UTC
Labels: bug
