### ISSUE TITLE
Contact doesn't save

### ISSUE THREAD

**Issue by allorder** [nextcloud/contacts#149] opened 2017-02-27 15:57 UTC
### Steps to reproduce
1. Try to save a new contact
2.
3.

### Expected behaviour
Save information

### Actual behaviour
A new contact appear with no information 

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** apache 2.4.18

**Database:** mariadb 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** (see Nextcloud admin page)  11.0.2 (stable)

**Contacts version:** (see Nextcloud apps page)  1.5.3

**Updated from an older Nextcloud or fresh install:** updated from 11.0.1

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folderEnabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - admin_notifications: 1.0.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.0
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ojsxc: 3.1.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - issuetemplate
  - user_external
  - user_ldap
  - user_saml


**The content of config/config.php:**

```
If you have access to your "system": {
        "instanceid": "oc4eia6szmeg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
"***REMOVED SENSITIVE VALUE***"
        ],
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "XX",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "mysql",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Toronto",
        "installed": true,
        "default_language": "fr",
        "mail_smtpmode": "smtp",
        "mail_from_address": "XXX",
        "mail_domain": "XXX",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "XXX",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "appstore.experimental.enabled": true,
        "theme": "",
        "htaccess.RewriteBase": "\/",
        "check_for_working_htaccess": true,
        "maintenance": false,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "enable_previews": "true"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

Insert your Nextcloud log here
```
No error

**Comment by allorder** [comment] 2017-03-29 12:57
Update: In the console I have theses errors:

Refused to load the script 'https://***/apps/ojsxc/js/jsxc/lib/otr/vendor/salsa20.js' because /apps/contacts/#/All%20contacts?uid=9bd4a419-89fb-421b-bb21-16c32e1b4cb9:1 
it violates the following Content Security Policy directive: "script-src 'nonce-WDhPT1pKNzFCc0t3aExtZklQMjVsTk9vZktyZGJadmdWdmtEVVFLTm9KOD06TE9qK1ZleVVWZTNIM1ByNVRzei81cGJPTnNDdFhhS21ISnRDRmpDbThldz0=' 'unsafe-eval'".

Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://***/apps/ojsxc/js/jsxc/lib/otr/vendor/salsa20.js' failed to load.
    at onmessage (https://***/apps/ojsxc/js/jsxc/lib/otr/lib/dsa-webworker.js:36:19)
onmessage @ dsa-webworker.js:36

PUT https://***/remote.php/dav/addressbooks/users/root/test/1ddfd9b9-6b8d-44c9-81fd-6c271bbee5c1.vcf 412 (Precondition failed)

Uncaught (in promise) Error: Bad status: 412
    at XMLHttpRequest.request.onreadystatechange (dav.js?v=d7669b1…:3649)

**Comment by irgendwie** [comment] 2017-05-19 12:17
Sorry for the late repsonse @allorder.
I am currently looking into all issues, which are dealing with non saving contacts.
Were you able to resolve this problem on your own?

The errors in your last comment are coming from a different nextcloud app you are using. Could you try disabling it and rechecking if the problem still occurs?

**Comment by theCalcaholic** [comment] 2017-05-29 12:25
The first error @allorder mentioned is in fact coming from ojsxc.
It's due to a chrome CSP being violated in the script salsa20 which is included in the ojsxc app.

Since this appears to be 3rd party library it might be advisable to report the issue there.

I experience the same CSP problems:
`Refused to load the script 'https://cloud.knoeppler.org/apps/ojsxc/js/jsxc/lib/otr/vendor/salsa20.js' because it violates the following Content Security Policy directive: "script-src 'nonce-Sjd5OW9Ta2dMM1llTVZvQWZrVlhwZTZTNWtBZ3JZZEFPUGZYdGhLeGFJcz06VSt6WjF3SVJSbGxYY2h0SktTQm1uZGJVdmdWWnhjZ0VBYktjNEVML0NzZz0=' 'unsafe-eval'".`

**Comment by jancborchardt** [comment] 2017-07-04 18:32
cc @sualko @LEDfan for Chat / JSXC – can you help debug this?

**Comment by sualko** [comment] 2017-07-05 07:57
This error was previously reported at jsxc/jsxc#521, but closed due to lack of information. I reopened it and hope @theCalcaholic @allorder will help me to find the root cause of the issue. It's a bit weird, because we add `self` to the csp in [app.php#L34](https://github.com/nextcloud/jsxc.nextcloud/blob/master/appinfo/app.php#L34).

Btw. the author of this issue should update ojsxc to it's latest version and try to disable ojsxc to check if this causes the described error.

**Comment by theCalcaholic** [comment] 2017-07-05 09:58
For me the issue has been fixed. I didn't provide more information, because the errors have been so inconsistent (between browsers, but even within the same one), that I was unsure what to report.
If I recall correctly, it was fixed by an update to the app.

**Comment by jancborchardt** [comment] 2017-07-06 10:27
Thank you for the info @theCalcaholic! :) Since an update fixed it, I'm closing this issue.

**Closed** 2017-07-06 10:27 UTC
Labels: bug, needs info
