### ISSUE TITLE
Contact photos dont show up until you click on the contact

### ISSUE THREAD

**Issue by pflaugh** [nextcloud/contacts#581] opened 2018-07-19 15:47 UTC
### Steps to reproduce
1. Open Contacts App
2. Scroll down list of contacts that should have photos
3. Click on contact that should have a photo showing in the list, once the contact loads the "details" pane, the photo will populate over in the list entry for that contact.

### Expected behaviour
Have the photos for all contacts populate upon opening the Contacts app.

### Actual behaviour
The list on contacts loads, but without photos. Once you click on a contact that has a photo, the photo will populate and stay until you close out the contacts app or navigate to a different app.

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** PHP 7

**Nextcloud version:** 13.0.4

**Contacts version:** 2.1.5

**Updated from an older Nextcloud or fresh install:** Updated

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.3.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.2
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - onlyoffice: 1.3.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_automatedtagging
  - files_texteditor
  - notes
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows/Mac/iOS

**CardDAV-clients:**iOS

#### Web server error log
```
error.log

[Thu Jul 19 06:25:08.694813 2018] [ssl:warn] [pid 18700] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 19 06:25:08.695505 2018] [ssl:warn] [pid 18700] AH01909: localhost:12322:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 19 06:25:08.695815 2018] [mpm_prefork:notice] [pid 18700] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Thu Jul 19 06:25:08.695829 2018] [core:notice] [pid 18700] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 19 15:15:21.295421 2018] [authz_core:error] [pid 27672] [client 208.88.254.114:60971] AH01630: client denied by server configuration: /usr/share/nextcloud/data/.ocdata
[Thu Jul 19 15:15:23.284556 2018] [authz_core:error] [pid 21654] [client 208.88.254.114:60970] AH01630: client denied by server configuration: /usr/share/nextcloud/data/.ocdata
[Thu Jul 19 15:15:28.977442 2018] [authz_core:error] [pid 21617] [client 208.88.254.114:60981] AH01630: client denied by server configuration: /usr/share/nextcloud/data/.ocdata
[Thu Jul 19 15:29:34.625279 2018] [authz_core:error] [pid 21655] [client 208.88.254.114:61186] AH01630: client denied by server configuration: /usr/share/nextcloud/data/.ocdata
[Thu Jul 19 15:29:38.428061 2018] [authz_core:error] [pid 27718] [client 208.88.254.114:61188] AH01630: client denied by server configuration: /usr/share/nextcloud/data/.ocdata



```

#### Nextcloud log (data/nextcloud.log)
```

Contains sensitive info and doesn't seem to contain anything helpful in this case.

```

#### Browser log
```
Insert your browser log here, this could for example include:


```

**Comment by skjnldsv** [comment] 2018-09-11 18:58
Duplicate of #215

**Closed by skjnldsv** 2018-09-11 18:58 UTC
