### ISSUE TITLE
Get Signal to the list of messengers and the handler to open the app

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/contacts#3553] opened 2023-08-11 07:28 UTC
### Is your feature request related to a problem? Please describe.

The contacts app provides convenient way of storing the user data. Amongst others there's the field messenger, where the username or mobile phone number may be placed. The list of messengers lacks Signal app, which becomes quite popular amongst users. Please, add it.

Additionally, please, add the handler, which will allow to open Signal app, when clicked on the icon to the right of username. This may be related to any other messenger app, eg a user may select application to use for its opening. 

### Describe the solution you'd like

Add the handler which will allow a user to open a selected messenger application to make a chat or call (should be selected) when clicked on the username field.

**Comment by ChristophWurst** [comment] 2023-08-11 07:33
Duplicate of https://github.com/nextcloud/contacts/issues/2910?

**Comment by ostasevych** [comment] 2023-08-11 07:43
Please, close it. It is really duplicating my previous request 🤦‍♂️

**Closed** 2023-08-11 07:47 UTC
Labels: enhancement, 0. Needs triage
