### ISSUE TITLE
contact field labels should always be displayed the the selected language

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#374] opened 2017-10-03 18:03 UTC
## Expected behavior
The field labels of a contact record should always be displayed the the selected language, e.g. `german`.

## Current behavior
The field labels of a contact record are very often displayed in `english` language although they should be displayed in `german` language . 

![20171003_contacts_labels](https://user-images.githubusercontent.com/2572764/31140533-f66a90c6-a874-11e7-8076-64a377455bf0.png)

I've therefore exported a contact record to a vcf-file and found the following address field entries:
```
EMAIL;TYPE=home,pref:<email-address>
TEL;TYPE=home:<phone-number>
TEL;TYPE=cell:<mobile-number>
TEL;TYPE=fax,home:<fax-number>
ADR;TYPE=home:<address-data>
```
Then I changed the field labels twice to get them displayed in the local language again.

![20171003_contacts_labels-ok](https://user-images.githubusercontent.com/2572764/31140572-157c970c-a875-11e7-8e3f-e2f30561f48c.png)

After exported the contact record to a vcf-file again, the address fields are all written in upper-case now:
```
EMAIL;TYPE=HOME,PREF:<email-address>
TEL;TYPE=HOME,VOICE:<phone-number>
TEL;TYPE=CELL:<mobile-number>
TEL;TYPE=HOME,FAX:<fax-number>
ADR;TYPE=HOME:<address-data>
```
Base on my findings I assume that the field label translation mechanism is based on the upper-case writing of the field names, which is not done before a records is displayed. Therefore a character conversion should be done in the Contacts app before data is displayed or in the server part before data is written to the database by e.g. the sync mechanism. (The contacts app seems to work correctly at this point).

### Steps to reproduce
1. Open the contacts app
2. Set the sorting order to 'last name'
3. check-out a contact for which no first name has been entered.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.03
Contacts app version: 2.0.0

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

**Comment by irgendwie** [comment] 2017-11-02 08:47
Seems to be fixed by  #380, can't reproduce it anymore at least.

**Closed by irgendwie** 2017-11-02 08:47 UTC
Labels: 1. to develop, bug, compatibility, good first issue
