### ISSUE TITLE
Last modified date is not displayed in the preferred language

### ISSUE THREAD

**Issue by MeCias** [nextcloud/contacts#1096] opened 2019-05-09 06:11 UTC
Hi,

I just noticed that the last modified date is displayed in English and German, similar to the [issue](https://github.com/nextcloud/mail/issues/1232) that I reported with the email app. My set language in NC is English, but my locale is Germany and there the timestamp gets confused I guess.

![screenshot](https://user-images.githubusercontent.com/4476171/57431043-cf655780-7231-11e9-9e3e-b505fbb06e9f.jpg)

**Comment by skjnldsv** [comment] 2019-05-09 06:40
@MeCias Hey!
Well, this is why we have a locale settings.
Like the locale setting state: the dates will be formatted with the locale and not the language :)

**Comment by MeCias** [comment] 2019-05-09 07:20
Hi,
 I agree and understand. Just looks wrong. But I just got told that nickvergessen is already working on that [issue](https://github.com/nextcloud/server/pull/14784), since this behavior is not app related it seems to be like that for the whole NC installation.

**Comment by skjnldsv** [comment] 2019-05-09 07:23
@MeCias Good question :)
I'll see what comes out of the issue indeed.

I agree that it kinda looks weird, but I don't know what the locale setting would be used for if we don't display the dates with it then :thinking:

**Comment by MeCias** [comment] 2019-05-09 07:30
My understanding always was that locale sets the timezone you are in and the language defines how the this information gets displayed.  :) THX

**Comment by wiswedel** [comment] 2020-01-02 06:35
duplicate of https://github.com/nextcloud/server/issues/15457

**Closed by wiswedel** 2020-01-02 06:35 UTC
Labels: 0. Needs triage, bug, pending fix
