### ISSUE TITLE
Option Select picture from Nextcloud

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/contacts#240] opened 2017-06-23 09:24 UTC
### Steps to reproduce
1. Go to an User
2. Click on Picture placeholder
3.

### Expected behaviour
Will it be possible to get the option to select a picture from nextcloud and not only from pc. Also a bigger Size as 1MB will be greate. I have no picture smaller as an 1 MB include pictures taken with my smartphone

### Actual behaviour
It is only possible to load picture from pc

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Contacts version:** (see Nextcloud apps page)
1.5.3
 

thanks for the great looking app

**Comment by jancborchardt** [comment] 2017-07-04 16:52
This is a duplicate of https://github.com/nextcloud/contacts/issues/106, let’s continue there. :)

**Closed by jancborchardt** 2017-07-04 16:52 UTC
Labels: enhancement
