### ISSUE TITLE
Hide not used fields

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/contacts#3561] opened 2023-08-13 13:23 UTC
### Is your feature request related to a problem? Please describe.

When opening a user contact I see a lot of fields, which are a bit redundant, take place and do not allow to get the most needed information. Will it be possible to hide those fields, which are not filled in the view form?

![image](https://github.com/nextcloud/contacts/assets/5199030/7ff9d8c9-820d-485d-9b9a-67ecfa090486)

Moreover, I suggest to make the fields: birthday, messenger available by default, but not hidden under "Add more info".

**Comment by ChristophWurst** [comment] 2023-08-14 07:45
Duplicate of https://github.com/nextcloud/contacts/issues/3363

**Closed by ChristophWurst** 2023-08-14 07:45 UTC
Labels: enhancement, 0. Needs triage
