### ISSUE TITLE
Spinning Wheel 11.0.1.2 ->11.0.2.7

### ISSUE THREAD

**Issue by MarcSN311** [nextcloud/contacts#153] opened 2017-03-04 10:23 UTC
After upgrading from NC 11.0.1.2 to  NC 11.0.2.7 and also upgrading Contacts app to 1.5.3 its only showing the spinning wheel for all users. This install is on Debian 8/nginx/mariadb and has several other apps activated.

After setting up a fresh NC 11.0.2.7 install with contacts app 1.4.1 and importing my Database this only happens for one out of two users. This install is also on Debian 8/apache2/mariadb and only has the default apps and contacts app active.

#### Web server error log
```
[Sat Mar 04 10:25:12.671213 2017] [:error] [pid 18191] [client XX.XX.XX.XX:39354] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4492560 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"vq2YZUcNhpjAmrc9slWL","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4492560 bytes) at \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2017-03-04T09:25:12+00:00","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/addressbooks\/users\/alexandra\/kontakte\/","user":"alexandra","version":"11.0.2.7"}
```

#### Browser log
![nc_contacts](https://cloud.githubusercontent.com/assets/12860202/23578018/09010a9e-00cd-11e7-95e0-526d66af670d.png)

EDIT: I just checkt the Database: the update blew it up somehow.the non working user has 3902 entries in nc_cards, resulting in a 600MB sql dump.

**Comment by skjnldsv** [comment] 2017-03-05 04:49
What does says the 500 error in your browser?

**Comment by jancborchardt** [comment] 2017-07-04 18:31
Seems to be a duplicate of https://github.com/nextcloud/contacts/issues/145 – let’s continue there.

**Closed by jancborchardt** 2017-07-04 18:31 UTC
Labels: needs info
