### ISSUE TITLE
contacts app 3.0.1 sets wrong date

### ISSUE THREAD

**Issue by KLobrillenmann** [nextcloud/contacts#841] opened 2019-01-09 13:06 UTC
⚠ Please report only issues corresponding to the contacts app for Nextcloud ⚠

Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues

If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts
__________________________________________________________________

### Describe the bug
When I fill a date field in the contacts app (picking year month day time in GUI), then the app in many cases doesn´t read the correct date from my GUI entries.

I couldn´t see a pattern in which cases a date is set wron in first place and when not. But for the specific example it is repeatable
......
......

**To Reproduce**
1. set birthday date to 1966-11-14 it ends up with a 1966-10-14
2. when changing wrong 166-10-14 to  e.g. 1966-01-14 it ends up with (month-1) which is 1966-09-14
3. doing a change to the newly wrong 1966-09-14 again  e.g. change to 1966-05-14 once again it does a (month-1) and ends up with a 1966-08-14

![date bug 1](https://user-images.githubusercontent.com/46526792/50901125-89c98700-1417-11e9-90dc-ec738814ba04.JPG)
![date bug 2](https://user-images.githubusercontent.com/46526792/50901129-8d5d0e00-1417-11e9-87ef-34fb1e7d72b4.JPG)
![date bug 3](https://user-images.githubusercontent.com/46526792/50901133-8f26d180-1417-11e9-8d55-6a36f1e25574.JPG)
![date bug 4](https://user-images.githubusercontent.com/46526792/50901135-9057fe80-1417-11e9-82ea-6db187a2c2cc.JPG)
![date bug 5](https://user-images.githubusercontent.com/46526792/50901137-9221c200-1417-11e9-964e-b2c3125a0421.JPG)
![date bug 6](https://user-images.githubusercontent.com/46526792/50901141-93eb8580-1417-11e9-8680-4cc143d89ab2.JPG)

**Expected behavior**
fill the date fields like picked in GUI

**Actual behavior**
Tell us what happened instead.
in my case month was one behind and always one more behind afer every month change

**Screenshots**

### Server configuration

**Linx (Synology)

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** 7.0

**Nextcloud version:** 15.0.0
**Contacts version:** 3.0.1

**Updated from an older Nextcloud or fresh install:**
updated to 15.0.0 beta channel when 15.0 was final released

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
Chrome

**Operating system:**
Win 10

**CardDAV-clients:**
DAVx5 on android

### Logs
#### *Web server error log*
```
Insert your webserver log here
```

### Nextcloud log
#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment] 2019-01-09 13:30
Duplicate of #840

**Closed by skjnldsv** 2019-01-09 13:30 UTC
Labels: bug
