### ISSUE TITLE
Feature request : multi select to sort / delete contacts

### ISSUE THREAD

**Issue by rgarrigue** [nextcloud/contacts#519] opened 2018-03-12 10:54 UTC
Hi

Everything is in the title. I wish there was a multi select feature (ctrl clic clic clic, or a select all / none button) for some mass operation, like deleting users.

Best regards,

**Comment by skjnldsv** [comment] 2018-03-12 11:07
Duplicate of #277

**Closed by skjnldsv** 2018-03-12 11:07 UTC
