### ISSUE TITLE
Trash for contacts

### ISSUE THREAD

**Issue by zeroblue2005** [nextcloud/contacts#3849] opened 2024-03-10 09:27 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

A trash can for accidentally deleted contacts, for example in Thunderbird.  This already exists in the calendar app.  This applies to both individual objects and entire calendars.  This would be a great advantage for administrators in contacts.  Since contacts currently have to be done in a complex manner via a database restoration or via backup on the client side.

**Comment by joshtrichards** [comment] 2024-06-15 23:06
Duplicate of #296

**Closed by joshtrichards** 2024-06-15 23:06 UTC
Labels: enhancement, feature: contacts, 0. Needs triage
