### ISSUE TITLE
Contacts Birthday Calendar entries are not deleted when Addressbook is deleted

### ISSUE THREAD

**Issue by michaelof** [nextcloud/contacts#1902] opened 2020-10-30 21:57 UTC
### Steps to reproduce
Deletion of an addressbook deletes also contacts within this addressbook.
But birthdays in "Contact's birthday" calendar are not deleted for "auto-deleted" contacts, leaving "orphan" calendar entries.

1. Create addressbook
2. Import some vcards with BDAY nodes
3. Delete addressbook
4. Switch to Calendar app: Birthdays are still shown
5. Repeat Step 1 to 3
4. Switch to Calendar app: Birthdays are now shown TWO times
5. ...
9999. Switch to Calendar app: Birthdays are now shown N times, for each import/delete

Workaround: 
- DIsable creation of "Contact's birthday" calendar, as admin
- Reenable creation of "Contact's birthday" calendar, as admin
- Wait for next cron run

This recreates/repopulates "Contact's birthday" calendar.

## Server configuration detail

**Operating system:** Linux 5.3.18-lp152.47-default #1 SMP Thu Oct 15 16:05:25 UTC 2020 (41f7396) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.4.14

**PHP version:** 

7.4.6
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, apcu, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, ldap, exif, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, zlib, posix, soap, sockets, sqlite3, tokenizer, xmlreader, xmlwriter, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.1 - 20.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from OwnCloud, LONG ago...

**Where did you install Nextcloud from:** OpenSuse RPMs

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.2
 - admin_audit: 1.10.0
 - audioplayer: 2.12.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.1
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - encryption: 2.8.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.5.1
 - music: 0.17.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.1
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.5
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "updatechecker": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost:10080",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost:10080\/nextcloud",
    "dbtype": "mysql",
    "version": "20.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "appstore.experimental.enabled": true,
    "theme": "",
    "loglevel": 0,
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "log_rotate_size": 10485760,
    "app_install_overwrite": [
        "tasks",
        "contacts",
        "unsplash",
        "bruteforcesettings"
    ],
    "mysql.utf8mb4": true,
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

**Operating system:** OpenSuse Leap 15.2

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by skjnldsv** [comment] 2020-10-31 10:45
I think they are deleted on the next cron run.
Can you run cron and check?

Make sure it is also properly setup on your server :)

**Comment by michaelof** [comment] 2020-11-01 16:40
I can conform that cron is set up for my nextcloud, like this:
```sh
vserver:~ # crontab -u wwwrun -l
*/5  *  *  *  * php -f /srv/www/htdocs/nextcloud/cron.php

```
Nextclouds cron itself works, as written above, about the "workaround":

- Works fine regarding recreating/repopulating the contacts birthday calendar when disabling/enabling as an admin (groupware settings).
- Does NOT work as you expected, "orphaned" birthdays are still there after next (or whenever) cron run.

**Comment by skjnldsv** [comment] 2020-11-02 10:23
I guess this is a duplicate of https://github.com/nextcloud/server/issues/1506
Apparently a known issue, sorry about that. :)

**Closed by skjnldsv** 2020-11-02 10:23 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by cristarta** [comment] 2021-01-02 14:23
A workaround described in related issue [#1506](https://github.com/nextcloud/server/issues/1506) allowed me to fix this outstanding problem on my Nextcloud v19 installation as a regular user - in case non-dev users land on this page.
