### ISSUE TITLE
Move to/from groups using drag & drop

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1089] opened 2019-05-02 18:30 UTC
**Is your feature request related to a problem? Please describe.**
I have 100+ contacts that I want to sort into groups. Now, I have to open every contact manually and assign the group.

**Describe the solution you'd like**
Why can't I just drag and drop the contacts in the second column to a group in the first column?

**Comment by skjnldsv** [comment] 2019-05-02 20:42
duplicate of #564

**Closed by skjnldsv** 2019-05-02 20:42 UTC
