### ISSUE TITLE
Option to select muiltiple contacts at once, e.g. for deletion

### ISSUE THREAD

**Issue by michaelof** [nextcloud/contacts#1898] opened 2020-10-28 14:52 UTC
**Describe the solution you'd like**
It would be cool to have a GUI option (e.g. checkbox for each contact) to select multiple contacts at once. For further processing, e.g. to delete them.

**Describe alternatives you've considered**
As I've written a (perl) script which reads contact data from a spreadsheet and creates a single vcard file for them, to be imported into nextcloud, I needed a chance to delete all imported contacts at once, while testing. 
To be able to do this, I'm currently importing them into a separate addressbook, which I can easily delete and recreate. But based on a restriction of the in Germany widely used "Fritzbox" described here https://help.nextcloud.com/t/mass-delete-of-contacts-how-if-possible/95410/7 it finally would be cool to select multiple to be deleted contacts. 
Maybe based on CATEGORIES, deletion of all contacts belonging to a specific category

BTW, FYI, there's a small and not very important bug in current Contacts app:
Nextcloud (20.0.1) shows # of contacts in a category, when Contacts app is loaded in Browser.
When I as described delete an adressbook (all contacts of the addressbook are also assigned to a category with same name), the contacts are gone as they should.
Category/group still there, and Browser correctly says "no contacts in group". But # counter for category/group still shows # of contacts before deletion of addressbook. E.g. "31" instead of now "0".
When now recreating the addressbook and (re-)importing the contacts, # counter is "adding" them always to the existing # value. E.g. "62" instead of now "31".

**Comment by skjnldsv** [comment] 2020-10-28 15:12
Hey! Thanks for your interest :)
This is a duplicate of #277

**Closed by skjnldsv** 2020-10-28 15:12 UTC
Labels: 0. Needs triage, enhancement
