### ISSUE TITLE
Contacts phone number type gets replaced with random values by Nextcloud

### ISSUE THREAD

**Issue by eibex** [nextcloud/contacts#1503] opened 2020-03-06 00:19 UTC
I will preface this issue by saying that I am unsure if this is a contacts or nextcloud/server issue.

### Describe the bug
Contacts on Nextcloud that have phone numbers without a specified type (e.g. home, mobile, ...) are synced to phones (iOS at least) with the type marked as `VALUE` or `VOICE`. This happens with contacts that were synced from the phone to Nextcloud and all fields were marked with mobile, etc. but they recently got replaced by `VALUE` or `VOICE`.

I went ahead and _manually_ replaced every single phone number to mobile, home, work from the Nextcloud instance. This only worked for `mobile`, as `home` and `work` are shown on the phone as `"HOME` `"WORK` (with just one leading double quotation and no quotation at the end) but they show correctly on the Contacts interface.

This is not limited to phone numbers, but to other properties with selectable types (e.g. email, address).

This happened recently and never happened since relying on NC for CardDAV for months. 

**To Reproduce**
1. Add a contact with a phone number from the phone (usually the label defaults to mobile)
2. Load the contact card on Nextcloud contacts and notice that there is no type next to the phone number (it asks to select it)
3. Edit the contact on the web interface (not necessarily the phone number, even the middle name) (leave the phone number type "empty")
4. Sync your phone again to see normal values like `mobile` replaced by `VALUE`

OR

1. Add a contact with a phone number from the phone
2. Load the contact card on Nextcloud contacts and notice that there is no type next to the phone number (it asks to select it)
3. Edit the phone number type on the web interface to "home" or "work" (not "mobile" as this is synced correctly)
4. Sync your phone again to see `home` replaced by `"HOME` and `work` replaced by `"WORK`

**Expected behavior**
Type fields are synced and not replaced.

**Actual behavior**
The phone number type is replaced by string like VALUE or VOICE if left empty or by "HOME or "WORK if set to home or work.

**Screenshots**
- [VALUE](https://user-images.githubusercontent.com/40539455/76037559-aa23a180-5f47-11ea-8b91-affeec8c4b49.png)
- ["WORK](https://user-images.githubusercontent.com/40539455/76037594-bf003500-5f47-11ea-8e82-2a341355be5f.jpg)

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache2.4.41

**Database:** PostgreSQL 10.12

**PHP version:** 7.2

**Nextcloud version:** 17.0.3

**Contacts version:** 3.2.0

**Updated from an older Nextcloud or fresh install:** Updated from 16

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.2.0
  - dav: 1.13.0
  - external: 3.4.1
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.3
  - maps: 0.1.2
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - richdocuments: 3.5.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - suspicious_login: 3.1.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - survey_client
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "https:\/\/cloud.example.com\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 3
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "lost_password_link": "disabled"
    }
}
```

### Client configuration
**CardDAV-clients:** iOS

### Logs
No relavant logs to show.

### Nextcloud log
No relavant logs to show.

**Comment by skjnldsv** [comment] 2020-03-06 06:54
Duplicate of #941 https://github.com/nextcloud/contacts/issues/942

This is iOS fault, but we can help mitigate

**Closed by skjnldsv** 2020-03-06 06:54 UTC
Labels: 0. Needs triage, bug
