### ISSUE TITLE
Contacts not readable in Opera

### ISSUE THREAD

**Issue by summerm78** [nextcloud/contacts#480] opened 2018-02-13 22:40 UTC
### Steps to reproduce
1. Upgrade to Contacts 2.1.0
2. Login and open Contacts

### Expected behaviour
Contactlist should be readable.

### Actual behaviour
Contactlist is resized to 3 characters

### Server configuration
**Operating system**:
Linux 3.10 (sorry, not more informations because it is a managed plattform) 

**Web server:**
apche2

**Database:**
mysql 5.5.56

**PHP version:**
7.1.14

**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Contacts version:** (see Nextcloud apps page)
2.1.0

**Updated from an older Nextcloud or fresh install:**
Update from 12.5.0

```
No errors have been found.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Opera 51.0.2830.26, always full-screen
Cache cleanded and private tab

**Operating system:**
Fedora 27
Windows 10
<img width="381" alt="contacts" src="https://user-images.githubusercontent.com/15927212/36177829-33756a1c-1117-11e8-9433-e88c501cc5ec.png">

**Comment by skjnldsv** [comment] 2018-02-14 07:08
Duplicate of #453

**Closed** 2018-02-14 07:08 UTC
Labels: duplicate
