### ISSUE TITLE
Field for Telephonenumber

### ISSUE THREAD

**Issue by PrinzS** [nextcloud/contacts#1178] opened 2019-07-17 10:50 UTC
### Describe the bug
If we synchronize contacts to IOS or Android the Field description ist wrong.
In IOS Arbeit: Number is shown as "Work: Number
In Android sonstiges Number

So in Android the field is not known and in IOS you habe the "symbol and the english description.
In field E-Mail everything ist correct.

**To Reproduce**
1. Go to "Contacts"'
2. Click on 'a contact'
3. Edit the contact 'Description for telphonnumber'
4. See error on IOS or Android device

**Expected behavior**
Tell us what you expected to happen.
The Contactfields should be shown correct with german description.

**Actual behavior**
Tell us what happened instead.
Instead of Arbeit in IOS you get *"Work* and in Android *sonstiges*

**Screenshots**

### Server configuration

**Operating system**:  Linux

**Web server:** Apache

**Database:**MySQL 10.1.40

**PHP version:** 7.2.20

**Nextcloud version:** 16.0.3.0

**Contacts version:** 3.1.3

**Updated from an older Nextcloud

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
Accessibility	1.2.0	Offiziell	
Activity	2.9.1	Offiziell	
Auditing / Logging	1.6.0	Offiziell	
Brute-force settings	1.4.0	Offiziell	
Calendar	1.7.0	Offiziell	
Collaborative tags	1.6.0	Offiziell	
Comments	1.6.0	Offiziell	
Contacts	3.1.3	Offiziell	
Deleted files	1.6.0	Offiziell	
External storage support	1.7.0	Offiziell	
Federation	1.6.0	Offiziell	
File sharing	1.8.0	Offiziell	
First run wizard	2.5.0	Offiziell	
Gallery	18.3.0	Offiziell	
Log Reader	2.1.0	Offiziell	
Monitoring	1.6.0	Offiziell	
Nextcloud announcements	1.5.0	Offiziell	
Notifications	2.4.1	Offiziell	
Password policy	1.6.0	Offiziell	
PDF viewer	1.5.0	Offiziell	
Privacy	1.0.0	Offiziell	
Quota warning	1.5.0		
Recommendations	0.4.0	Offiziell	
Right click	0.13.0		
Share by mail	1.6.0	Offiziell	
Support	1.0.0	Offiziell	
Talk	6.0.2	Offiziell	
Text editor	2.8.0	Offiziell	
Theming	1.7.0	Offiziell	
Update notification	1.6.0	Offiziell	
Usage survey	1.4.0	Offiziell	
Versions	1.9.0	Offiziell	
Video player	1.5.0	Offiziell	
Viewer	1.0.0	Offiziell	
Default encryption module	2.4.0	Offiziell	
LDAP user and group backend

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)


### Client configuration
**Browser:** Chrome 75 on Windows 10

**Operating system:** IOS 12

**CardDAV-clients:** IOS embedded

### Logs
#### *Web server error log*
```
Insert your webserver log here
```

### Nextcloud log
#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment] 2019-07-21 20:01
Hi, please attach screenshots of both of your ios and android view.
Please also attach the (redacted for privacy) vcard.

**Comment by PrinzS** [comment] 2019-07-22 06:38
Hi there.
Here are the files.
Thx
[Screenshot.zip](https://github.com/nextcloud/contacts/files/3415974/Screenshot.zip)

**Comment by skjnldsv** [comment] 2019-07-22 08:32
Ah yes!
So this is because of iOS.
And this is a duplicate of https://github.com/nextcloud/contacts/issues/942 and https://github.com/nextcloud/contacts/issues/1107#issuecomment-495111182

**Closed by skjnldsv** 2019-07-22 08:32 UTC
Labels: 0. Needs triage, bug, need info
