### ISSUE TITLE
Birthday notification off by one day

### ISSUE THREAD

**Issue by republicus** [nextcloud/contacts#1432] opened 2020-01-21 00:31 UTC
Ive noticed a few other issues, now closed, where dates were off by a month.
I'm noticing the notifications are currently reporting the date off by one day.

### Describe the bug
Notification for birthday is off by one day.

**To Reproduce**
1. Set contact's birthday
2. Review notification of contact's birthday off by one day

**Expected behavior**
Birthday notification should show contact's accurate 

**Actual behavior**
Contact's birthday shows incorrect date (by one day in my instance) in notifications.

**Screenshots**
![image](https://user-images.githubusercontent.com/47370709/72765709-d4014e80-3bbb-11ea-9178-dc8d369841a5.png)

### Contacts app

**Contacts app version:**  3.1.6

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by hanzi** [comment] 2020-01-21 08:45
What time zone are
1. your browser/computer,
2. your Nextcloud server (you can find that one on `/settings/admin/serverinfo` under 'Server time')

in?

**Comment by georgehrke** [comment] 2020-01-21 09:35
As already asked for by @hanzi, please tell us your time-zone. 

Notifications for all-day events are currently send out at 12am UTC.

**Comment by republicus** [comment] 2020-01-22 04:10
Server time looks correct and matches my local system time.

Server time: Tue Jan 21 23:01:15 EST 2020

The attachment shows a notification not of an upcoming birthday. But, a notification that a contact was updated with a birthday -- having the wrong date.

As you see in the screenshot the birthday is more than 6 months away. July 21, But the notification says the contact was updated with the birthday July 20.

Though I did just realize that I posted this on Jan 20, and since it says its Jul 20, 2020 -- it could actually be that the notification is off by 6 months

**Comment by skjnldsv** [comment] 2020-01-24 15:14
> There is a closed ticket where birthdays were off by one month. Related?
> #652

No, this one was on display, it was fixed since if I recall correctly :)

**Comment by skjnldsv** [comment] 2020-09-06 14:55
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen in the server repository (as this is where we generate the birthday events).

**Closed by skjnldsv** 2020-09-06 14:55 UTC
Labels: 0. Needs triage, bug
