### ISSUE TITLE
Cannot access Contacts 3.1.4 on Nextcloud 16 (Could not find initial state of contacts)

### ISSUE THREAD

**Issue by sk22** [nextcloud/contacts#1287] opened 2019-09-29 17:04 UTC
* Nextcloud 16.0.5
* Contacts 3.1.4

In the console:

```
Uncaught Error: Could not find initial state of contacts
    at Module.m (initialstate.js:31)
    at e.loadState (index.js:10)
    at Module.<anonymous> (rfcProps.js:29)
    at i (bootstrap:63)
    at bootstrap:198
    at contacts.js?v=625d3545-10:1
```

and this according to Nextcloud's logging:

```
ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/contacts, file: index.php/css/contacts/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)
```

**Comment by sk22** [comment] 2019-09-29 17:07
In https://github.com/nextcloud/contacts/issues/1278#issuecomment-536319577, @skjnldsv asked me to show the source code below `This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.</div>`:

```html
    <div>
      This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.    </div>
  </div>
</noscript>

    
    <a href="#app-content" class="button primary skip-navigation skip-content">Skip to main content</a>
    <a href="#app-navigation" class="button primary skip-navigation">Skip to navigation of app</a>

    <div id="notification-container">
      <div id="notification"></div>
    </div>
    <header role="banner" id="header">
```

**Comment by skjnldsv** [comment] 2019-09-29 17:14
That is really weird!
@ChristophWurst we're using the official initial state provider API here https://github.com/nextcloud/contacts/blob/773799777c0e1b0bece80cfbc3cb6b77e28afa78/lib/Controller/PageController.php#L61

Somehow this is empty on the source code. Do you how that could be?

@sk22 do yo have some kind of web caching? Cloudflare?

**Comment by skjnldsv** [comment] 2019-09-29 17:17
@sk22  Also, on your data/nextcloud.log, nothing else?
Please set your debug loglevel to 2 in your nextcloud config and trigger the error again to see if any more warning are logged :)

**Comment by sk22** [comment] 2019-09-30 06:01
@skjnldsv Apparently, I get the same error for all kinds of apps, yet only Contacts isn't working...
```json
{"reqId":"mW50X9knjK1uB6hAHgJM","level":3,"time":"2019-09-29T18:05:07+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/contacts, file: index.php\/css\/contacts\/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"rNhQ3P0XNDEpI4jNnQ9E","level":3,"time":"2019-09-29T20:36:29+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/spreed, file: index.php\/css\/spreed\/41bb-fcfc-merged-files.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"rNhQ3P0XNDEpI4jNnQ9E","level":3,"time":"2019-09-29T20:36:29+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/text, file: index.php\/css\/text\/b24d-fcfc-icons.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"sJo21EeLJz2auPcgISmV","level":3,"time":"2019-09-29T20:36:48+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/spreed\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/spreed, file: index.php\/css\/spreed\/41bb-fcfc-merged.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"aaaedSK9NVEr8wYdU2N2","level":3,"time":"2019-09-29T20:37:01+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/maps\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/maps, file: index.php\/css\/maps\/02f4-fcfc-style.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"ozTZB0bDMiSdOc4jBUyT","level":3,"time":"2019-09-29T20:37:30+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/calendar\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/calendar, file: index.php\/css\/calendar\/91a5-fcfc-app.min.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Linux; Android 9; Pixel 2 XL) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.92 Mobile Safari\/537.36","version":"16.0.5.1"}
{"reqId":"JuHxZjt6QHBmCk08Rz9H","level":3,"time":"2019-09-30T05:51:35+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/spreed, file: index.php\/css\/spreed\/41bb-fcfc-merged-files.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"16.0.5.1"}
{"reqId":"JuHxZjt6QHBmCk08Rz9H","level":3,"time":"2019-09-30T05:51:35+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/text, file: index.php\/css\/text\/b24d-fcfc-icons.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"16.0.5.1"}
{"reqId":"tUoG1YDxVvkHBjuiz2Ay","level":3,"time":"2019-09-30T05:51:47+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/contacts, file: index.php\/css\/contacts\/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"16.0.5.1"}
{"reqId":"42OET4SeRibZ52bVrzim","level":3,"time":"2019-09-30T05:51:47+00:00","remoteAddr":"192.168.1.2","user":"kaisers","app":"lib","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/16232\/nextcloud\/extra-apps\/contacts, file: index.php\/css\/contacts\/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"16.0.5.1"}
```

And, we're using a Synology NAS as a proxy, so maybe this has something to do with it?

> Please set your debug loglevel to 2 in your nextcloud config and trigger the error again to see if any more warning are logged :)
The `nextcloud.log` contains entries from level 0 to 4, so I think everything you want to see should get logged, right?

**Comment by ChristophWurst** [comment] 2019-09-30 13:13
> Somehow this is empty on the source code. Do you how that could be?

Empty? Are you sure this code is actually run?

**Comment by skjnldsv** [comment] 2019-09-30 13:19
Well, I do have it on my 16 instance :man_shrugging:

**Comment by ChristophWurst** [comment] 2019-09-30 13:54
> it

The bug?

**Comment by ChristophWurst** [comment] 2019-09-30 13:55
> Somehow this is empty on the source code

Also where is it empty? On the generated HTML? On the server?

**Comment by skjnldsv** [comment] 2019-09-30 13:56
Nono, it works fine on my 16 instance, I did not had the issue about no initial state found. But I don't get how it's possible since the pageController implement it properly :thinking: 

@sk22 have you tried removing the app entirely (you won't loose your contacts) and install it again?

**Comment by sk22** [comment] 2019-09-30 14:03
@skjnldsv Just did, I still get an empty page… (disabling and removing the app using the web interface should do, right?)

**Comment by sk22** [comment] 2019-09-30 14:08
Oh and by the way, the contacts quick-access search widget in the Nextcloud bar aorks

**Comment by sk22** [comment] 2019-09-30 14:09
oops, accidentally closed the issue

**Comment by skjnldsv** [comment] 2019-09-30 14:17
> Oh and by the way, the contacts quick-access search widget in the Nextcloud bar works.

Yes, this is a very independent module :)
It is not related to contacts.

**Comment by sk22** [comment] 2019-09-30 14:23
> > Oh and by the way, the contacts quick-access search widget in the Nextcloud bar works.
> 
> Yes, this is a very independent module :)
> It is not related to contacts.

oh whoops, didn't notice, thanks!

**Comment by skjnldsv** [comment] 2019-10-01 06:22
@sk22 can you maybe provide me with a test account?
You can sent it to  skjnldsv@protonmail.com

**Comment by sk22** [comment] 2019-10-01 09:11
@skjnldsv done

**Comment by skjnldsv** [comment] 2019-10-01 09:16
@sk22 Thanks! I got two errors triggered on login. Could you check the nextcloud logs again please?

**Comment by sk22** [comment] 2019-10-01 09:28
@skjnldsv Sure. Here's all log entries since 2019-10-01T11:14:55+0200

```json
{"reqId":"0nVbNodAMweiv9tMZaWB","level":3,"time":"2019-10-01T09:14:55+00:00","remoteAddr":"192.168.1.2","user":"skjnldsv","app":"index","method":"POST","url":"/index.php/login","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"Photos/Coast.jpg\" is locked","Code":0,"Trace":[{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":2050,"function":"lockPath","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg",1,false]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":1140,"function":"lockFile","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg",1]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":595,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_get_contents","/skjnldsv/files/Photos/Coast.jpg",["read"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/File.php","line":52,"function":"file_get_contents","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":447,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":391,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":278,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":83,"function":"safeAddPhoto","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Hooks/FileHooks.php","line":49,"function":"safeAddByFile","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\Maps\\Hooks\\{closure}","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Hooks/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Hooks/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Root.php","line":136,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Node.php","line":109,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/File.php","line":109,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->","args":[["postWrite"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":473,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->","args":["w"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":464,"function":"copyr","class":"OC_Util","type":"::","args":["/snap/nextcloud/16232/htdocs/core/skeleton/Photos",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":436,"function":"copyr","class":"OC_Util","type":"::","args":["/snap/nextcloud/16232/htdocs/core/skeleton",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/User/Session.php","line":520,"function":"copySkeleton","class":"OC_Util","type":"::","args":["*** sensitive parameter replaced ***",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/User/Session.php","line":378,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/core/Controller/LoginController.php","line":336,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/snap/nextcloud/16232/htdocs/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","Line":1945,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/7b92edbb08c591ecc5e63199b45ffc10\" is locked, existing lock on file: exclusive","Code":0,"Trace":[{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Storage/Common.php","line":715,"function":"acquireLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->","args":["files/7b92edbb08c591ecc5e63199b45ffc10",1]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php","line":593,"function":"acquireLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files/Photos/Coast.jpg",1,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":1940,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/Photos/Coast.jpg",1,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":2050,"function":"lockPath","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg",1,false]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":1140,"function":"lockFile","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg",1]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/View.php","line":595,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_get_contents","/skjnldsv/files/Photos/Coast.jpg",["read"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/File.php","line":52,"function":"file_get_contents","class":"OC\\Files\\View","type":"->","args":["/skjnldsv/files/Photos/Coast.jpg"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":447,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":391,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":278,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Service/PhotofilesService.php","line":83,"function":"safeAddPhoto","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/16232/nextcloud/extra-apps/maps/lib/Hooks/FileHooks.php","line":49,"function":"safeAddByFile","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\Maps\\Hooks\\{closure}","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Hooks/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Hooks/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Root.php","line":136,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Node.php","line":109,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Files/Node/File.php","line":109,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->","args":[["postWrite"]]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":473,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->","args":["w"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":464,"function":"copyr","class":"OC_Util","type":"::","args":["/snap/nextcloud/16232/htdocs/core/skeleton/Photos",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/legacy/util.php","line":436,"function":"copyr","class":"OC_Util","type":"::","args":["/snap/nextcloud/16232/htdocs/core/skeleton",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/User/Session.php","line":520,"function":"copySkeleton","class":"OC_Util","type":"::","args":["*** sensitive parameter replaced ***",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/User/Session.php","line":378,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/core/Controller/LoginController.php","line":336,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"/snap/nextcloud/16232/htdocs/lib/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/snap/nextcloud/16232/htdocs/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/16232/htdocs/lib/private/Lock/MemcacheLockingProvider.php","Line":75},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36","version":"16.0.5.1","id":"5d931b23b6326"}

{"reqId":"rQJeCv7cxCoAnbMIfqJG","level":3,"time":"2019-10-01T09:15:11+00:00","remoteAddr":"192.168.1.2","user":"skjnldsv","app":"lib","method":"GET","url":"/index.php/apps/files/","message":"ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-fcfc-merged-files.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36","version":"16.0.5.1","id":"5d931b23b602b"}

{"reqId":"rQJeCv7cxCoAnbMIfqJG","level":3,"time":"2019-10-01T09:15:11+00:00","remoteAddr":"192.168.1.2","user":"skjnldsv","app":"lib","method":"GET","url":"/index.php/apps/files/","message":"ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/text, file: index.php/css/text/b24d-fcfc-icons.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36","version":"16.0.5.1","id":"5d931b23b600f"}

{"reqId":"mWqSu1QbpvTbfNufcj9Z","level":3,"time":"2019-10-01T09:15:18+00:00","remoteAddr":"192.168.1.2","user":"skjnldsv","app":"lib","method":"GET","url":"/index.php/apps/contacts/","message":"ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/contacts, file: index.php/css/contacts/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36","version":"16.0.5.1","id":"5d931b23b5ff3"}

{"reqId":"VlUEPcsRM69cYoPWnHQ9","level":3,"time":"2019-10-01T09:15:28+00:00","remoteAddr":"192.168.1.2","user":"skjnldsv","app":"lib","method":"GET","url":"/index.php/apps/contacts/","message":"ResourceLocator can not find a web root (root: /var/snap/nextcloud/16232/nextcloud/extra-apps/contacts, file: index.php/css/contacts/1e49-fcfc-contacts.css?v=743417092b8f695fd7f1c09520bde4e3, webRoot: , throw: true)","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36","version":"16.0.5.1","id":"5d931b23b5fd1"}
```

**Comment by skjnldsv** [comment] 2019-10-01 09:31
> (disabling and removing the app using the web interface should do, right?)

yes.
@sk22 can you share an  `occ config:list system` here  please?

**Comment by sk22** [comment] 2019-10-01 10:06
@skjnldsv sorry this took a while - here it is:

```json
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.108",
            "nextcloud.strimcom.at",
            "strimcom.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "overwrite.cli.url": "http:\/\/10.0.0.108",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "has_rebuilt_cache": true,
        "loglevel": 2,
        "app_install_overwrite": [
            "occweb"
        ]
    }
}

```

**Comment by Mesman-S** [comment] 2019-10-01 18:35
```
Error: Could not find initial state of contacts initialstate.js:31:8
    m initialstate.js:31
    loadState index.js:10
    <anonymous> rfcProps.js:29
    Webpack 3
```

```
Could not find initial state of contacts initialstate.js:30:10
    m initialstate.js:30
    loadState index.js:10
    <anonymous> rfcProps.js:29
    Webpack 3
```

I have the same issue after updating to Contacts 3.1.4. Running the stable snap version 16.0.5 on Raspbian 10. Browser is Firefox 69.0.1 on Windows 10.

**Comment by skjnldsv** [comment] 2019-10-02 08:37
Duplicate of https://github.com/nextcloud/nextcloud-snap/issues/1130

**Closed by skjnldsv** 2019-10-02 08:37 UTC
Labels: 0. Needs triage, bug, high, needs info
