### ISSUE TITLE
macos contacts app does not reflect adding or deleting contacts

### ISSUE THREAD

**Issue by tiiiecherle** [nextcloud/contacts#575] opened 2018-06-24 09:14 UTC
### Steps to reproduce
1. complete nextcloud / php / nginx (incl. well-known rewrite) install on archlinux with all packages up-to-date
2. activate contacts app in nextcloud interface
3. connect to nextcloud user address book with macos 10.13.5 contacts app as client
4. connect to nextcloud user address book with ios 11.4 contacts app as client

### Expected behaviour
Both clients should be able to see, read and write to the address book and should reflect changes, additions and deletions.

### Actual behaviour
The behaviour on the ios client is fine and matches everything that happens in the the nextlcoud contacts. 
The problem occurs with the macos contacts client. If you create a contact on macos it gets synced and appears in nextcloud. But a contact created in nextcloud or in ios does not show up in macos. And if you delete a contact in nextcloud or ios it does not get deleted in macos contacts app.

### Server configuration

**Operating system**:
archlinux
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.2.7-1
**Nextcloud version:** (see Nextcloud admin page)
13.0.4-1
**Contacts version:** (see Nextcloud apps page)
2.1.5-1
**Updated from an older Nextcloud or fresh install:**
fresh contacts install
**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - files_external
  - tasks
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.1.205",
            "mydomain.org",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "13.0.4.0",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": false,
        "skeletondirectory": "\/usr\/share\/webapps\/nextcloud\/core\/skeleton",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "http:\/\/localhost",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": false,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "appcodechecker": true,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "syslog_tag": "Nextcloud",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": true,
        "log_rotate_size": false,
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/#install-clients",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": -1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "ldapUserCleanupInterval": 51,
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
        "maintenance": false,
        "singleuser": false,
        "openssl": [],
        "enable_certificate_management": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcached_options": {
            "14": 50,
            "15": 50,
            "19": 50,
            "20": 50,
            "8": 50,
            "-1001": true,
            "16": true,
            "18": true
        },
        "cache_path": "",
        "cache_chunk_gc_ttl": 86400,
        "sharing.managerFactory": "\\OC\\Share20\\ProviderFactory",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "sqlite.journal_mode": "DELETE",
        "mysql.utf8mb4": true,
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql",
            "oci"
        ],
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "theme": "custom",
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "2.0.0",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "mount_file": "\/data\/cloud\/nextcloud\/data\/mount.json",
        "filesystem_cache_readonly": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "upgrade.disable-web": false,
        "debug": false,
        "data-fingerprint": "",
        "copied_sample_config": false,
        "dbport": "",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari
**Operating system:**
macos 10.13.5
ios 11.4
**CardDAV-clients:**
macos contacts
ios addresss book

#### Web server error log
the webserver log starts with creating a new contact on ios, then syncs it to nextcloud and then opening macos contacts, the contact does not show up in macos contacts afterwards
```
172.16.2.40 - - [24/Jun/2018:11:06:10 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 401 569 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:11 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 285 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - - [24/Jun/2018:11:06:11 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 401 569 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:11 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 207 1495 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - - [24/Jun/2018:11:06:11 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 401 569 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:11 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 207 3393 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:12 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 285 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:15 +0200] "OPTIONS /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 200 0 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - - [24/Jun/2018:11:06:17 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 401 569 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:17 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 207 1495 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - - [24/Jun/2018:11:06:17 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 401 569 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:18 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 207 3400 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:19 +0200] "PUT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/E044DF69-9E12-466A-907D-F5291BFBC52B.vcf HTTP/1.1" 201 0 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:19 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 600 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:22 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 285 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:24 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 207 1495 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:25 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 207 3393 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:25 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 285 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.40 - user [24/Jun/2018:11:06:26 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 207 285 "-" "iOS/12.0 (16A5308e) dataaccessd/1.0"
172.16.2.32 - - [24/Jun/2018:11:06:54 +0200] "OPTIONS /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
172.16.2.32 - user [24/Jun/2018:11:06:54 +0200] "OPTIONS /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 200 0 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
172.16.2.32 - user [24/Jun/2018:11:06:54 +0200] "PROPFIND /nextcloud/remote.php/dav/principals/users/user/ HTTP/1.1" 207 1495 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
172.16.2.32 - - [24/Jun/2018:11:06:54 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
172.16.2.32 - user [24/Jun/2018:11:06:54 +0200] "PROPFIND /nextcloud/remote.php/dav/addressbooks/users/user/ HTTP/1.1" 207 3400 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
172.16.2.32 - user [24/Jun/2018:11:06:55 +0200] "REPORT /nextcloud/remote.php/dav/addressbooks/users/user/contacts/ HTTP/1.1" 403 5 "-" "Mac OS X/10.13.5 (17F77) AddressBook/1808.7"
```

#### Nextcloud log (data/nextcloud.log)
```
no log entries
```

**Comment by skjnldsv** [comment] 2018-06-29 13:54
Hello :)
Have you checked the other issues related to mac os sync please?
https://help.nextcloud.com/t/discussion-adressbooks-sync-with-macos/25760

This is not related to nextcloud

**Comment by tiiiecherle** [comment] 2018-06-29 14:35
Hey, 

yes I have checked about the other macos issues, but it does not seem to be related at all. 

1   I did not try to sync multiple address books or groups, just one. 
2   The rewrite that is often forgotten in nginx is implemented and working correctly. 
3   The connection from macos client is done correctly.
4   The connection itself to the address book is working.

I did a lot of research before posting this. Syncing with macos is working with other tools like baikal or radicale. So it is highly plausible that this issue is nextcloud related.

Please read the specified issue description in the post above and please reopen the issue.

If you have any questions or if I can try to help like testing I`ll happily do that.

Thanks

**Comment by skjnldsv** [comment] 2018-06-29 14:45
Okay, let's do some debug then!
1. Create a contact with the nextcloud app
2. ensure the contact is saved on nextcloud (if you refresh the contacts app and it appear again, then it's ok)
3. retrieve the contact filename (right click the download link, it should contain the filename)
4. connect to webdav with finder or any kind of mac webdav browser and use the current addressbook webdav url (https://YOURDOMAIN/remote.php/dav/addressbooks/users/USERNAME/)
5. search for the filename you noted earlier

If it's here, then it is not a nextcloud issue but is related to mac and the synchronisation or your config

**Comment by skjnldsv** [comment] 2018-06-29 15:33
Yes, I still wanted to try to make sure we're on the same page for this.
nextcloud use the webdav standard. Since nextcloud seems to behave properly according to your tests, the only issue we could have here is the software you're using to communicate with nextcloud doesn't behave properly or does not follow the webdav standard.

Therefore, I don't see much what we can do.
I suggest you try searching the issue on the mac os contacts manager since it seems to come from here.
i'm sorry, this is frustrating, but there is not much I can do.

Could it be that the mac software does not update the information automatically?
I mean, when you create a contact, it must understand it needs to send the new one, but maybe you need to trigger the sync somehow?

**Comment by tiiiecherle** [comment] 2018-06-29 15:39
Thanks for the explanation. You can force a sync by really quitting the contacts app and reopen it. When reopening a sync is forced.

What`s strange to me is that baikal and radicale work perfectly. If for all carddav software the issue would be the same I would agree with you that it is a mac issue.

But as it`s not it seems to me that nextcloud contacts does have a problem writing to the macos contacts app.

**Comment by skjnldsv** [comment] 2018-06-29 15:40
> Thanks for the explanation. You can force a sync by really quitting the contacts app and reopen it. When reopening a sync is forced.

So if you do that, the sync is done properly?

**Comment by tiiiecherle** [comment] 2018-06-29 15:52
With radicale or baikal as carddav server yes, with nextcloud as carddav server no.

More precise, yes one way and no the other way. macos contacs does write to nextcloud but nextcloud does not write to macos contacts. So if a contact is added on macos it gets synced to nextcloud but if a contact is added in nextcloud it does not appear on macos.

**Comment by skjnldsv** [comment] 2018-06-29 15:56
Do you see requests in the access log coming from the mac contacts app?

**Comment by tiiiecherle** [comment] 2018-06-29 16:06
In which log? I added the nginx log to the first post. As stated the webserver log posted starts with creating a new contact on ios, then syncs it to nextcloud and then opening macos contacts, the contact does not show up in macos contacts afterwards.

**Comment by skjnldsv** [comment] 2018-06-29 16:09
On the webserver's. :)
Yes, I saw that, but I did not know if the entries were general or precisely linked to mac contact's app

**Comment by tiiiecherle** [comment] 2018-06-29 16:11
yes, the log is from nginx and reflects exactly the time of the described events ;)

**Comment by tiiiecherle** [comment] 2018-06-29 16:11
sorry, just hit the wrong button when closing ;)

**Comment by tiiiecherle** [comment] 2018-07-05 08:30
as the label "needs info" is still applied, is there anything I can help with additionally?

**Comment by TomFreudenberg** [comment] 2018-09-03 18:09
Hi, I can confirm this issue from @tiiiecherle 

Just tested with a nextcloud demo test instance and my Mac OSX contacts app.

BUT ... in my case it seems that this is happen due to an issue on mac osx contacts app. Always when I changed something on a card from the contact app, all other changes where correctly synced after that. It looks like the "sync download" might have some issue on osx app?

Cheers
Tom

**Comment by brettferrell** [comment] 2019-01-29 17:17
Just as a data point, I use iOS and MacOS, but with a NC15 (contacts 3.0.2) instance on Ubuntu (16.04), and I just created two contacts on the web interface for testing another bug, and they did create OK on my MacOS (10.14.3) contacts app just fine, so it seems likely something in the nginx or arch side maybe.

**Comment by tiiiecherle** [comment] 2019-03-19 08:45
I took some time to try this again yesterday with next cloud 15.0.5 on archlinux with all packages up-to-date and proper configuration. macOS is also up-to-date with 10.14.3. The issue still persists. macOS contacts sync once when adding the account, no more syncs possible afterwards.

**Comment by christiaan2b** [comment] 2020-05-08 16:38
This problem still exists :(

**Comment by TomFreudenberg** [comment] 2020-05-28 19:32
Can confirm - still exists

**Comment by nachtbraker** [comment] 2020-06-29 23:19
Confirmed here too. I had 2 contacts in Nextcloud. I added the profile to my Mac (Mojave 10.14.6). I edited one contact and deleted the other one. These changes are only visible on the Mac and did not sync with the web view of Nextcloud.

**Comment by skjnldsv** [comment] 2020-07-14 11:51
DO you have multiple addressbooks?

**Comment by TomFreudenberg** [comment] 2020-07-14 12:25
yes, from different mail accounts but only one from nextcloud

**Comment by nachtbraker** [comment] 2020-07-14 13:02
In my case I have two calendars from NextCloud and a bunch of iCloud ones.

**Comment by skjnldsv** [comment] 2020-07-14 14:41
Can any of you see PUT requests to your nextcloud server from your Apple devices?
If not, this is an Apple issue (my guess)

**Comment by nachtbraker** [comment] 2020-07-14 17:31
I see a put request when I add a new contact from MacOS:

192.168.200.101 - - [14/Jul/2020:19:20:20 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 401 557
192.168.200.101 - ben [14/Jul/2020:19:20:20 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 207 3341
192.168.200.101 - ben [14/Jul/2020:19:20:21 +0200] "PUT /remote.php/dav/addressbooks/users/ben/contacts/ee973461-b0e4-4900-8acc-8dd7ffbf6722.vcf HTTP/1.1" 201 -
192.168.200.101 - ben [14/Jul/2020:19:20:22 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 207 578

This created the contact on NextCloud. Next I edit it from my iPhone and change a field in that record:

192.168.200.65 - - [14/Jul/2020:19:23:44 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 401 557
192.168.200.65 - ben [14/Jul/2020:19:23:44 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 207 883
192.168.200.65 - ben [14/Jul/2020:19:23:46 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 207 1248
192.168.200.65 - - [14/Jul/2020:19:23:48 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 401 557
192.168.200.65 - ben [14/Jul/2020:19:23:48 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 207 3341
192.168.200.65 - ben [14/Jul/2020:19:23:50 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 207 273
192.168.200.65 - - [14/Jul/2020:19:25:29 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 401 557
192.168.200.65 - ben [14/Jul/2020:19:25:30 +0200] "PROPFIND /remote.php/dav/addressbooks/users/ben/ HTTP/1.1" 207 3341
192.168.200.65 - ben [14/Jul/2020:19:25:31 +0200] "PUT /remote.php/dav/addressbooks/users/ben/contacts/ee973461-b0e4-4900-8acc-8dd7ffbf6722.vcf HTTP/1.1" 204 -
192.168.200.65 - ben [14/Jul/2020:19:25:32 +0200] "REPORT /remote.php/dav/addressbooks/users/ben/contacts/ HTTP/1.1" 207 578

But in NextCloud the change is not visible. But here is the odd thing, sometimes it *does* work. I tried it a few times, also by quiting apps, reloading the NextCloud page, etc.

I don't know if this matters, but the calendar works fine from MacOS and iOS. It is just the addressbook that's giving me trouble. I added both in one go using the Apple profile option in NextCloud.

**Comment by skjnldsv** [comment] 2020-07-14 18:28
For every PUT request, can you confirm changes are properly visible?

**Comment by skjnldsv** [comment] 2020-09-06 14:51
Still exists?
I'd close this in favour of #399

**Closed by skjnldsv** 2020-09-06 14:51 UTC
Labels: 0. Needs triage, bug

**Comment by nachtbraker** [comment] 2020-09-06 15:45
@skjnldsv We've upgrade to v19.0.2 since. I haven't seen the problem since.

**Comment by skjnldsv** [comment] 2020-09-06 15:46
Good to hear! :)
Maybe MacOS fixed it too :shrug:
