### ISSUE TITLE
spinning wheel in contacts NC 11

### ISSUE THREAD

**Issue by wdehoog** [nextcloud/contacts#145] opened 2017-02-25 14:26 UTC
Just upgraded to nextcloud 11 (from owncloud 9.1). Contacts app only shows the spinning wheel. Firefox web console shows exception thrown at line 488 of angular-cache.js from apps/contacts/js/vendor/angular-cache/dist. 

When I set a breakpoint I see 'key' is an array. Looks like the UID from vcard data:

  UID:cn=XXXX XXXX,ou=People,dc=exalondelft,dc=nl

(seen in vcards exported using remote.php/dav/addressbooks/users/exalon/contacts?export)

**Comment by skjnldsv** [comment] 2017-02-26 08:05
Could you post the full error log please?

**Comment by wdehoog** [comment] 2017-02-26 09:14
What error log do you mean? This is happening in the browser.

The console shows: Error: key must be a string! angular-cache.js:419:17

**Comment by skjnldsv** [comment] 2017-02-26 09:19
The error in console should be much bigger. :)

**Comment by wdehoog** [comment] 2017-02-27 21:00
Hopefully this is big enough for you then. ![contacts-err-1](https://cloud.githubusercontent.com/assets/3353303/23379660/13f8f3aa-fd38-11e6-92c0-afe3fee8f722.png)

**Comment by wdehoog** [comment] 2017-02-27 21:04
Thisone is with the breakpoint. ![contacts-err-2](https://cloud.githubusercontent.com/assets/3353303/23379808/a428a92a-fd38-11e6-94b6-170405163ed0.png)

**Comment by anoma** [comment] 2017-03-07 15:28
Just updated from 10.0.1 and received the spinning loading wheel which appears to go on indefinitely.

If I click the "new contact" button I immediately see all contacts.
Pressing the "new contact" button again does nothing.
Clicking on any of the now revealed contacts also does nothing.

No difference in behavior between FF 51.0.1 and Chrome  56.0.2924.87.
No database bloat as reported in https://github.com/nextcloud/contacts/issues/153.
I can see a `nextcloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map` error in the nginx log.

Access is via a nginx SSL reverse proxy.

I have limited capability to provide logs as it is a private install but will do what I can.

**Comment by irgendwie** [comment] 2017-03-07 17:29
@anoma 

> I can see a nextcloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map error in the nginx log.


what kind of error?

**Comment by wdehoog** [comment] 2017-03-07 21:59
To me the problem seems to be that the uid of the vcard is turned into an array so it cannot be used anymore as a string to identify the vcard. Sorry but I don't understand what additional logs could be needed.

**Comment by anoma** [comment] 2017-03-08 08:22
Since I was specifically asked

`2017/03/07 15:21:02 [error] 304#0: *9406 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /nextcloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx.yyy.zzz:443"`

Domain redacted. However I have not seen this error since and @wdehoog seem far more on point.

**Comment by anoma** [comment] 2017-03-13 09:41
Given that I am in a fully broken webgui state can anyone suggest a means to backup the contacts, delete existing an re-import (in the context of this error).

**Comment by wdehoog** [comment] 2017-03-13 10:21
I do not know how to remove all current vcards from the database but you can export from the commandline using for example:

  curl -u <user> http://<host>/nextcloud/remote.php/dav/addressbooks/users/<ocuser>/contacts?export > contacs-export.vcf

(replace <user>, <host> and <ocuser> with your local values.)

then fix the UIDs in contacs-export.vcf and then import them using the web interface. But the old ones really need to be removed first.

**Comment by CamZie** [comment] 2017-03-20 09:41
One of our customers is also having the same issue. We have version 10.0.2 and the size of the contact affected is 34MB and occurs on the browser (spinning wheel) and DavDroid. The error message is the following:

[error] 9178#9178: *2948581 upstream timed out (110: Connection timed out) while reading response header from upstream

We are using the nextcloud recommended nginx configuration and added the following extra ones, which we thought would solve the timeout problem but it did not seem to do it:

fastcgi_read_timeout 300;
fastcgi_connect_timeout 300;

**Comment by anoma** [comment] 2017-03-20 12:30
@wdehoog 

I managed to export one of my contact lists however the main contact list export fails with

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\VObject\ParseException</s:exception>
  <s:message>Unsupported CHARSET: utf-8</s:message>
</d:error>
```

anyone know if this is a red herring or relevant to this ticket.

**Comment by anoma** [comment] 2017-03-27 08:47
OK so I am at the point now where my only way forward is to remove NextCloud and try to recover contacts from client side contact exports. Given than my entire install exists only to share contacts and calendar I find this disappointing (although to be fair based on the volume of posts here I seem to have hit an edge case).

Last call for any information anyone wants before i kill this thing

**Comment by wdehoog** [comment] 2017-05-17 09:38
We have exported all contacts (1068). Deleted them from nextcloud. Replaced all UID's in the vcards file and imported them back into nextcloud. Now the contacts app shows them.

(Some contacts could not  be imported back but that is another subject.)

**Comment by jancborchardt** [comment] 2017-07-04 18:30
@nextcloud/contacts @nextcloud/javascript can you help debug this please?

**Comment by wdehoog** [comment] 2017-07-05 08:45
What else do you expect me to do? I showed where the error occurs, what causes the error and how we changed the data to prevent the error from happening. 
Do you want me to fix the contacts javascript? I took a quick look but it was not obvious where it goes wrong (why is the UID value parsed instead of treated a single string) and diving into the contacts code base is not something I would like to do.

**Comment by jancborchardt** [comment] 2017-07-05 09:42
@wdehoog the info you supplied is good, I merely notified the relevant people who could help debugging or fixing this. :)

**Comment by skjnldsv** [comment] 2017-07-26 22:22
uids are duplicate of #175 
Closing this one for readability.

**Closed by skjnldsv** 2017-07-26 22:22 UTC
Labels: bug, high, needs info
