### ISSUE TITLE
"groupname (new group)" stored

### ISSUE THREAD

**Issue by lual** [nextcloud/contacts#444] opened 2017-11-24 00:19 UTC
### Steps to reproduce
1. Open any of your contacts
2. Click in the Groups Textbox and Type a new Group Name. E.g. "mygroup"
3. A suggestion will appear "mygroup (new group)"
4. If you just hit Enter - everything is as expected, but if you select the suggestion "mygroup (new group)" is stored. 

### Expected behaviour
"mygroup" should be saved.

### Actual behaviour
"mygroup (new group)" was saved.

### Server configuration

**PHP version:**
7.0.19

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Contacts version:** (see Nextcloud apps page)
 2.0.1

### Client configuration
**Browser:**
FF 57.0 
**Operating system:**
linux

**Comment by michaelof** [comment] 2017-12-09 23:45
Same on NC 12.0.4

FF 52.5 ESR, 
OpenSuse Leap 42.3

**Comment by kelmas** [comment] 2017-12-25 19:42
I can confirm the issue.

**Comment by fapsi** [comment] 2017-12-28 15:46
I can confirm this issue too. 
But I found a possible workaround: After typing the group-name you can press "TAB" and the group is created without the string " (new group)".

**Comment by michaelof** [comment] 2017-12-28 19:41
thanks for the cool workaround, fapsi!

**Comment by Benestar** [comment] 2018-02-11 16:39
This is actually a bug in angular-ui. https://github.com/angular-ui/ui-select/issues/1806

Apparently there is already a fix for this which is awaiting review since 9 months... https://github.com/angular-ui/ui-select/pull/1943

The quick 'n dirty fix would be to add something like `.replace(' (new group)', '')` in the right place.

**Comment by gorn** [comment] 2018-02-13 11:32
It seems there is some effort to change it on the way https://github.com/angular-ui/ui-select/pull/1943

**Comment by Henni** [comment] 2018-02-13 18:53
@Benestar `.replace(' (new group)', '')` might be an option, even though we have to respect translations here.

I doubt ui-select will fix this. It doesn't seem maintained anymore (old AngularJS slowly falling apart :frowning_face: )

**Comment by skjnldsv** [comment] 2018-02-13 18:55
@Henni the pr fix in the select repo has been updated all day. Maybe if we cross our fingers! 🙏

**Comment by gorn** [comment] 2018-02-27 19:42
I see https://github.com/angular-ui/ui-select/pull/1943 quite active, so there is a hope.

**Comment by boldt** [comment] 2018-02-28 13:32
I can confirm that issue on the nextcloud docker image: `nextcloud:13.0.0`

**Comment by jancborchardt** [comment] 2018-05-04 13:58
Upping this to medium and help wanted since it seems to occur quite often. @nextcloud/javascript any ideas how to fix this?

**Comment by gorn** [comment] 2018-06-18 11:50
angular-ui/ui-select#1943 has been closed, time to pull it to nextcloud

**Comment by skjnldsv** [comment] 2018-06-18 11:53
@gorn pr is still opened?

**Comment by gorn** [comment] 2018-06-18 13:39
It is closed, but maybe with a manual hotfix (did not checked). If so, it might be easier to accept the upstream solution.

**Comment by jaller94** [comment] 2018-07-17 05:18
I don’t see that angular-ui/ui-select#1943 was merged. It seems still open as of today.

**Comment by Cortek29** [comment] 2018-07-27 12:55
My tips (for waiting) : under "Thunderbird", if you have distant address book (CalDav), you can rename the category field manualy.

**Comment by michaelof** [comment] 2018-07-27 13:50
@Cortek29: Sounded like a wonderful idea, at first, BUT: 

Be  careful, you in fact can rename entries in the "category" field of Thunderbird's addressbook, but this will create a NEW group!

 E.g:
-  15 contacts in "groupA".
-  select one of these in TB's addressbook
-  rename "category" to "groupA_1"

Result in Nextcloud: 1 contact in "groupA_1", 14 still in "groupA", unchanged.

Maybe, if "renamed" group existed already, reassign to to existing group, haven't tested.

BTW: Afaik we're talking about cardDAV here, not calDAV. But doesn't matter :-)

**Comment by Cortek29** [comment] 2018-07-27 14:00
@michaelof :+1: 
Yes, cardDav, sorry :)

I try it successfully on my system. No problems. No duplicate, no new group.

But, the NextCloud is not mine, it's at my office, i don't have version or admin access...

**Comment by michaelof** [comment] 2018-07-27 14:10
@Cortek29: I've extended my last post during you've added you latest comment, not sure if you'll get a github notification about that. Which version of SOGo Connector are you using?

**Comment by michaelof** [comment] 2018-07-27 14:30
@Cortek29: P.S.: More ugly on my side: I can switch the group back to the original one, NC is updated at once by SOGo. And, as usual, NC drops "new" group, as not used anymore, in my example. 
But SOGo conenctor will NOT delete these once used group, TB setting tab for SOGo lists all "categories" used, and offers a "delete" button. But nothing happens when clicked :-(
Again: Maybe fixed with 31.0.6 or later. 

And we should not get to off-topic for a NC issue, probably, I'll stop now.

**Comment by Cortek29** [comment] 2018-07-27 15:19
Sorry, but on my side, I use only. Lightning as manager of diaries with thunderbird, my OS is Debian fork (Mint).
It was after a problem of category renaming that I came across this discussion. I just explained my temporary solution. I do not use SOgo
I wish you good luck...

**Comment by joe-pirat** [comment] 2018-07-31 22:00
the only way I know is : 
that is a bug at the moment (08/2018) it only helps to import a .vcf file which leads the desired category name. 
writhe a file with the content:
-------
BEGIN: VCARD
VERSION 3.0
FN: AAA 1
NOTE 1
NOTE 1
2: TYPE = WORK, VOICE; TEL
3: TYPE = HOME, VOICE; TEL
TEL; TYPE = FAX: 0351 808
UID:
CATEGORIES: new-group
REV:
1@1.de: TYPE = HOME; EMAIL
END: VCARD

Save as a.vcf and import to the contacts
This creates a new group "new-group" without the stupid brackets. So you can also create empty contacts so you have not always have to click the necessary fields - which I find very annoying.
Also you can have 2 notes Create fields.  ;)

**Comment by jaller94** [comment] 2018-07-31 23:43
I can still create groups without "(new group)" by pressing Enter instead
of clicking the label.

**Closed** 2018-10-01 16:08 UTC
Labels: 1. to develop, bug, help wanted, medium

**Comment by walley** [comment] 2018-11-20 13:30
is it fixed in nextcloud 14? because 13 is stil doing it.

**Comment by skjnldsv** [comment] 2018-11-20 13:36
@walley This is fixed in the 3.0.0 version of contacts
