### ISSUE TITLE
vCards Messed up and apple groups don't work

### ISSUE THREAD

**Issue by ZappZero** [nextcloud/contacts#1637] opened 2020-05-23 21:24 UTC
![vCard_Browser](https://user-images.githubusercontent.com/1382952/82740979-f95ebe80-9d4d-11ea-8793-d9c9e23fa7cd.png)
![vCard_iPhone](https://user-images.githubusercontent.com/1382952/82740981-fb288200-9d4d-11ea-9de3-19ef164da5e8.png)

Hi!

I think since the update to 3.3.0 the vCards on are messed up. I have >400 contacts from apple "Contacts". Well sorted and organized. 

Since one of the last updates my groups will not show up on iPhone, nor is it possible to create new groups. In the browser view of NextCloud the old groups will display as "unsorted contacts". 

The vCards - created anywhere on mac or via browser and NextCloud contacts, or via iPhone - receive unkown field names. F. e. all "Mobile" tags are now tagged as ""CELL" (with one leading "). The tag "Privat" (phone number) is now "Home and "Arbeit" is now "WORK-

**Comment by ZappZero** [comment] 2020-05-24 08:18
Not important anymore, I switched to "radicale".
I'm sorry, but contacts are too important to mess them up!

Thank you for all your great work! :-)

**Comment by skjnldsv** [comment] 2020-06-02 10:28
All of those are duplicate of other issues.

Please use the search function. See #213 or #1107 ... etc

**Closed by skjnldsv** 2020-06-02 10:28 UTC
Labels: 0. Needs triage, bug
