### ISSUE TITLE
Custom Label Support for iOS Sync

### ISSUE THREAD

**Issue by smallTrogdor** [nextcloud/contacts#1901] opened 2020-10-30 17:01 UTC
Hi everyone,

this is my first issue here on nextCloud, I am fairly new to the whole project. Please bare that in mind when reading this.

**Is your feature request related to a problem? Please describe.**
I like to use custom labels for my contacts in my OS address book (see the screenshot of the address book app below). It seems however, that these custom fields are not synced at all. The information is completely lost. Of course, I do not know if Apple just does not include this information in the DAV format or does not include these custom fields at all. Then the problem is of course not solvable within this project.

**Describe the solution you'd like**
imo, the best solution is to support custom labels for address book entries.

**Describe alternatives you've considered**
A simple default to a standard field tag instead of not syncing is great.

**Additional context**
macOS: 10.15.7
nextCloudPiVersion: v1.31.0
distribution | Raspbian GNU/Linux 10 \n \l

address book in OS:
![Screenshot 2020-10-30 at 17 59 00](https://user-images.githubusercontent.com/30844036/97734565-a0077200-1ad9-11eb-8211-fae0b1709734.png)

entry on nextCloud:
![Screenshot 2020-10-30 at 18 01 01](https://user-images.githubusercontent.com/30844036/97734755-e3fa7700-1ad9-11eb-8a24-9d27d4019035.png)

**Comment by skjnldsv** [comment] 2020-10-30 19:02
Please export the contact from iOs and post it here

**Comment by smallTrogdor** [comment] 2020-10-30 20:07
> Please export the contact from iOs and post it here

Sure, here is the file as zip
[Hello World.vcf.zip](https://github.com/nextcloud/contacts/files/5467401/Hello.World.vcf.zip)

**Comment by skjnldsv** [comment] 2020-10-31 10:07
Yep, duplicate of #1842

**Closed by skjnldsv** 2020-10-31 10:07 UTC
Labels: 0. Needs triage, enhancement
