### ISSUE TITLE
Some fields with custom names are disappearing

### ISSUE THREAD

**Issue by github-cli** [nextcloud/contacts#1826] opened 2020-10-05 19:54 UTC
### Steps to reproduce
Edit a contacts phone number, click on the name of the number (e.g. Mobile) and manually type in some text like "iPhone"
After that the item will simply disappear from the UI,however these custom names still sync correctly to e.g. iPhones

### Expected behaviour
I expect to be able to see all forms/fields

### Actual behaviour
custom named items seem to disappear in NextCloud 20

## Server configuration detail

**Operating system:** Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, json, igbinary, apcu, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, redis, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.0 - 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from NextCloud 19

**Where did you install Nextcloud from:** install script from hanssonit.se

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - admin_audit: 1.10.0
 - announcementcenter: 4.0.0
 - apporder: 0.11.0
 - audioplayer: 2.12.0
 - audioplayer_editor: 0.3.0
 - bookmarks: 3.4.1
 - breezedark: 19.0.4
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - camerarawpreviews: 0.7.8
 - checksum: 0.4.5
 - cloud_federation_api: 1.3.0
 - contacts: 3.4.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - deck: 1.1.0
 - duplicatefinder: 0.0.2
 - external: 3.7.0
 - extract: 1.2.4
 - federatedfilesharing: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_external_dropbox: 1.4.3
 - files_external_gdrive: 0.4.0
 - files_fulltextsearch: 1.4.3
 - files_pdfviewer: 2.0.1
 - files_retention: 1.8.2
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - fulltextsearch: 1.4.2
 - fulltextsearch_elasticsearch: 1.5.2
 - gallery: 18.5.0
 - groupfolders: 8.0.0
 - impersonate: 1.7.0
 - integration_discourse: 0.0.3
 - integration_gitlab: 0.0.4
 - issuetemplate: 0.7.0
 - keeweb: 0.6.3
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.5.0
 - maps: 0.1.8
 - nextbackup: 20.9.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - password_policy: 1.10.1
 - passwords: 2020.10.0
 - phonetrack: 0.6.5
 - previewgenerator: 3.0.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - ransomware_detection: 0.8.0
 - ransomware_protection: 1.8.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.4
 - richdocumentscode: 4.2.800
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - smb_test: 0.2.6
 - socialsharing_email: 2.1.0
 - survey_client: 1.8.0
 - suspicious_login: 3.2.1
 - systemtags: 1.10.0
 - tasks: 0.13.3
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflow_ocr: 1.19.0
 - workflowengine: 2.2.0
Disabled:
 - afterlogic
 - comments
 - encryption
 - facerecognition
 - federation
 - files_mindmap
 - geoblocker
 - photos
 - rainloop
 - support
 - transmission
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.X.Y",
        "nextcloud.mydomain.com",
        "nextcloud.mydomain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "20.0.0.9",
    "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": "true",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "log.condition": {
        "apps": [
            "admin_audit"
        ]
    },
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1800",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "versions_retention_obligation": "auto, 365",
    "simpleSignUpLink.shown": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Europe\/Zurich",
    "htaccess.RewriteBase": "\/",
    "enable_previews": true,
    "enabledPreviewProviders": {
        "11": "OC\\Preview\\PNG",
        "12": "OC\\Preview\\JPEG",
        "13": "OC\\Preview\\GIF",
        "14": "OC\\Preview\\BMP",
        "15": "OC\\Preview\\MarkDown",
        "16": "OC\\Preview\\MP3",
        "17": "OC\\Preview\\TXT",
        "18": "OC\\Preview\\Movie"
    },
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "maintenance": false,
    "app_install_overwrite": [
        "files_external_dropbox",
        "files_external_gdrive",
        "keeweb",
        "gallery",
        "occweb",
        "workflow_ocr",
        "ransomware_detection",
        "audioplayer",
        "fulltextsearch",
        "fulltextsearch_elasticsearch",
        "files_fulltextsearch",
        "geoblocker",
        "audioplayer_editor",
        "breezedark",
        "extract",
        "checksum",
        "camerarawpreviews",
        "facerecognition",
        "files_retention"
    ],
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local,smb and sftp but for contacts its local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

no browser log included
</details>

**Comment by skjnldsv** [comment] 2020-10-05 20:31
Hi!
This is not made to enter custom type.
Duplicate of https://github.com/nextcloud/contacts/issues/1705

**Closed by skjnldsv** 2020-10-05 20:31 UTC
Labels: 0. Needs triage, bug
