### ISSUE TITLE
Contact added via iOS doesn't show address information

### ISSUE THREAD

**Issue by carslen** [nextcloud/contacts#940] opened 2019-02-18 16:31 UTC
⚠ Please report only issues corresponding to the contacts app for Nextcloud ⚠

Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues

If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts
__________________________________________________________________

### Describe the bug
New contacts added using iOS are not listed in webfrontend properly.

**To Reproduce**
1. Add new contact on iOS (incl. private/work phone and private/work address)
2. Search for new contact in nextcloud contact app
3. Wondering about the missing addresses
4. Wondering, that contact export/download from contact app contains the missing information

**Expected behavior**
Show all contact informations.

**Actual behavior**
Not all contact informations are listed. Also dropdown field for selecting "work/private/..." phone number identifier is no visible on webfrontend (but if you click on the blank area, the dropdown appears, but this is maybe a second issue)

**Screenshots**

### Server configuration
**Operating system**: Windows, Linux, MacOS...
```
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```
**Web server:** Apache, Nginx...
```
# rpm -qa | grep httpd
httpd-tools-2.4.6-88.el7.centos.x86_64
httpd-2.4.6-88.el7.centos.x86_64
```
**Database:** MariaDB, MySQL, PostgreSQL... 
```
# rpm -qa | grep maria
mariadb-libs-5.5.60-1.el7_5.x86_64
mariadb-5.5.60-1.el7_5.x86_64
mariadb-server-5.5.60-1.el7_5.x86_64
```
**PHP version:** 7.0, 7.1, 7.2...
```
# rpm -qa | grep php
php72w-mysql-7.2.14-1.w7.x86_64
php72w-cli-7.2.14-1.w7.x86_64
php72w-intl-7.2.14-1.w7.x86_64
php72w-pecl-imagick-3.4.3-1.2.w7.x86_64
php72w-common-7.2.14-1.w7.x86_64
php72w-pdo-7.2.14-1.w7.x86_64
php72w-xml-7.2.14-1.w7.x86_64
php72w-process-7.2.14-1.w7.x86_64
php72w-gd-7.2.14-1.w7.x86_64
mod_php72w-7.2.14-1.w7.x86_64
php72w-pecl-apcu-5.1.9-1.w7.x86_64
php72w-mbstring-7.2.14-1.w7.x86_64
php72w-opcache-7.2.14-1.w7.x86_64
php72w-pear-1.10.4-1.w7.noarch
```
**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Contacts version:** (see Nextcloud apps page)
3.0.3

**Updated from an older Nextcloud or fresh install:**
updated from older

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_external
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.clxe.de",
            "fin.clxe.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.clxe.de",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 86400,
        "theme": ""
    }
}
```

### Client configuration
**Browser:**
Safari

**Operating system:**
iOS 12.1.4

**CardDAV-clients:**
iOS internal

I'm skipping the logs part, unsure which would help you out. Attached you find:
- screenshot of iOS contact (https://cloud.clxe.de/index.php/s/7MkwBn69SbtcPkf)
- screenshot of contanct in webapp
![screenshot-webapp](https://user-images.githubusercontent.com/28647218/52964458-a3f56e00-33a2-11e9-828c-d26bb9f5e885.jpg)

- downloaded vcf contact file from webapp (renamed to txt)
[ABE2FECD-251A-4DD7-8983-57A98B633557.txt](https://github.com/nextcloud/contacts/files/2876562/ABE2FECD-251A-4DD7-8983-57A98B633557.txt)

**Comment by skjnldsv** [comment] 2019-02-19 08:08
Duplicate of #42

**Closed by skjnldsv** 2019-02-19 08:08 UTC
Labels: bug
