### ISSUE TITLE
Create Groups using VCard RFC standard

### ISSUE THREAD

**Issue by SebastianKrupinski** [nextcloud/contacts#4009] opened 2024-07-04 08:08 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Change the contacts groups mechanism to use the RFC recommended KIND and MEMBER property.

https://en.wikipedia.org/wiki/VCard

**Comment by SebastianKrupinski** [comment] 2024-07-04 08:17
Example...

```
     BEGIN:VCARD
     VERSION:4.0
     KIND:group
     FN:The Doe family
     MEMBER:urn:uuid:03a0e51f-d1aa-4385-8a53-e29025acd8af
     MEMBER:urn:uuid:b8767877-b4a1-4c70-9acc-505d3819e519
     END:VCARD

     BEGIN:VCARD
     VERSION:4.0
     FN:John Doe
     UID:urn:uuid:03a0e51f-d1aa-4385-8a53-e29025acd8af
     END:VCARD

     BEGIN:VCARD
     VERSION:4.0
     FN:Jane Doe
     UID:urn:uuid:b8767877-b4a1-4c70-9acc-505d3819e519
     END:VCARD

     BEGIN:VCARD
     VERSION:4.0
     KIND:group
     FN:Funky distribution list
     MEMBER:mailto:subscriber1@example.com
     MEMBER:xmpp:subscriber2@example.com
     MEMBER:sip:subscriber3@example.com
     MEMBER:tel:+1-418-555-5555
     END:VCARD
```

**Comment by ChristophWurst** [comment] 2024-10-15 15:15
Is this a duplicate of https://github.com/nextcloud/contacts/issues/213?

**Comment by SebastianKrupinski** [comment] 2024-10-15 23:33
Tested a couple of clients.

Apple Contacts (MacOS) has support.

```
BEGIN:VCARD
  VERSION:3.0
  X-ADDRESSBOOKSERVER-KIND:group
  PRODID:-//Apple Inc.//iOS 18.0.1//EN
  N:test-contacts-ios;;;;
  FN:test-contacts-ios
  UID:0E85507C-C67C-4C12-B4C2-E5EF19CF4E37
END:VCARD
```

emClient has support.

```
BEGIN:VCARD
  VERSION:4.0
  PRODID:-//MailClient.VObject/10.0.3530.0
  UID:urn:uuid:07ec6004-1c83-489f-b9ad-e706e884c1ce
  REV:20241015T232604Z
  KIND:group
  CATEGORIES:Business
  N;SORT-AS=This is a test:a test;This;is;;
  FN:This is a test
  MEMBER;X-CN=Testing Contact:mailto:testing@test.com
END:VCARD
```

**Comment by ChristophWurst** [comment] 2024-10-17 06:23
So is this now a duplicate or now?

**Comment by SebastianKrupinski** [comment] 2024-10-17 11:54
> So is this now a duplicate or now?

yes

**Closed** 2024-10-17 12:39 UTC
Labels: enhancement, 1. to develop, feature: contacts
