### ISSUE TITLE
Shared contact with birthday gets duplicated

### ISSUE THREAD

**Issue by maahrens** [nextcloud/contacts#1581] opened 2020-04-17 05:21 UTC
I’m running
- Nextcloud 18.0.3
- Contacts 3.2.0
- Calendar 2.0.2

… and observed the following issue:
1. Create new contact in personal address book
2. Set a birthday for this new account
3. Ensure the contact is saved
4. Change the contacts address book from personal to another shared address book
5. Reload all contacts
=> The contact is duplicated, because it now exists in the personal and the shared address book

Additional notes:
- Same issue does not occur when the contact has no birthday set - so it seems to be related to this element
- Deleting the duplicate and changing the contact’s address book again will also create the duplicate again
- This issue has some side effects on the birthday display in calendar app also - shared contacts birthdays do not always show up; running “occ dav:sync-birthday-calendar” will report duplicate calendar objects

**Comment by skjnldsv** [comment] 2020-04-17 07:46
Duplicate of https://github.com/nextcloud/contacts/issues/1275

**Comment by skjnldsv** [comment] 2020-04-17 07:48
Nooope, not a duplicate, my bad!

@maahrens the shared addressbook is shares with edit permissions?
You can create contacts to it?
Can you post screenshots? :)

**Comment by maahrens** [comment] 2020-04-19 21:55
@skjnldsv, I'm the owner of the shared address book and it is shared to other users with edit permissions.

Error when trying to switch user from personal to shared address book (similar error when running occ dav:sync-birthday-calendar):
`<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Calendar object with uid 762543ea-19b4-4508-9987-57ac051de318 already exists in this calendar collection.</s:message>
</d:error>`

I can create / move contacts to the shared calendar - no issues. But if a birthday exists the trouble starts.
Let me know what screen shots you need. Are you not at all able to reproduce?

I just updated to the latest version of calendar / contact app.

**Comment by skjnldsv** [comment] 2020-04-20 15:58
@georgehrke another issue with Birthday sync, does that ring a bell to you?

**Comment by georgehrke** [comment] 2020-04-20 17:43
Duplicate of https://github.com/nextcloud/server/issues/20492

**Closed by georgehrke** 2020-04-20 17:43 UTC
Labels: 0. Needs triage, bug, needs info
