### ISSUE TITLE
Unusable Web UI (Firefox 57)

### ISSUE THREAD

**Issue by tYYGH** [nextcloud/contacts#439] opened 2017-11-20 07:00 UTC
### Steps to reproduce
1. Load Contacts app in the Web UI

### Expected behaviour
Usable app.

### Actual behaviour
From looking at the page, you can tell something is off. Seriously so, unless some major UI overhaul took place in the last 6 months…
Items in the right pane (contacts) are unresponsive: nothing is clickable except the star.

### Server configuration
See here:
https://github.com/nextcloud/server/issues/7037

### Client configuration
**Browser:** Firefox 57

**Operating system:** Up-to-date Archlinux

**CardDAV-clients:** non applicable.

#### Web server error log
No error.

#### Nextcloud log (data/nextcloud.log)
No error.

#### Browser log
Nothing related to the Contacts :-(

In case this helps, I do have errors, though, in core.js:

```
Blocage du chargement du contenu mixte actif (mixed active content)
« http://fonts.gstatic.com/s/sourcesanspro/v11/toadOcfmlt9b38dHJxOBGOode0-EuMkY--TSyExeINg.woff2 »
                                                                     core.js:3:18259

Blocage du chargement du contenu mixte actif (mixed active content)
« http://fonts.gstatic.com/s/montserrat/v12/IQHow_FEYlDC4Gzy_m8fcoWiMMZ7xLd792ULpGE4W_Y.woff2 »
                                                                     core.js:3:18259

Blocage du chargement du contenu mixte actif (mixed active content)
« http://netdna.bootstrapcdn.com/font-awesome/3.2.1/font/fontawesome-webfont.woff?v=3.2.1 »
                                                                     core.js:3:18259

Blocage du chargement du contenu mixte actif (mixed active content)
« http://fonts.gstatic.com/s/raleway/v12/-_Ctzj9b56b8RgXW8FArifk_vArhqVIZ0nv9q090hN8.woff2 »
                                                                     core.js:3:18259

Blocage du chargement du contenu mixte actif (mixed active content)
« http://fonts.gstatic.com/s/raleway/v12/CcKI4k9un7TZVWzRVT-T8_k_vArhqVIZ0nv9q090hN8.woff2 »
                                                                     core.js:3:18259

Blocage du chargement du contenu mixte actif (mixed active content)
« http://sshudp.com//assets/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0 »
                                                                     core.js:3:18259
```
But I will open an independent issue for these, in nextcloud/server.

**Comment by tYYGH** [comment] 2017-11-20 07:15
What I get:
![bug_contacts](https://user-images.githubusercontent.com/5556825/33006448-b1d49594-cdca-11e7-8b5b-1d077393de9c.png)

**Comment by skjnldsv** [comment] 2017-11-20 08:25
Hi! Could you please clear your cache? :)

**Comment by tYYGH** [comment] 2017-11-21 07:27
Hi @skjnldsv . I did as you said. I get the same results. Here are the full logs:
* Firefox “access.log”: http://yalis.fr/public/contacts_firefox.log
* Firefox console: http://yalis.fr/public/contacts_firefox.har
* Nginx logs: http://yalis.fr/public/contacts_nginx.log
* Nextcloud/uwsgi logs: http://yalis.fr/public/contacts_nextcloud.log

**Comment by pixelipo** [comment] 2017-11-21 08:48
I am running NC12 on Firefox57 and Contacts app works as expected. @tYYGH can you please try opening in "safe mode"? You seem to be using a lot of Add-ons, and it's possible some of them are not compatible and are causing this.

**Comment by tYYGH** [comment] 2017-11-21 11:00
np, I have a Firefox profile dedicated to that: pristine state, no addon. I’ll test when I am at home…

**Comment by tYYGH** [comment] 2017-11-21 12:02
Following an eye-opening comment on Polls (https://github.com/nextcloud/polls/issues/249), I can confirm that taking the `scss` files out of app-dir “fixes” (works around) the issue (see https://github.com/nextcloud/polls/issues/230).

**Comment by pixelipo** [comment] 2017-11-21 15:10
I guess we can close this, then

**Closed by pixelipo** 2017-11-21 15:10 UTC

**Comment by jbmorgado** [comment] 2017-11-21 19:42
This shouldn't be closed, the bug it is still there, what was sugested was a woraround the bug.

**Comment by skjnldsv** [comment] 2017-11-21 20:49
It's not a contact issue though.

**Comment by pixelipo** [comment] 2017-11-21 20:50
Not really. There is nothing wrong with NC on a Firefox 57.

There is possibly an issue with the way apps fetch resources from core, which is clearly not what this issue is about.

**Comment by jbmorgado** [comment] 2017-11-21 21:13
I'm using NC in Firefox 57 and the bug is exactly this...

If you are so picky about the information we have to put in the bug report and then only go about checking if it works in your particular system, then why do you make people go trhough all the hassle to provide all that information in the first place?

If you don't want to fix the bug yourself just let it open so that some other contributor can do it in the future and so that the users can find a solution when they find this particular bug.

**Comment by splitt3r** [comment] 2017-11-22 11:02
@jbmorgado It seems to be an upstream bug wich is caused by something else. You could track the status [here](https://github.com/nextcloud/polls/issues/249) until somebody creates an issue in the server repo. Of course we appreciate you participation in the discussion / you issue creation.

**Comment by pixelipo** [comment] 2017-11-23 08:30
Most probably caused by https://github.com/nextcloud/server/issues/5289
