### ISSUE TITLE
Contact picture editing / adding / removing does not work in Firefox

### ISSUE THREAD

**Issue by evilphish** [nextcloud/contacts#227] opened 2017-06-02 21:16 UTC
### Steps to reproduce
1. Open any contact using firefox
2. Click the avatar image or placeholder

### Expected behaviour
A. The picture editing overlay should be shown for contacts that already have an avatar picture
B. The placeholder should have the "upload file" icon if the contact has no picture yet

### Actual behaviour
A. nothing (but it works using Chrome)
B. nothing and the upload icon is not shown (also works fine using Chrome)

### Server configuration
**Operating system**: Debian GNU/Linux 8.8 Jessie

**Web server:** Apache/2.4.10

**Database:** mariadb 10.0.30

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, apcu, curl, gd, gmp, imagick, intl, json, mcrypt, mysql, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, readline, sqlite3, mhash, apc, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** tar.bz2 from official website

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

**The content of config/config.php:**
```
{
    "instanceid": "ocwwphr339ub",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.phishtank.de"
    ],
    "datadirectory": "/var/www/nextcloud/data",
    "overwrite.cli.url": "https://cloud.phishtank.de",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "phishtank.de"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:** Linux Mint 18.1 Serena

#### Web server error log
```
No errors in the web server error log
```

#### Nextcloud log (data/nextcloud.log)
```
No errors in the nextcloud log
```
</details>

#### Browser log
```
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
Use of getAttributeNode() is deprecated. Use getAttribute() instead.  core.js:7:1714
Use of attributes’ nodeValue attribute is deprecated. Use value instead.  core.js:7:1714
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-WVovVnVLZG5kMEp1VE5iVWtTTEFPWFZ1MVA1VzROWmlpUGhPYmdzSGlRQT06QkxDVCs5Rk1QQnBiQ3BXT3BCS3dRRTBtblpFbmxMbzEwTDRIWGpoQnNEQT0=' 'unsafe-eval'”). Source: ondrop attribute on INPUT element.  contacts

```

**Comment by irgendwie** [comment] 2017-06-06 08:01
Thanks for the report! Unfortunately I'm not able to reproduce this issue.
I also don't see any relevant errors in the browser log, maybe some resources aren't correctly loaded in your setup? Do have any kind of special setup for your server?

> % firefox -V
Mozilla Firefox 53.0.3

**Comment by evilphish** [comment] 2017-06-06 08:19
You're welcome! I have no special setup, just standard Debian Jessie packages, nothing fancy. I have now upgraded to php 7 as I planned on doing that anyway. Interestingly enough the issue went away after the php upgrade. It makes absolutely no sense to me that the php version should have something to do with this behaviour as it seems more like a Browser / CSS / JS kind of issue to me. 
Switching back to php 5.6.30 results in the problem reappearing though so somehow this has an influence. Since I plan to stay on php 7 at least for me this issue is no longer relevant as of today. If you want to dig deeper into this I would be willing to help though.

**Comment by jancborchardt** [comment] 2017-07-04 16:41
Ok, closing issue since it went away. :)

**Closed by jancborchardt** 2017-07-04 16:41 UTC
Labels: needs info
