### ISSUE TITLE
Usernames are shown in Circle Member List instead of given name

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/contacts#3796] opened 2024-01-22 06:08 UTC
### Steps to reproduce

1. Use both LDAP and internal accounts
2. Create a circle from an LDAP account
3. Add members that are identified by LDAP and other identified internally
4. Only LDAP users are shown with their given name in some circle's members list, users that are authenticated internally are shown with their userid only what makes it difficult to tell who is who in larger circles

### Expected behavior

All users should be listed with their given name

### Actual behavior

Only users authenticated via LDAP are shown with their given name in serveral circles.

Example:
![image](https://github.com/nextcloud/contacts/assets/34368929/0ffe26c6-3afa-4017-92cb-cef4835c3bf6)

All userids beginning with "ocdu" are authenticated internally and userid and given name are set correctly, the others with their given name shown in this list are authenticated via LDAP.

First Idea: Circles ist using cached names in its database tables. I already hat a support case with an obsolete given name (after a marriage) that was sown correctly in the whole Nextcloud installation except for Circles. 

Could it be that a malfunction of an older Circles or Contacts version caused the wrong names to be cached in this case?

Maybe there's an undocumented command to refresh this cache?

### Server operating system

openSUSE

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.7.0
  - calendar: 4.6.4
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.3
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - support: 1.10.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - terms_of_service: 2.3.1
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0 (installed 2.7.0)
  - federation: 1.17.0 (installed 0.0.4)
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 1.1)
  - sharebymail: 1.17.0 (installed 1.0.1)
  - survey_client: 1.15.0 (installed 0.1.5)
  - suspicious_login: 5.0.0
  - updatenotification: 1.17.0 (installed 0.1.0)
  - whiteboard: 0.0.3 (installed 0.0.3)
```

### Nextcloud configuration

```Text
{
    "system": {
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.itk-rheinland.de",
            "cloud.itk.local",
            "lxcloudp01.itk.local",
            "lxcloudp02.itk.local",
            "lxcloudp03.itk.local",
            "lxcloudp04.itk.local",
            "lxcloudp05.itk.local",
            "localhost"
        ],
        "theme": "",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "appstoreenabled": true,
        "knowledgebaseenabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "updatechecker": false,
        "logtimezone": "Europe\/Berlin",
        "remember_login_cookie_lifetime": 1000,
        "session_lifetime": 900,
        "singleuser": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 4,
        "log_type": "syslog",
        "trashbin_retention_obligation": "auto",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.itk-rheinland.de",
        "default_language": "de_DE",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "auth.bruteforce.protection.enabled": false,
        "integrity.check.disabled": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "proxy": "wsaproxy.itk.local:8080",
        "defaultapp": "files",
        "mysql.utf8mb4": true,
        "disable_mobile_push": true,
        "data-fingerprint": "fc174b5fd6632ca4a252c91d01cd6d83",
        "app_install_overwrite": [
            "whiteboard"
        ]
    }
}
```

### Browser

any browser

### Client operating system

ayn os

### CardDAV-clients

n/a

### Web server error log

```Text
nothing to be seen there
```

**Comment by danxuliu** [comment] 2024-09-05 10:45
This looks like a duplicate of #3646, so it should be fixed with https://github.com/nextcloud/circles/pull/1682

> Maybe there's an undocumented command to refresh this cache?

You should be able to update it with `occ circles:maintenance --level=5 --force-refresh`, but please keep in mind that it does other things besides updating the display name cache and it could potentially cause a high system load while running.

**Comment by mejo-** [comment] 2024-09-10 11:56
Fixed by https://github.com/nextcloud/contacts/issues/3646

**Closed by mejo-** 2024-09-10 11:56 UTC
Labels: bug, feature: circles, 0. Needs triage
