### ISSUE TITLE
Manage multiple contacts in one step

### ISSUE THREAD

**Issue by MWL1701** [nextcloud/contacts#3054] opened 2022-10-16 15:38 UTC
### Is your feature request related to a problem? Please describe.

It's not related to a problem but would be very helpful to manage several contacts with one step.

### Describe the solution you'd like

I would like to set a selection of contacts to a group. As I know I can do this only contact per contact.
I would like to mark the needed contacts via checkbox or something like this and then use a function "add to a group" in which I can choose a group the contacts should be added to. (of course also the opposite way: to remove an added group out of the contact).

### Describe alternatives you've considered

This functionality can also be done only contact by contact and would be helpful to manage with many contacts together.

### Additional context

-/-

**Comment by jensb** [comment] 2023-02-05 10:53
Yes, this would be a huge plus!
In the web UI, this could be solved either by selectiong multiple contacts (CTRL+click) and then dragging them onto the contact you want them to be in, in the left sidebar, or (mobile compatible) toggle selection by simple clicks and showing a "..." (three dots) menu like:

      [5 contacts selected]
      Assign group  >   (submenu showing all groups)
      Remove group >  (submenu showing all groups at least one of the contacts has)
      Delete all 5
      Download VCF
      (possibly more ideas)

I have >500 contacts. Being able to reorganize contact groups in batches would be a huge efficiency plus for me!

**Comment by joshtrichards** [comment] 2024-01-15 23:27
Duplicate of #277

**Closed by joshtrichards** 2024-01-15 23:27 UTC
Labels: enhancement, 0. Needs triage
