### ISSUE TITLE
UI broken on bigger screen

### ISSUE THREAD

**Issue by kimberely27** [nextcloud/contacts#1704] opened 2020-07-15 11:18 UTC
### Describe the bug
When I add a new property/field it messes up the whole UI. For example I added a new Phone & Email field and now I can't figure out which one is what unless I shrink the window and show them correctly.

**To Reproduce**
1. Go to a contact or add a new one
2. Add a new property

**Expected behavior**
![contacts](https://user-images.githubusercontent.com/68330190/87538658-39cf1e80-c6a5-11ea-8038-3115d9c165f3.png)

**Actual behavior**
![contacts2](https://user-images.githubusercontent.com/68330190/87538669-405d9600-c6a5-11ea-92a9-3fb7fb32dc8a.png)

### Server configuration

**Operating system**: Linux (Ubuntu Server)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.18

**Nextcloud version:** 19.0.0

**Contacts version:** 3.3.0

**Updated from an older Nextcloud or fresh install:** Fresh

### Client configuration
**Browser:** FF 76

**Operating system:** Windows 7

#### *Web server error log*
No errors.

PS: I hope I completed this correctly..

**Comment by skjnldsv** [comment] 2020-07-20 16:02
Duplicate of #1327

**Closed by skjnldsv** 2020-07-20 16:02 UTC
Labels: 0. Needs triage, bug
