### ISSUE TITLE
Storing contact avatars seems to have changed and broke for certain clients.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/contacts#1195] opened 2019-07-30 21:38 UTC
I've just noticed that storing the avatar of contacts seems to have changed in the last half year or so. Previously the avatars of contacts where stored like this in the vcf file:

    PHOTO;TYPE=PNG;ENCODING=b:AVATAR_IN_BASE64_FOLLOWS

With the latest version (3.1.3) avatars are being stored like this:

    PHOTO;VALUE=URI:data:image/png;base64,AVATAR_IN_BASE64_FOLLOWS

This, however, seems to break in certain clients (UBports being one of them) as they will not recognize the avatars.

Was that a consciousness change or did I miss something here?

**Comment by skjnldsv** [comment] 2019-07-31 05:56
Vcard 3 I presume?
Duplicate of #477

**Comment by RobertZenz** [comment] 2019-07-31 18:57
I just noticed that you can add Nextcloud Mail to the list of application with which avatars have stopped working. The old ones still work fine, all newly assigned ones do not show up in the mail application.

So, this might require a second look as it is not about a third-party application storing avatars differently then contacts expects, but contacts storing it differently then everybody else expects.

**Comment by skjnldsv** [comment] 2019-07-31 20:21
@RobertZenz are the avatar url failing for you?
can you check by appending `?photo` to the direct dav url of the problematic vcards? :)

Does it generate any error in your nextcloud logs?

**Comment by RobertZenz** [comment] 2019-08-01 18:07
mail tries to fetch the photo but receives a 404.

How do I retrieve the DAV URL of a single card?

No, there's nothing in the log.

**Comment by skjnldsv** [comment] 2019-08-01 19:09
> How do I retrieve the DAV URL of a single card?

this is the download link :)
Instead of clicking you can right click and copy :)

**Comment by RobertZenz** [comment] 2019-08-02 20:53
Okay, that gives me the image (even though it is wrongly named, it's got the name and extension of the vcf file).

**Comment by skjnldsv** [comment] 2019-08-03 05:33
Hum, so loading the image works, but not in contacts?
Can you check if this is a duplicate of #1140 or not?

**Comment by RobertZenz** [comment] 2019-08-03 18:27
No, it works fine in contacts, it doesn't work in mail and other third-party clients in which it *used* to work.

**Comment by skjnldsv** [comment] 2019-08-03 20:35
So, if it works fine in contacts, what is this issue about? :see_no_evil: :grin:

**Comment by RobertZenz** [comment] 2019-08-03 21:06
That it *used to* work fine in *all* applications, now it doesn't. So something changed in contacts that broke it for these applications. And, actually, all I wanted to know is whether that was a deliberate change along the way or if it was a mistake.

**Comment by skjnldsv** [comment] 2019-08-04 07:38
Aaah, ok
The contacts app doesn't have anything to do with other applications :)
You will have to open dedicated issues on those apps :wink:

**Closed by skjnldsv** 2019-08-04 07:38 UTC
Labels: 0. Needs triage, bug

**Comment by RobertZenz** [comment] 2019-08-04 17:42
Okay, I'll try once again: Did you change anything, rather recently, regarding storing of the avatar which *might* have broken other applications? Like changed the vCard version?

**Comment by skjnldsv** [comment] 2019-08-05 05:47
Ah! Make more sense, sorry :)
Well, with the 3.x.x version, we are now properly styoring photo exept for some vcard reader on vcard3 versions :see_no_evil: 
See the mentioned issue above ;)

**Comment by RobertZenz** [comment] 2019-08-26 20:08
Just for your information, this is broken on your end.

I just found the time to do some more tests, and when I replace the "URI" variant of the avatar with the "TYPE PNG" one, everything is working as expected for everyone. The avatars are then also reachable through the web address again, which means that the Nextcloud Mail client can also display them again.

**Comment by skjnldsv** [comment] 2019-08-27 06:10
Yes @RobertZenz you're 100% right
This is what https://github.com/nextcloud/contacts/issues/1140 is all about :)
vcard3 are using a slightly different syntax, and we're not compliant :(

**Comment by skjnldsv** [comment] 2019-08-30 06:51
Fix in https://github.com/nextcloud/contacts/pull/1239
