### ISSUE TITLE
Contact address saved from IOS to Nextcloud Contacts produces incorrectly formatted entry

### ISSUE THREAD

**Issue by afhpayne** [nextcloud/contacts#3104] opened 2022-11-17 20:42 UTC
### Describe the bug

If a contact is created in Apple's Contacts app, and a street address is input, the street address is not correctly formatted when viewed in NC Contacts.

### Steps to reproduce

Create a contact in Apple Contacts
Enter a street address
Open same contact in NC Contacts App

### Expected behavior

The expected format in NC is for each component of the address to be placed in a corresponding box, eg:
Address: 123 Main St
Extended Address: Apt 1A
Postal Code: 99999
[...]

### Actual behavior

The actual behavior is one line of text is created in NC Contacts, looking like this:
;;123 Main St\nApt 1A;Bakersfield;CA;99999;United States

### Contact version

5.0.1

### Operating system

Ubuntu 20.0.4

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment] 2022-11-18 10:10
I believe this is a duplicate of https://github.com/nextcloud/contacts/issues/2982

**Closed by ChristophWurst** 2022-11-18 10:10 UTC
Labels: bug, feature: contacts, 0. Needs triage
