### ISSUE TITLE
Differents contacts IDs types in the popup links, results "contact not found"

### ISSUE THREAD

**Issue by wargreen** [nextcloud/contacts#670] opened 2018-10-19 01:20 UTC
### Steps to reproduce
Import contacts with DavDroid & Evolution
Show contacts from the popup
Click to get contact detail

### Expected behaviour
The contact infos are shown

### Actual behaviour
Error : "Contact Not Found"
Reloading the first contact in the Contacts view

## Server configuration detail

**Operating system:** Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 

7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.2 - 14.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud 9 [...] 14

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - apporder: 0.5.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.3
 - caniupdate: 0.2.0
 - circles: 0.15.1
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dashboard: 5.0.1
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.4.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - groupfolders: 1.3.3
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - metadata: 0.7.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - previewgenerator: 1.1.0
 - provisioning_api: 1.4.0
 - quota_warning: 1.3.0
 - registration: 0.4.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.2.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 4.0.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - announcementcenter
 - encryption
 - files_external
 - flowupload
 - keeweb
 - ojsxc
 - ransomware_protection
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.lebib.org",
        "nuage.lebib.org",
        "claude.lebib.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.lebib.org",
    "dbtype": "mysql",
    "version": "14.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "fr",
    "defaultapp": "activity",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "customclient_android": "https:\/\/f-droid.org\/repository\/browse\/?fdid=com.owncloud.android",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Font",
        "OC\\Preview\\PDF",
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "preview_max_x": 2048,
    "preview_max_scale_factor": 1,
    "theme": "lebib",
    "maintenance": false,
    "log_type": "file",
    "loglevel": "0",
    "log_query": false,
    "mail_smtpauthtype": "PLAIN",
    "updater.release.channel": "stable",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "app.mail.accounts.default": {
        "email": "%USERID%@lebib.org",
        "imapHost": "mail.lebib.org",
        "imapUser": "%EMAIL%",
        "imapPort": 993,
        "imapSslMode": "tls",
        "smtpHost": "mail.lebib.org",
        "smtpUser": "%USERID%",
        "smtpPort": 143,
        "smtpSslMode": "tls"
    },
    "mail_smtpsecure": "ssl",
    "allow_user_to_change_display_name": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

**Operating system:** Debian sid

## Logs

<details><summary>Browser log</summary>

```
Exemple of links in the popup :
https://cloud.lebib.org/index.php/apps/contacts#/contact/pas-id-b4fdbf3c12727feed725d6303dc2352943a96ace
https://cloud.lebib.org/index.php/apps/contacts#/contact/C9B55019-CF9F0986-EDFFA864

Same in the contacts view :
https://cloud.lebib.org/index.php/apps/contacts#/Tous%20les%20contacts/b116fc6ef25192b4a4e7085addc776cb
https://cloud.lebib.org/index.php/apps/contacts#/Tous%20les%20contacts/d9bf825f1ceda802d018731218d91517
```
</details>

<details><summary>Nextcloud log</summary>

```
No logs from the server.
```
</details>

<details><summary>Browser log</summary>

Exemple of links in the popup :
https://cloud.lebib.org/index.php/apps/contacts#/contact/pas-id-b4fdbf3c12727feed725d6303dc2352943a96ace
https://cloud.lebib.org/index.php/apps/contacts#/contact/C9B55019-CF9F0986-EDFFA864

Same in the contacts view :
https://cloud.lebib.org/index.php/apps/contacts#/Tous%20les%20contacts/b116fc6ef25192b4a4e7085addc776cb
https://cloud.lebib.org/index.php/apps/contacts#/Tous%20les%20contacts/d9bf825f1ceda802d018731218d91517
</details>

Thank you for the work !

**Comment by skjnldsv** [comment] 2018-10-19 09:36
Duplicate of #557

**Closed by skjnldsv** 2018-10-19 09:36 UTC
