### ISSUE TITLE
Order of groups

### ISSUE THREAD

**Issue by boldt** [nextcloud/contacts#503] opened 2018-02-28 13:35 UTC
The groups in my nextcloud 13.0.0 (installed with docker) are not ordered.

### Expected behaviour

* Having the groups in alphabetical order or provide an option how to order the groups.

### Actual behaviour

* The groups are shown in the order as they were created.

**Comment by skjnldsv** [comment] 2018-02-28 14:54
Duplicate of #431

**Closed by skjnldsv** 2018-02-28 14:54 UTC
