### ISSUE TITLE
Can't import user in MS Internet Explorer

### ISSUE THREAD

**Issue by freakms** [nextcloud/contacts#551] opened 2018-04-28 08:40 UTC
### Steps to reproduce
1. Open the Contacts App
2. click settings
3.click import
4. choose the import file

### Expected behaviour
The Contacts should be imported to the chosen addressbook

### Actual behaviour
In Firefox and MS Edge, i am able to choose the file, but nothing happened. I am waiting but no contacts are imported and the loadcircle doesnt stop.

In MS Internet Explorer, I am not able to choose any file. I got the message, that the import was deactivated, cause there are no writable addressbooks found. 

### Server configuration

**Operating system**:
synology dsm
**Web server:**
nginx/Apache
**Database:**
Maria DB 5
**PHP version:**
5.6/7.0 error is on both
**Nextcloud version:** (see Nextcloud admin page)
13.0.2, 
**Contacts version:** (see Nextcloud apps page)
2.1.3
**Updated from an older Nextcloud or fresh install:**
fresh install
**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
actually no- tested with both
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox 59.0.2 64bit/ Microsoft Edge / MS Internet Explorer 11.402 
**Operating system:**
Windows 10 
**CardDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"B2ARagVNj5mbQTREv963","level":3,"time":"2018-04-28T08:27:50+00:00","remoteAddr":"31.16.181.198","user":"mschad","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/apps\/categories","message":"Invalid argument supplied for foreach() at \/volume1\/web\/nextcloud\/lib\/private\/Installer.php#406","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; Trident\/7.0; rv:11.0) like Gecko","version":"13.0.2.1"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment] 2018-04-28 09:54
Hello! We're gonna need the browser log as well! :)

**Comment by freakms** [comment] 2018-04-28 10:04
[Firefox_log.log](https://github.com/nextcloud/contacts/files/1957567/Firefox_log.log)

**Comment by skjnldsv** [comment] 2018-04-30 05:33
Oups, sorry, it's not this log :)
It's the console log, opn the dev tools and click the consqole tab. Refresh and reproduce your case :)

**Comment by freakms** [comment] 2018-04-30 07:57
oh ok...
[console_log.log](https://github.com/nextcloud/contacts/files/1959822/console_log.log)

**Comment by skjnldsv** [comment] 2018-04-30 07:59
Thanks :)
Duplicate of #433

**Comment by skjnldsv** [comment] 2018-06-21 04:51
Even if it's a duplicate, know that we do not support ie on contacts.

**Closed by skjnldsv** 2018-06-21 04:51 UTC
Labels: wontfix
